# Copyright (c) 2024 Realtek Semiconductor Corp.
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.10)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/screen_410_502_squareline)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/screen_410_502_lvgl)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/benchmark)

