#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('gui_port', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH)

Return('group')
