#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

# building script for LVGL port

from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')

# Get LVGL root path - go up from win32_sim/port/lvgl_port to lvgl_v9
# Path: win32_sim/port/lvgl_port -> win32_sim -> rtk -> lvgl_v9
LVGLV9_ROOT = os.path.abspath(os.path.join(cwd, '../../../../'))

CPPPATH = [cwd]
CPPPATH += [LVGLV9_ROOT]

group = DefineGroup('lvgl_port', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
