# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('rtk_gui', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
