#if defined _WIN32
extern unsigned char resource_root[];

#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(resource_root + 0x000002b8)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(resource_root + 0x00009f38)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(resource_root + 0x000390f8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(resource_root + 0x00042d78)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(resource_root + 0x0004c9f8)
#define   CLEAR_BG_BIN                            (void *)(resource_root + 0x0004cc78)
#define   CAPSULE_MUTE_OFF_BIN                    (void *)(resource_root + 0x00064b38)
#define   CAPSULE_MUTE_ON_BIN                     (void *)(resource_root + 0x000654f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                (void *)(resource_root + 0x00065eb8)
#define   CAPSULE_NOBOTHER_ON_BIN                 (void *)(resource_root + 0x00066ef8)
#define   CAPSULE_PHONE_OFF_BIN                   (void *)(resource_root + 0x00067f38)
#define   CAPSULE_PHONE_ON_BIN                    (void *)(resource_root + 0x00068f78)
#define   CONTROL_CAPSULE_BIN                     (void *)(resource_root + 0x00069fb8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(resource_root + 0x00070538)
#define   CONTROL_LTE_ON_BIN                      (void *)(resource_root + 0x00085d78)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(resource_root + 0x0009b5b8)
#define   CONTROL_MUTE_ON_BIN                     (void *)(resource_root + 0x000b0df8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(resource_root + 0x000c6638)
#define   CONTROL_PHONE_ON_BIN                    (void *)(resource_root + 0x000dbe78)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(resource_root + 0x000f16b8)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(resource_root + 0x00106ef8)
#define   CONTROL_PAD_BIN                         (void *)(resource_root + 0x0011c738)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(resource_root + 0x00131f78)
#define   CONTROL_WIFI_ON_BIN                     (void *)(resource_root + 0x001477b8)
#define   MUTE_OFF_ICON_BIN                       (void *)(resource_root + 0x0015cff8)
#define   MUTE_ON_ICON_BIN                        (void *)(resource_root + 0x0015d9b8)
#define   MENU_BAR_BG_BIN                         (void *)(resource_root + 0x0015e378)
#define   MSG_TAB_BG_BIN                          (void *)(resource_root + 0x001927b8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN            (void *)(resource_root + 0x001ddc78)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN             (void *)(resource_root + 0x001e1338)
#define   APP_MUSIC_BTN_LOOP_BIN                  (void *)(resource_root + 0x001e49b8)
#define   APP_MUSIC_BTN_NEXT_BIN                  (void *)(resource_root + 0x001e52f8)
#define   APP_MUSIC_BTN_PAUSE_BIN                 (void *)(resource_root + 0x001e8f38)
#define   APP_MUSIC_BTN_PLAY_BIN                  (void *)(resource_root + 0x001eee78)
#define   APP_MUSIC_BTN_PREV_BIN                  (void *)(resource_root + 0x001f4db8)
#define   APP_MUSIC_BTN_RND_BIN                   (void *)(resource_root + 0x001f89f8)
#define   APP_MUSIC_CORNER_LEFT_BIN               (void *)(resource_root + 0x001f9338)
#define   APP_MUSIC_CORNER_RIGHT_BIN              (void *)(resource_root + 0x001f9878)
#define   APP_MUSIC_COVER_1_BIN                   (void *)(resource_root + 0x001f9db8)
#define   APP_MUSIC_COVER_2_BIN                   (void *)(resource_root + 0x00217f38)
#define   APP_MUSIC_COVER_3_BIN                   (void *)(resource_root + 0x002360b8)
#define   APP_MUSIC_ICN_CHART_BIN                 (void *)(resource_root + 0x00254238)
#define   APP_MUSIC_ICN_CHAT_BIN                  (void *)(resource_root + 0x00254b78)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN              (void *)(resource_root + 0x002554b8)
#define   APP_MUSIC_ICN_HEART_BIN                 (void *)(resource_root + 0x00255df8)
#define   APP_MUSIC_ICN_SLIDER_BIN                (void *)(resource_root + 0x00256738)
#define   APP_MUSIC_LIST_BORDER_BIN               (void *)(resource_root + 0x00257cf8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN               (void *)(resource_root + 0x00258e38)
#define   APP_MUSIC_WAVE_TOP_BIN                  (void *)(resource_root + 0x002640f8)
#define   OPTION_BAR_BG_BIN                       (void *)(resource_root + 0x0026f3b8)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(resource_root + 0x0028a978)
#define   OPTION_TAB_BG_BIN                       (void *)(resource_root + 0x002a5f38)
#define   PATH02_BIN                              (void *)(resource_root + 0x002ca8f8)
#define   PATH03_BIN                              (void *)(resource_root + 0x002cac38)
#define   PATH04_BIN                              (void *)(resource_root + 0x002cb138)
#define   PATH05_BIN                              (void *)(resource_root + 0x002cb7b8)
#define   PATH06_BIN                              (void *)(resource_root + 0x002cbfb8)
#define   PATH07_BIN                              (void *)(resource_root + 0x002cc938)
#define   PATH08_BIN                              (void *)(resource_root + 0x002cd478)
#define   PATH09_BIN                              (void *)(resource_root + 0x002ce138)
#define   PATH10_BIN                              (void *)(resource_root + 0x002cef78)
#define   PATH11_BIN                              (void *)(resource_root + 0x002cff38)
#define   PATH12_BIN                              (void *)(resource_root + 0x002d10b8)
#define   PATH13_BIN                              (void *)(resource_root + 0x002d23b8)
#define   PATH14_BIN                              (void *)(resource_root + 0x002d3838)
#define   PATH15_BIN                              (void *)(resource_root + 0x002d4e38)
#define   PATH16_BIN                              (void *)(resource_root + 0x002d65f8)
#define   PATH17_BIN                              (void *)(resource_root + 0x002d7f38)
#define   PATH18_BIN                              (void *)(resource_root + 0x002d99f8)
#define   UI_TEXT_0_BIN                           (void *)(resource_root + 0x002db6f8)
#define   UI_TEXT_1_BIN                           (void *)(resource_root + 0x002dd378)
#define   UI_TEXT_2_BIN                           (void *)(resource_root + 0x002debb8)
#define   UI_TEXT_3_BIN                           (void *)(resource_root + 0x002e08b8)
#define   UI_TEXT_4_BIN                           (void *)(resource_root + 0x002e2638)
#define   UI_TEXT_5_BIN                           (void *)(resource_root + 0x002e44f8)
#define   UI_TEXT_6_BIN                           (void *)(resource_root + 0x002e62b8)
#define   UI_TEXT_7_BIN                           (void *)(resource_root + 0x002e7f38)
#define   UI_TEXT_8_BIN                           (void *)(resource_root + 0x002e9b78)
#define   UI_TEXT_9_BIN                           (void *)(resource_root + 0x002eb8f8)
#define   UI_TEXT_COLON_BIN                       (void *)(resource_root + 0x002ed578)
#define   UI_TEXT_PERCENT_BIN                     (void *)(resource_root + 0x002edbf8)
#define   UI_ARROW_DOWN_BIN                       (void *)(resource_root + 0x002f10b8)
#define   UI_ARROW_UP_BIN                         (void *)(resource_root + 0x002f20f8)
#define   UI_BG_ICON_BIN                          (void *)(resource_root + 0x002f3138)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(resource_root + 0x002f7f78)
#define   UI_CARD_APPVIEW_BIN                     (void *)(resource_root + 0x0032df38)
#define   UI_CARD_BG_BIN                          (void *)(resource_root + 0x00338f38)
#define   UI_CARD_CALENDAR_BIN                    (void *)(resource_root + 0x00353f38)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x0036ef38)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x0038bd38)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(resource_root + 0x003c1cf8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(resource_root + 0x003cb978)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(resource_root + 0x003d55f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN              (void *)(resource_root + 0x003df278)
#define   UI_IWATCH_ICON_BIN                      (void *)(resource_root + 0x003e8ef8)
#define   UI_LINE_STILL_BIN                       (void *)(resource_root + 0x003e9e78)
#define   UI_MENU_CARD_BIN                        (void *)(resource_root + 0x003ea338)
#define   UI_MENU_CELLULAR_BIN                    (void *)(resource_root + 0x003f3838)
#define   UI_MESSAGE_ICON_BIN                     (void *)(resource_root + 0x004005f8)
#define   UI_PERSON_ICON_BIN                      (void *)(resource_root + 0x004038f8)
#define   W3W_BIN                                 (void *)(resource_root + 0x00403f78)
#define   WATCH_HOUR_HAND_BIN                     (void *)(resource_root + 0x004ccfb8)
#define   WATCH_MASK_BIN                          (void *)(resource_root + 0x004cde78)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(resource_root + 0x004ce0f8)
#define   WATCH_SECOND_HAND_BIN                   (void *)(resource_root + 0x004cfdf8)
#define   UI_CLOCK_WEATHER_ICON_BIN               (void *)(resource_root + 0x004d0138)
#define   UI_WEATHER_CLEAR_BIN                    (void *)(resource_root + 0x004d9db8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(resource_root + 0x004dabf8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(resource_root + 0x004dbd38)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(resource_root + 0x004dcc78)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(resource_root + 0x004ddbb8)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(resource_root + 0x004deaf8)
#define   UI_CARD_WEATHER_DAY_BIN                 (void *)(resource_root + 0x004df938)
#define   UI_CARD_WEATHER_NIGHT_BIN               (void *)(resource_root + 0x004fa938)
#define   WEATHER_DAY_SCR_BG_BIN                  (void *)(resource_root + 0x00515938)
#define   WEATHER_LOCATION_BIN                    (void *)(resource_root + 0x0057a178)
#define   WEATHER_NIGHT_SCR_BG_BIN                (void *)(resource_root + 0x0057a938)

#else
#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(0x025426b8)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(0x0254c338)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(0x0257b4f8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(0x02585178)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(0x0258edf8)
#define   CLEAR_BG_BIN                            (void *)(0x0258f078)
#define   CAPSULE_MUTE_OFF_BIN                    (void *)(0x025a6f38)
#define   CAPSULE_MUTE_ON_BIN                     (void *)(0x025a78f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                (void *)(0x025a82b8)
#define   CAPSULE_NOBOTHER_ON_BIN                 (void *)(0x025a92f8)
#define   CAPSULE_PHONE_OFF_BIN                   (void *)(0x025aa338)
#define   CAPSULE_PHONE_ON_BIN                    (void *)(0x025ab378)
#define   CONTROL_CAPSULE_BIN                     (void *)(0x025ac3b8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(0x025b2938)
#define   CONTROL_LTE_ON_BIN                      (void *)(0x025c8178)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(0x025dd9b8)
#define   CONTROL_MUTE_ON_BIN                     (void *)(0x025f31f8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(0x02608a38)
#define   CONTROL_PHONE_ON_BIN                    (void *)(0x0261e278)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(0x02633ab8)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(0x026492f8)
#define   CONTROL_PAD_BIN                         (void *)(0x0265eb38)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(0x02674378)
#define   CONTROL_WIFI_ON_BIN                     (void *)(0x02689bb8)
#define   MUTE_OFF_ICON_BIN                       (void *)(0x0269f3f8)
#define   MUTE_ON_ICON_BIN                        (void *)(0x0269fdb8)
#define   MENU_BAR_BG_BIN                         (void *)(0x026a0778)
#define   MSG_TAB_BG_BIN                          (void *)(0x026d4bb8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN            (void *)(0x02720078)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN             (void *)(0x02723738)
#define   APP_MUSIC_BTN_LOOP_BIN                  (void *)(0x02726db8)
#define   APP_MUSIC_BTN_NEXT_BIN                  (void *)(0x027276f8)
#define   APP_MUSIC_BTN_PAUSE_BIN                 (void *)(0x0272b338)
#define   APP_MUSIC_BTN_PLAY_BIN                  (void *)(0x02731278)
#define   APP_MUSIC_BTN_PREV_BIN                  (void *)(0x027371b8)
#define   APP_MUSIC_BTN_RND_BIN                   (void *)(0x0273adf8)
#define   APP_MUSIC_CORNER_LEFT_BIN               (void *)(0x0273b738)
#define   APP_MUSIC_CORNER_RIGHT_BIN              (void *)(0x0273bc78)
#define   APP_MUSIC_COVER_1_BIN                   (void *)(0x0273c1b8)
#define   APP_MUSIC_COVER_2_BIN                   (void *)(0x0275a338)
#define   APP_MUSIC_COVER_3_BIN                   (void *)(0x027784b8)
#define   APP_MUSIC_ICN_CHART_BIN                 (void *)(0x02796638)
#define   APP_MUSIC_ICN_CHAT_BIN                  (void *)(0x02796f78)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN              (void *)(0x027978b8)
#define   APP_MUSIC_ICN_HEART_BIN                 (void *)(0x027981f8)
#define   APP_MUSIC_ICN_SLIDER_BIN                (void *)(0x02798b38)
#define   APP_MUSIC_LIST_BORDER_BIN               (void *)(0x0279a0f8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN               (void *)(0x0279b238)
#define   APP_MUSIC_WAVE_TOP_BIN                  (void *)(0x027a64f8)
#define   OPTION_BAR_BG_BIN                       (void *)(0x027b17b8)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(0x027ccd78)
#define   OPTION_TAB_BG_BIN                       (void *)(0x027e8338)
#define   PATH02_BIN                              (void *)(0x0280ccf8)
#define   PATH03_BIN                              (void *)(0x0280d038)
#define   PATH04_BIN                              (void *)(0x0280d538)
#define   PATH05_BIN                              (void *)(0x0280dbb8)
#define   PATH06_BIN                              (void *)(0x0280e3b8)
#define   PATH07_BIN                              (void *)(0x0280ed38)
#define   PATH08_BIN                              (void *)(0x0280f878)
#define   PATH09_BIN                              (void *)(0x02810538)
#define   PATH10_BIN                              (void *)(0x02811378)
#define   PATH11_BIN                              (void *)(0x02812338)
#define   PATH12_BIN                              (void *)(0x028134b8)
#define   PATH13_BIN                              (void *)(0x028147b8)
#define   PATH14_BIN                              (void *)(0x02815c38)
#define   PATH15_BIN                              (void *)(0x02817238)
#define   PATH16_BIN                              (void *)(0x028189f8)
#define   PATH17_BIN                              (void *)(0x0281a338)
#define   PATH18_BIN                              (void *)(0x0281bdf8)
#define   UI_TEXT_0_BIN                           (void *)(0x0281daf8)
#define   UI_TEXT_1_BIN                           (void *)(0x0281f778)
#define   UI_TEXT_2_BIN                           (void *)(0x02820fb8)
#define   UI_TEXT_3_BIN                           (void *)(0x02822cb8)
#define   UI_TEXT_4_BIN                           (void *)(0x02824a38)
#define   UI_TEXT_5_BIN                           (void *)(0x028268f8)
#define   UI_TEXT_6_BIN                           (void *)(0x028286b8)
#define   UI_TEXT_7_BIN                           (void *)(0x0282a338)
#define   UI_TEXT_8_BIN                           (void *)(0x0282bf78)
#define   UI_TEXT_9_BIN                           (void *)(0x0282dcf8)
#define   UI_TEXT_COLON_BIN                       (void *)(0x0282f978)
#define   UI_TEXT_PERCENT_BIN                     (void *)(0x0282fff8)
#define   UI_ARROW_DOWN_BIN                       (void *)(0x028334b8)
#define   UI_ARROW_UP_BIN                         (void *)(0x028344f8)
#define   UI_BG_ICON_BIN                          (void *)(0x02835538)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(0x0283a378)
#define   UI_CARD_APPVIEW_BIN                     (void *)(0x02870338)
#define   UI_CARD_BG_BIN                          (void *)(0x0287b338)
#define   UI_CARD_CALENDAR_BIN                    (void *)(0x02896338)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x028b1338)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x028ce138)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(0x029040f8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(0x0290dd78)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(0x029179f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN              (void *)(0x02921678)
#define   UI_IWATCH_ICON_BIN                      (void *)(0x0292b2f8)
#define   UI_LINE_STILL_BIN                       (void *)(0x0292c278)
#define   UI_MENU_CARD_BIN                        (void *)(0x0292c738)
#define   UI_MENU_CELLULAR_BIN                    (void *)(0x02935c38)
#define   UI_MESSAGE_ICON_BIN                     (void *)(0x029429f8)
#define   UI_PERSON_ICON_BIN                      (void *)(0x02945cf8)
#define   W3W_BIN                                 (void *)(0x02946378)
#define   WATCH_HOUR_HAND_BIN                     (void *)(0x02a0f3b8)
#define   WATCH_MASK_BIN                          (void *)(0x02a10278)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(0x02a104f8)
#define   WATCH_SECOND_HAND_BIN                   (void *)(0x02a121f8)
#define   UI_CLOCK_WEATHER_ICON_BIN               (void *)(0x02a12538)
#define   UI_WEATHER_CLEAR_BIN                    (void *)(0x02a1c1b8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(0x02a1cff8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(0x02a1e138)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(0x02a1f078)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(0x02a1ffb8)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(0x02a20ef8)
#define   UI_CARD_WEATHER_DAY_BIN                 (void *)(0x02a21d38)
#define   UI_CARD_WEATHER_NIGHT_BIN               (void *)(0x02a3cd38)
#define   WEATHER_DAY_SCR_BG_BIN                  (void *)(0x02a57d38)
#define   WEATHER_LOCATION_BIN                    (void *)(0x02abc578)
#define   WEATHER_NIGHT_SCR_BG_BIN                (void *)(0x02abcd38)

#endif
