#if defined _WIN32
extern unsigned char resource_root[];

#define   DESC_FACE_BIN                            (void *)(resource_root + 0x000002f8)
#define   UI_CLOCK_ACTIVITY_ICON_BIN               (void *)(resource_root + 0x00015eb8)
#define   UI_CLOCK_CARD_WEATHER_BIN                (void *)(resource_root + 0x0001fb38)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN           (void *)(resource_root + 0x0004ecf8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN              (void *)(resource_root + 0x00058978)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN        (void *)(resource_root + 0x000625f8)
#define   CLEAR_BG_BIN                             (void *)(resource_root + 0x00062878)
#define   CAPSULE_MUTE_OFF_BIN                     (void *)(resource_root + 0x0007a738)
#define   CAPSULE_MUTE_ON_BIN                      (void *)(resource_root + 0x0007b0f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                 (void *)(resource_root + 0x0007bab8)
#define   CAPSULE_NOBOTHER_ON_BIN                  (void *)(resource_root + 0x0007caf8)
#define   CAPSULE_PHONE_OFF_BIN                    (void *)(resource_root + 0x0007db38)
#define   CAPSULE_PHONE_ON_BIN                     (void *)(resource_root + 0x0007eb78)
#define   CONTROL_CAPSULE_BIN                      (void *)(resource_root + 0x0007fbb8)
#define   CONTROL_LTE_OFF_BIN                      (void *)(resource_root + 0x00086138)
#define   CONTROL_LTE_ON_BIN                       (void *)(resource_root + 0x0009b978)
#define   CONTROL_MUTE_OFF_BIN                     (void *)(resource_root + 0x000b11b8)
#define   CONTROL_MUTE_ON_BIN                      (void *)(resource_root + 0x000c69f8)
#define   CONTROL_PHONE_OFF_BIN                    (void *)(resource_root + 0x000dc238)
#define   CONTROL_PHONE_ON_BIN                     (void *)(resource_root + 0x000f1a78)
#define   CONTROL_NOBOTHER_OFF_BIN                 (void *)(resource_root + 0x001072b8)
#define   CONTROL_NOBOTHER_ON_BIN                  (void *)(resource_root + 0x0011caf8)
#define   CONTROL_PAD_BIN                          (void *)(resource_root + 0x00132338)
#define   CONTROL_WIFI_OFF_BIN                     (void *)(resource_root + 0x00147b78)
#define   CONTROL_WIFI_ON_BIN                      (void *)(resource_root + 0x0015d3b8)
#define   MUTE_OFF_ICON_BIN                        (void *)(resource_root + 0x00172bf8)
#define   MUTE_ON_ICON_BIN                         (void *)(resource_root + 0x001735b8)
#define   MENU_BAR_BG_BIN                          (void *)(resource_root + 0x00173f78)
#define   MSG_TAB_BG_BIN                           (void *)(resource_root + 0x001a83b8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN             (void *)(resource_root + 0x001f3878)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN              (void *)(resource_root + 0x001f6f38)
#define   APP_MUSIC_BTN_LOOP_BIN                   (void *)(resource_root + 0x001fa5b8)
#define   APP_MUSIC_BTN_NEXT_BIN                   (void *)(resource_root + 0x001faef8)
#define   APP_MUSIC_BTN_PAUSE_BIN                  (void *)(resource_root + 0x001feb38)
#define   APP_MUSIC_BTN_PLAY_BIN                   (void *)(resource_root + 0x00204a78)
#define   APP_MUSIC_BTN_PREV_BIN                   (void *)(resource_root + 0x0020a9b8)
#define   APP_MUSIC_BTN_RND_BIN                    (void *)(resource_root + 0x0020e5f8)
#define   APP_MUSIC_CORNER_LEFT_BIN                (void *)(resource_root + 0x0020ef38)
#define   APP_MUSIC_CORNER_RIGHT_BIN               (void *)(resource_root + 0x0020f478)
#define   APP_MUSIC_COVER_1_BIN                    (void *)(resource_root + 0x0020f9b8)
#define   APP_MUSIC_COVER_2_BIN                    (void *)(resource_root + 0x0022db38)
#define   APP_MUSIC_COVER_3_BIN                    (void *)(resource_root + 0x0024bcb8)
#define   APP_MUSIC_ICN_CHART_BIN                  (void *)(resource_root + 0x00269e38)
#define   APP_MUSIC_ICN_CHAT_BIN                   (void *)(resource_root + 0x0026a778)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN               (void *)(resource_root + 0x0026b0b8)
#define   APP_MUSIC_ICN_HEART_BIN                  (void *)(resource_root + 0x0026b9f8)
#define   APP_MUSIC_ICN_SLIDER_BIN                 (void *)(resource_root + 0x0026c338)
#define   APP_MUSIC_LIST_BORDER_BIN                (void *)(resource_root + 0x0026d8f8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN                (void *)(resource_root + 0x0026ea38)
#define   APP_MUSIC_WAVE_TOP_BIN                   (void *)(resource_root + 0x00279cf8)
#define   OPTION_BAR_BG_BIN                        (void *)(resource_root + 0x00284fb8)
#define   OPTION_BAR_WHITE_BG_BIN                  (void *)(resource_root + 0x002a0578)
#define   OPTION_TAB_BG_BIN                        (void *)(resource_root + 0x002bbb38)
#define   PATH02_BIN                               (void *)(resource_root + 0x002e04f8)
#define   PATH03_BIN                               (void *)(resource_root + 0x002e0838)
#define   PATH04_BIN                               (void *)(resource_root + 0x002e0d38)
#define   PATH05_BIN                               (void *)(resource_root + 0x002e13b8)
#define   PATH06_BIN                               (void *)(resource_root + 0x002e1bb8)
#define   PATH07_BIN                               (void *)(resource_root + 0x002e2538)
#define   PATH08_BIN                               (void *)(resource_root + 0x002e3078)
#define   PATH09_BIN                               (void *)(resource_root + 0x002e3d38)
#define   PATH10_BIN                               (void *)(resource_root + 0x002e4b78)
#define   PATH11_BIN                               (void *)(resource_root + 0x002e5b38)
#define   PATH12_BIN                               (void *)(resource_root + 0x002e6cb8)
#define   PATH13_BIN                               (void *)(resource_root + 0x002e7fb8)
#define   PATH14_BIN                               (void *)(resource_root + 0x002e9438)
#define   PATH15_BIN                               (void *)(resource_root + 0x002eaa38)
#define   PATH16_BIN                               (void *)(resource_root + 0x002ec1f8)
#define   PATH17_BIN                               (void *)(resource_root + 0x002edb38)
#define   PATH18_BIN                               (void *)(resource_root + 0x002ef5f8)
#define   UI_TEXT_0_BIN                            (void *)(resource_root + 0x002f12f8)
#define   UI_TEXT_1_BIN                            (void *)(resource_root + 0x002f2f78)
#define   UI_TEXT_2_BIN                            (void *)(resource_root + 0x002f47b8)
#define   UI_TEXT_3_BIN                            (void *)(resource_root + 0x002f64b8)
#define   UI_TEXT_4_BIN                            (void *)(resource_root + 0x002f8238)
#define   UI_TEXT_5_BIN                            (void *)(resource_root + 0x002fa0f8)
#define   UI_TEXT_6_BIN                            (void *)(resource_root + 0x002fbeb8)
#define   UI_TEXT_7_BIN                            (void *)(resource_root + 0x002fdb38)
#define   UI_TEXT_8_BIN                            (void *)(resource_root + 0x002ff778)
#define   UI_TEXT_9_BIN                            (void *)(resource_root + 0x003014f8)
#define   UI_TEXT_COLON_BIN                        (void *)(resource_root + 0x00303178)
#define   UI_TEXT_PERCENT_BIN                      (void *)(resource_root + 0x003037f8)
#define   UI_ARROW_DOWN_BIN                        (void *)(resource_root + 0x00306cb8)
#define   UI_ARROW_UP_BIN                          (void *)(resource_root + 0x00307cf8)
#define   UI_BG_ICON_BIN                           (void *)(resource_root + 0x00308d38)
#define   UI_CARD_ACTIVITY_BIN                     (void *)(resource_root + 0x0030db78)
#define   UI_CARD_APPVIEW_BIN                      (void *)(resource_root + 0x00343b38)
#define   UI_CARD_BG_BIN                           (void *)(resource_root + 0x0034eb38)
#define   UI_CARD_CALENDAR_BIN                     (void *)(resource_root + 0x00369b38)
#define   UI_CARD_CLOCKCIRCLE_BIN                  (void *)(resource_root + 0x00384b38)
#define   UI_CARD_WEATHER_BIN                      (void *)(resource_root + 0x003a1938)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN            (void *)(resource_root + 0x003d78f8)
#define   UI_CLOCK_MUSIC_ICON_BIN                  (void *)(resource_root + 0x003e1578)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN             (void *)(resource_root + 0x003eb1f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN               (void *)(resource_root + 0x003f4e78)
#define   UI_IWATCH_ICON_BIN                       (void *)(resource_root + 0x003feaf8)
#define   UI_LINE_STILL_BIN                        (void *)(resource_root + 0x003ffa78)
#define   UI_MENU_CARD_BIN                         (void *)(resource_root + 0x003fff38)
#define   UI_MENU_CELLULAR_BIN                     (void *)(resource_root + 0x00409438)
#define   UI_MESSAGE_ICON_BIN                      (void *)(resource_root + 0x004161f8)
#define   UI_PERSON_ICON_BIN                       (void *)(resource_root + 0x004194f8)
#define   W3W_BIN                                  (void *)(resource_root + 0x00419b78)
#define   WATCH_HOUR_HAND_BIN                      (void *)(resource_root + 0x004e2bb8)
#define   WATCH_MASK_BIN                           (void *)(resource_root + 0x004e3a78)
#define   WATCH_MINUTE_HAND_BIN                    (void *)(resource_root + 0x004e3cf8)
#define   WATCH_SECOND_HAND_BIN                    (void *)(resource_root + 0x004e59f8)
#define   UI_CLOCK_WEATHER_ICON_BIN                (void *)(resource_root + 0x004e5d38)
#define   UI_WEATHER_CLEAR_BIN                     (void *)(resource_root + 0x004ef9b8)
#define   UI_WEATHER_CLOUDY_BIN                    (void *)(resource_root + 0x004f07f8)
#define   UI_WEATHER_RAIN_L_BIN                    (void *)(resource_root + 0x004f1938)
#define   UI_WEATHER_RAIN_M_BIN                    (void *)(resource_root + 0x004f2878)
#define   UI_WEATHER_RAIN_S_BIN                    (void *)(resource_root + 0x004f37b8)
#define   UI_WEATHER_SUNNY_BIN                     (void *)(resource_root + 0x004f46f8)
#define   UI_CARD_WEATHER_DAY_BIN                  (void *)(resource_root + 0x004f5538)
#define   UI_CARD_WEATHER_NIGHT_BIN                (void *)(resource_root + 0x00510538)
#define   WEATHER_DAY_SCR_BG_BIN                   (void *)(resource_root + 0x0052b538)
#define   WEATHER_LOCATION_BIN                     (void *)(resource_root + 0x0058fd78)
#define   WEATHER_NIGHT_SCR_BG_BIN                 (void *)(resource_root + 0x00590538)

#else
#define   DESC_FACE_BIN                            (void *)(0x704d16f8)
#define   UI_CLOCK_ACTIVITY_ICON_BIN               (void *)(0x704e72b8)
#define   UI_CLOCK_CARD_WEATHER_BIN                (void *)(0x704f0f38)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN           (void *)(0x705200f8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN              (void *)(0x70529d78)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN        (void *)(0x705339f8)
#define   CLEAR_BG_BIN                             (void *)(0x70533c78)
#define   CAPSULE_MUTE_OFF_BIN                     (void *)(0x7054bb38)
#define   CAPSULE_MUTE_ON_BIN                      (void *)(0x7054c4f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                 (void *)(0x7054ceb8)
#define   CAPSULE_NOBOTHER_ON_BIN                  (void *)(0x7054def8)
#define   CAPSULE_PHONE_OFF_BIN                    (void *)(0x7054ef38)
#define   CAPSULE_PHONE_ON_BIN                     (void *)(0x7054ff78)
#define   CONTROL_CAPSULE_BIN                      (void *)(0x70550fb8)
#define   CONTROL_LTE_OFF_BIN                      (void *)(0x70557538)
#define   CONTROL_LTE_ON_BIN                       (void *)(0x7056cd78)
#define   CONTROL_MUTE_OFF_BIN                     (void *)(0x705825b8)
#define   CONTROL_MUTE_ON_BIN                      (void *)(0x70597df8)
#define   CONTROL_PHONE_OFF_BIN                    (void *)(0x705ad638)
#define   CONTROL_PHONE_ON_BIN                     (void *)(0x705c2e78)
#define   CONTROL_NOBOTHER_OFF_BIN                 (void *)(0x705d86b8)
#define   CONTROL_NOBOTHER_ON_BIN                  (void *)(0x705edef8)
#define   CONTROL_PAD_BIN                          (void *)(0x70603738)
#define   CONTROL_WIFI_OFF_BIN                     (void *)(0x70618f78)
#define   CONTROL_WIFI_ON_BIN                      (void *)(0x7062e7b8)
#define   MUTE_OFF_ICON_BIN                        (void *)(0x70643ff8)
#define   MUTE_ON_ICON_BIN                         (void *)(0x706449b8)
#define   MENU_BAR_BG_BIN                          (void *)(0x70645378)
#define   MSG_TAB_BG_BIN                           (void *)(0x706797b8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN             (void *)(0x706c4c78)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN              (void *)(0x706c8338)
#define   APP_MUSIC_BTN_LOOP_BIN                   (void *)(0x706cb9b8)
#define   APP_MUSIC_BTN_NEXT_BIN                   (void *)(0x706cc2f8)
#define   APP_MUSIC_BTN_PAUSE_BIN                  (void *)(0x706cff38)
#define   APP_MUSIC_BTN_PLAY_BIN                   (void *)(0x706d5e78)
#define   APP_MUSIC_BTN_PREV_BIN                   (void *)(0x706dbdb8)
#define   APP_MUSIC_BTN_RND_BIN                    (void *)(0x706df9f8)
#define   APP_MUSIC_CORNER_LEFT_BIN                (void *)(0x706e0338)
#define   APP_MUSIC_CORNER_RIGHT_BIN               (void *)(0x706e0878)
#define   APP_MUSIC_COVER_1_BIN                    (void *)(0x706e0db8)
#define   APP_MUSIC_COVER_2_BIN                    (void *)(0x706fef38)
#define   APP_MUSIC_COVER_3_BIN                    (void *)(0x7071d0b8)
#define   APP_MUSIC_ICN_CHART_BIN                  (void *)(0x7073b238)
#define   APP_MUSIC_ICN_CHAT_BIN                   (void *)(0x7073bb78)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN               (void *)(0x7073c4b8)
#define   APP_MUSIC_ICN_HEART_BIN                  (void *)(0x7073cdf8)
#define   APP_MUSIC_ICN_SLIDER_BIN                 (void *)(0x7073d738)
#define   APP_MUSIC_LIST_BORDER_BIN                (void *)(0x7073ecf8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN                (void *)(0x7073fe38)
#define   APP_MUSIC_WAVE_TOP_BIN                   (void *)(0x7074b0f8)
#define   OPTION_BAR_BG_BIN                        (void *)(0x707563b8)
#define   OPTION_BAR_WHITE_BG_BIN                  (void *)(0x70771978)
#define   OPTION_TAB_BG_BIN                        (void *)(0x7078cf38)
#define   PATH02_BIN                               (void *)(0x707b18f8)
#define   PATH03_BIN                               (void *)(0x707b1c38)
#define   PATH04_BIN                               (void *)(0x707b2138)
#define   PATH05_BIN                               (void *)(0x707b27b8)
#define   PATH06_BIN                               (void *)(0x707b2fb8)
#define   PATH07_BIN                               (void *)(0x707b3938)
#define   PATH08_BIN                               (void *)(0x707b4478)
#define   PATH09_BIN                               (void *)(0x707b5138)
#define   PATH10_BIN                               (void *)(0x707b5f78)
#define   PATH11_BIN                               (void *)(0x707b6f38)
#define   PATH12_BIN                               (void *)(0x707b80b8)
#define   PATH13_BIN                               (void *)(0x707b93b8)
#define   PATH14_BIN                               (void *)(0x707ba838)
#define   PATH15_BIN                               (void *)(0x707bbe38)
#define   PATH16_BIN                               (void *)(0x707bd5f8)
#define   PATH17_BIN                               (void *)(0x707bef38)
#define   PATH18_BIN                               (void *)(0x707c09f8)
#define   UI_TEXT_0_BIN                            (void *)(0x707c26f8)
#define   UI_TEXT_1_BIN                            (void *)(0x707c4378)
#define   UI_TEXT_2_BIN                            (void *)(0x707c5bb8)
#define   UI_TEXT_3_BIN                            (void *)(0x707c78b8)
#define   UI_TEXT_4_BIN                            (void *)(0x707c9638)
#define   UI_TEXT_5_BIN                            (void *)(0x707cb4f8)
#define   UI_TEXT_6_BIN                            (void *)(0x707cd2b8)
#define   UI_TEXT_7_BIN                            (void *)(0x707cef38)
#define   UI_TEXT_8_BIN                            (void *)(0x707d0b78)
#define   UI_TEXT_9_BIN                            (void *)(0x707d28f8)
#define   UI_TEXT_COLON_BIN                        (void *)(0x707d4578)
#define   UI_TEXT_PERCENT_BIN                      (void *)(0x707d4bf8)
#define   UI_ARROW_DOWN_BIN                        (void *)(0x707d80b8)
#define   UI_ARROW_UP_BIN                          (void *)(0x707d90f8)
#define   UI_BG_ICON_BIN                           (void *)(0x707da138)
#define   UI_CARD_ACTIVITY_BIN                     (void *)(0x707def78)
#define   UI_CARD_APPVIEW_BIN                      (void *)(0x70814f38)
#define   UI_CARD_BG_BIN                           (void *)(0x7081ff38)
#define   UI_CARD_CALENDAR_BIN                     (void *)(0x7083af38)
#define   UI_CARD_CLOCKCIRCLE_BIN                  (void *)(0x70855f38)
#define   UI_CARD_WEATHER_BIN                      (void *)(0x70872d38)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN            (void *)(0x708a8cf8)
#define   UI_CLOCK_MUSIC_ICON_BIN                  (void *)(0x708b2978)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN             (void *)(0x708bc5f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN               (void *)(0x708c6278)
#define   UI_IWATCH_ICON_BIN                       (void *)(0x708cfef8)
#define   UI_LINE_STILL_BIN                        (void *)(0x708d0e78)
#define   UI_MENU_CARD_BIN                         (void *)(0x708d1338)
#define   UI_MENU_CELLULAR_BIN                     (void *)(0x708da838)
#define   UI_MESSAGE_ICON_BIN                      (void *)(0x708e75f8)
#define   UI_PERSON_ICON_BIN                       (void *)(0x708ea8f8)
#define   W3W_BIN                                  (void *)(0x708eaf78)
#define   WATCH_HOUR_HAND_BIN                      (void *)(0x709b3fb8)
#define   WATCH_MASK_BIN                           (void *)(0x709b4e78)
#define   WATCH_MINUTE_HAND_BIN                    (void *)(0x709b50f8)
#define   WATCH_SECOND_HAND_BIN                    (void *)(0x709b6df8)
#define   UI_CLOCK_WEATHER_ICON_BIN                (void *)(0x709b7138)
#define   UI_WEATHER_CLEAR_BIN                     (void *)(0x709c0db8)
#define   UI_WEATHER_CLOUDY_BIN                    (void *)(0x709c1bf8)
#define   UI_WEATHER_RAIN_L_BIN                    (void *)(0x709c2d38)
#define   UI_WEATHER_RAIN_M_BIN                    (void *)(0x709c3c78)
#define   UI_WEATHER_RAIN_S_BIN                    (void *)(0x709c4bb8)
#define   UI_WEATHER_SUNNY_BIN                     (void *)(0x709c5af8)
#define   UI_CARD_WEATHER_DAY_BIN                  (void *)(0x709c6938)
#define   UI_CARD_WEATHER_NIGHT_BIN                (void *)(0x709e1938)
#define   WEATHER_DAY_SCR_BG_BIN                   (void *)(0x709fc938)
#define   WEATHER_LOCATION_BIN                     (void *)(0x70a61178)
#define   WEATHER_NIGHT_SCR_BG_BIN                 (void *)(0x70a61938)

#endif
