#if defined _WIN32
extern unsigned char resource_root[];

#define   DESC_FACE_BIN                            (void *)(resource_root + 0x000002f8)
#define   UI_CLOCK_ACTIVITY_ICON_BIN               (void *)(resource_root + 0x00015eb8)
#define   UI_CLOCK_CARD_WEATHER_BIN                (void *)(resource_root + 0x0001fb38)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN           (void *)(resource_root + 0x0004ecf8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN              (void *)(resource_root + 0x00058978)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN        (void *)(resource_root + 0x000625f8)
#define   CLEAR_BG_BIN                             (void *)(resource_root + 0x00062878)
#define   CAPSULE_MUTE_OFF_BIN                     (void *)(resource_root + 0x0007a738)
#define   CAPSULE_MUTE_ON_BIN                      (void *)(resource_root + 0x0007b0f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                 (void *)(resource_root + 0x0007bab8)
#define   CAPSULE_NOBOTHER_ON_BIN                  (void *)(resource_root + 0x0007caf8)
#define   CAPSULE_PHONE_OFF_BIN                    (void *)(resource_root + 0x0007db38)
#define   CAPSULE_PHONE_ON_BIN                     (void *)(resource_root + 0x0007eb78)
#define   CONTROL_CAPSULE_BIN                      (void *)(resource_root + 0x0007fbb8)
#define   CONTROL_LTE_OFF_BIN                      (void *)(resource_root + 0x00086138)
#define   CONTROL_LTE_ON_BIN                       (void *)(resource_root + 0x0009b978)
#define   CONTROL_MUTE_OFF_BIN                     (void *)(resource_root + 0x000b11b8)
#define   CONTROL_MUTE_ON_BIN                      (void *)(resource_root + 0x000c69f8)
#define   CONTROL_PHONE_OFF_BIN                    (void *)(resource_root + 0x000dc238)
#define   CONTROL_PHONE_ON_BIN                     (void *)(resource_root + 0x000f1a78)
#define   CONTROL_NOBOTHER_OFF_BIN                 (void *)(resource_root + 0x001072b8)
#define   CONTROL_NOBOTHER_ON_BIN                  (void *)(resource_root + 0x0011caf8)
#define   CONTROL_PAD_BIN                          (void *)(resource_root + 0x00132338)
#define   CONTROL_WIFI_OFF_BIN                     (void *)(resource_root + 0x00147b78)
#define   CONTROL_WIFI_ON_BIN                      (void *)(resource_root + 0x0015d3b8)
#define   MUTE_OFF_ICON_BIN                        (void *)(resource_root + 0x00172bf8)
#define   MUTE_ON_ICON_BIN                         (void *)(resource_root + 0x001735b8)
#define   MENU_BAR_BG_BIN                          (void *)(resource_root + 0x00173f78)
#define   MSG_TAB_BG_BIN                           (void *)(resource_root + 0x001a83b8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN             (void *)(resource_root + 0x001f3878)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN              (void *)(resource_root + 0x001f6f38)
#define   APP_MUSIC_BTN_LOOP_BIN                   (void *)(resource_root + 0x001fa5b8)
#define   APP_MUSIC_BTN_NEXT_BIN                   (void *)(resource_root + 0x001faef8)
#define   APP_MUSIC_BTN_PAUSE_BIN                  (void *)(resource_root + 0x001feb38)
#define   APP_MUSIC_BTN_PLAY_BIN                   (void *)(resource_root + 0x00204a78)
#define   APP_MUSIC_BTN_PREV_BIN                   (void *)(resource_root + 0x0020a9b8)
#define   APP_MUSIC_BTN_RND_BIN                    (void *)(resource_root + 0x0020e5f8)
#define   APP_MUSIC_CORNER_LEFT_BIN                (void *)(resource_root + 0x0020ef38)
#define   APP_MUSIC_CORNER_RIGHT_BIN               (void *)(resource_root + 0x0020f478)
#define   APP_MUSIC_COVER_1_BIN                    (void *)(resource_root + 0x0020f9b8)
#define   APP_MUSIC_COVER_2_BIN                    (void *)(resource_root + 0x0022db38)
#define   APP_MUSIC_COVER_3_BIN                    (void *)(resource_root + 0x0024bcb8)
#define   APP_MUSIC_ICN_CHART_BIN                  (void *)(resource_root + 0x00269e38)
#define   APP_MUSIC_ICN_CHAT_BIN                   (void *)(resource_root + 0x0026a778)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN               (void *)(resource_root + 0x0026b0b8)
#define   APP_MUSIC_ICN_HEART_BIN                  (void *)(resource_root + 0x0026b9f8)
#define   APP_MUSIC_ICN_SLIDER_BIN                 (void *)(resource_root + 0x0026c338)
#define   APP_MUSIC_LIST_BORDER_BIN                (void *)(resource_root + 0x0026d8f8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN                (void *)(resource_root + 0x0026ea38)
#define   APP_MUSIC_WAVE_TOP_BIN                   (void *)(resource_root + 0x00279cf8)
#define   OPTION_BAR_BG_BIN                        (void *)(resource_root + 0x00284fb8)
#define   OPTION_BAR_WHITE_BG_BIN                  (void *)(resource_root + 0x002a0578)
#define   OPTION_TAB_BG_BIN                        (void *)(resource_root + 0x002bbb38)
#define   PATH02_BIN                               (void *)(resource_root + 0x002e04f8)
#define   PATH03_BIN                               (void *)(resource_root + 0x002e0838)
#define   PATH04_BIN                               (void *)(resource_root + 0x002e0d38)
#define   PATH05_BIN                               (void *)(resource_root + 0x002e13b8)
#define   PATH06_BIN                               (void *)(resource_root + 0x002e1bb8)
#define   PATH07_BIN                               (void *)(resource_root + 0x002e2538)
#define   PATH08_BIN                               (void *)(resource_root + 0x002e3078)
#define   PATH09_BIN                               (void *)(resource_root + 0x002e3d38)
#define   PATH10_BIN                               (void *)(resource_root + 0x002e4b78)
#define   PATH11_BIN                               (void *)(resource_root + 0x002e5b38)
#define   PATH12_BIN                               (void *)(resource_root + 0x002e6cb8)
#define   PATH13_BIN                               (void *)(resource_root + 0x002e7fb8)
#define   PATH14_BIN                               (void *)(resource_root + 0x002e9438)
#define   PATH15_BIN                               (void *)(resource_root + 0x002eaa38)
#define   PATH16_BIN                               (void *)(resource_root + 0x002ec1f8)
#define   PATH17_BIN                               (void *)(resource_root + 0x002edb38)
#define   PATH18_BIN                               (void *)(resource_root + 0x002ef5f8)
#define   UI_TEXT_0_BIN                            (void *)(resource_root + 0x002f12f8)
#define   UI_TEXT_1_BIN                            (void *)(resource_root + 0x002f2f78)
#define   UI_TEXT_2_BIN                            (void *)(resource_root + 0x002f47b8)
#define   UI_TEXT_3_BIN                            (void *)(resource_root + 0x002f64b8)
#define   UI_TEXT_4_BIN                            (void *)(resource_root + 0x002f8238)
#define   UI_TEXT_5_BIN                            (void *)(resource_root + 0x002fa0f8)
#define   UI_TEXT_6_BIN                            (void *)(resource_root + 0x002fbeb8)
#define   UI_TEXT_7_BIN                            (void *)(resource_root + 0x002fdb38)
#define   UI_TEXT_8_BIN                            (void *)(resource_root + 0x002ff778)
#define   UI_TEXT_9_BIN                            (void *)(resource_root + 0x003014f8)
#define   UI_TEXT_COLON_BIN                        (void *)(resource_root + 0x00303178)
#define   UI_TEXT_PERCENT_BIN                      (void *)(resource_root + 0x003037f8)
#define   UI_ARROW_DOWN_BIN                        (void *)(resource_root + 0x00306cb8)
#define   UI_ARROW_UP_BIN                          (void *)(resource_root + 0x00307cf8)
#define   UI_BG_ICON_BIN                           (void *)(resource_root + 0x00308d38)
#define   UI_CARD_ACTIVITY_BIN                     (void *)(resource_root + 0x0030db78)
#define   UI_CARD_APPVIEW_BIN                      (void *)(resource_root + 0x00343b38)
#define   UI_CARD_BG_BIN                           (void *)(resource_root + 0x0034eb38)
#define   UI_CARD_CALENDAR_BIN                     (void *)(resource_root + 0x00369b38)
#define   UI_CARD_CLOCKCIRCLE_BIN                  (void *)(resource_root + 0x00384b38)
#define   UI_CARD_WEATHER_BIN                      (void *)(resource_root + 0x003a1938)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN            (void *)(resource_root + 0x003d78f8)
#define   UI_CLOCK_MUSIC_ICON_BIN                  (void *)(resource_root + 0x003e1578)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN             (void *)(resource_root + 0x003eb1f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN               (void *)(resource_root + 0x003f4e78)
#define   UI_IWATCH_ICON_BIN                       (void *)(resource_root + 0x003feaf8)
#define   UI_LINE_STILL_BIN                        (void *)(resource_root + 0x003ffa78)
#define   UI_MENU_CARD_BIN                         (void *)(resource_root + 0x003fff38)
#define   UI_MENU_CELLULAR_BIN                     (void *)(resource_root + 0x00409438)
#define   UI_MESSAGE_ICON_BIN                      (void *)(resource_root + 0x004161f8)
#define   UI_PERSON_ICON_BIN                       (void *)(resource_root + 0x004194f8)
#define   W3W_BIN                                  (void *)(resource_root + 0x00419b78)
#define   WATCH_HOUR_HAND_BIN                      (void *)(resource_root + 0x004e2bb8)
#define   WATCH_MASK_BIN                           (void *)(resource_root + 0x004e3a78)
#define   WATCH_MINUTE_HAND_BIN                    (void *)(resource_root + 0x004e3cf8)
#define   WATCH_SECOND_HAND_BIN                    (void *)(resource_root + 0x004e59f8)
#define   UI_CLOCK_WEATHER_ICON_BIN                (void *)(resource_root + 0x004e5d38)
#define   UI_WEATHER_CLEAR_BIN                     (void *)(resource_root + 0x004ef9b8)
#define   UI_WEATHER_CLOUDY_BIN                    (void *)(resource_root + 0x004f07f8)
#define   UI_WEATHER_RAIN_L_BIN                    (void *)(resource_root + 0x004f1938)
#define   UI_WEATHER_RAIN_M_BIN                    (void *)(resource_root + 0x004f2878)
#define   UI_WEATHER_RAIN_S_BIN                    (void *)(resource_root + 0x004f37b8)
#define   UI_WEATHER_SUNNY_BIN                     (void *)(resource_root + 0x004f46f8)
#define   UI_CARD_WEATHER_DAY_BIN                  (void *)(resource_root + 0x004f5538)
#define   UI_CARD_WEATHER_NIGHT_BIN                (void *)(resource_root + 0x00510538)
#define   WEATHER_DAY_SCR_BG_BIN                   (void *)(resource_root + 0x0052b538)
#define   WEATHER_LOCATION_BIN                     (void *)(resource_root + 0x0058fd78)
#define   WEATHER_NIGHT_SCR_BG_BIN                 (void *)(resource_root + 0x00590538)

#else
#define   DESC_FACE_BIN                            (void *)(0x704d12f8)
#define   UI_CLOCK_ACTIVITY_ICON_BIN               (void *)(0x704e6eb8)
#define   UI_CLOCK_CARD_WEATHER_BIN                (void *)(0x704f0b38)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN           (void *)(0x7051fcf8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN              (void *)(0x70529978)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN        (void *)(0x705335f8)
#define   CLEAR_BG_BIN                             (void *)(0x70533878)
#define   CAPSULE_MUTE_OFF_BIN                     (void *)(0x7054b738)
#define   CAPSULE_MUTE_ON_BIN                      (void *)(0x7054c0f8)
#define   CAPSULE_NOBOTHER_OFF_BIN                 (void *)(0x7054cab8)
#define   CAPSULE_NOBOTHER_ON_BIN                  (void *)(0x7054daf8)
#define   CAPSULE_PHONE_OFF_BIN                    (void *)(0x7054eb38)
#define   CAPSULE_PHONE_ON_BIN                     (void *)(0x7054fb78)
#define   CONTROL_CAPSULE_BIN                      (void *)(0x70550bb8)
#define   CONTROL_LTE_OFF_BIN                      (void *)(0x70557138)
#define   CONTROL_LTE_ON_BIN                       (void *)(0x7056c978)
#define   CONTROL_MUTE_OFF_BIN                     (void *)(0x705821b8)
#define   CONTROL_MUTE_ON_BIN                      (void *)(0x705979f8)
#define   CONTROL_PHONE_OFF_BIN                    (void *)(0x705ad238)
#define   CONTROL_PHONE_ON_BIN                     (void *)(0x705c2a78)
#define   CONTROL_NOBOTHER_OFF_BIN                 (void *)(0x705d82b8)
#define   CONTROL_NOBOTHER_ON_BIN                  (void *)(0x705edaf8)
#define   CONTROL_PAD_BIN                          (void *)(0x70603338)
#define   CONTROL_WIFI_OFF_BIN                     (void *)(0x70618b78)
#define   CONTROL_WIFI_ON_BIN                      (void *)(0x7062e3b8)
#define   MUTE_OFF_ICON_BIN                        (void *)(0x70643bf8)
#define   MUTE_ON_ICON_BIN                         (void *)(0x706445b8)
#define   MENU_BAR_BG_BIN                          (void *)(0x70644f78)
#define   MSG_TAB_BG_BIN                           (void *)(0x706793b8)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN             (void *)(0x706c4878)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN              (void *)(0x706c7f38)
#define   APP_MUSIC_BTN_LOOP_BIN                   (void *)(0x706cb5b8)
#define   APP_MUSIC_BTN_NEXT_BIN                   (void *)(0x706cbef8)
#define   APP_MUSIC_BTN_PAUSE_BIN                  (void *)(0x706cfb38)
#define   APP_MUSIC_BTN_PLAY_BIN                   (void *)(0x706d5a78)
#define   APP_MUSIC_BTN_PREV_BIN                   (void *)(0x706db9b8)
#define   APP_MUSIC_BTN_RND_BIN                    (void *)(0x706df5f8)
#define   APP_MUSIC_CORNER_LEFT_BIN                (void *)(0x706dff38)
#define   APP_MUSIC_CORNER_RIGHT_BIN               (void *)(0x706e0478)
#define   APP_MUSIC_COVER_1_BIN                    (void *)(0x706e09b8)
#define   APP_MUSIC_COVER_2_BIN                    (void *)(0x706feb38)
#define   APP_MUSIC_COVER_3_BIN                    (void *)(0x7071ccb8)
#define   APP_MUSIC_ICN_CHART_BIN                  (void *)(0x7073ae38)
#define   APP_MUSIC_ICN_CHAT_BIN                   (void *)(0x7073b778)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN               (void *)(0x7073c0b8)
#define   APP_MUSIC_ICN_HEART_BIN                  (void *)(0x7073c9f8)
#define   APP_MUSIC_ICN_SLIDER_BIN                 (void *)(0x7073d338)
#define   APP_MUSIC_LIST_BORDER_BIN                (void *)(0x7073e8f8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN                (void *)(0x7073fa38)
#define   APP_MUSIC_WAVE_TOP_BIN                   (void *)(0x7074acf8)
#define   OPTION_BAR_BG_BIN                        (void *)(0x70755fb8)
#define   OPTION_BAR_WHITE_BG_BIN                  (void *)(0x70771578)
#define   OPTION_TAB_BG_BIN                        (void *)(0x7078cb38)
#define   PATH02_BIN                               (void *)(0x707b14f8)
#define   PATH03_BIN                               (void *)(0x707b1838)
#define   PATH04_BIN                               (void *)(0x707b1d38)
#define   PATH05_BIN                               (void *)(0x707b23b8)
#define   PATH06_BIN                               (void *)(0x707b2bb8)
#define   PATH07_BIN                               (void *)(0x707b3538)
#define   PATH08_BIN                               (void *)(0x707b4078)
#define   PATH09_BIN                               (void *)(0x707b4d38)
#define   PATH10_BIN                               (void *)(0x707b5b78)
#define   PATH11_BIN                               (void *)(0x707b6b38)
#define   PATH12_BIN                               (void *)(0x707b7cb8)
#define   PATH13_BIN                               (void *)(0x707b8fb8)
#define   PATH14_BIN                               (void *)(0x707ba438)
#define   PATH15_BIN                               (void *)(0x707bba38)
#define   PATH16_BIN                               (void *)(0x707bd1f8)
#define   PATH17_BIN                               (void *)(0x707beb38)
#define   PATH18_BIN                               (void *)(0x707c05f8)
#define   UI_TEXT_0_BIN                            (void *)(0x707c22f8)
#define   UI_TEXT_1_BIN                            (void *)(0x707c3f78)
#define   UI_TEXT_2_BIN                            (void *)(0x707c57b8)
#define   UI_TEXT_3_BIN                            (void *)(0x707c74b8)
#define   UI_TEXT_4_BIN                            (void *)(0x707c9238)
#define   UI_TEXT_5_BIN                            (void *)(0x707cb0f8)
#define   UI_TEXT_6_BIN                            (void *)(0x707cceb8)
#define   UI_TEXT_7_BIN                            (void *)(0x707ceb38)
#define   UI_TEXT_8_BIN                            (void *)(0x707d0778)
#define   UI_TEXT_9_BIN                            (void *)(0x707d24f8)
#define   UI_TEXT_COLON_BIN                        (void *)(0x707d4178)
#define   UI_TEXT_PERCENT_BIN                      (void *)(0x707d47f8)
#define   UI_ARROW_DOWN_BIN                        (void *)(0x707d7cb8)
#define   UI_ARROW_UP_BIN                          (void *)(0x707d8cf8)
#define   UI_BG_ICON_BIN                           (void *)(0x707d9d38)
#define   UI_CARD_ACTIVITY_BIN                     (void *)(0x707deb78)
#define   UI_CARD_APPVIEW_BIN                      (void *)(0x70814b38)
#define   UI_CARD_BG_BIN                           (void *)(0x7081fb38)
#define   UI_CARD_CALENDAR_BIN                     (void *)(0x7083ab38)
#define   UI_CARD_CLOCKCIRCLE_BIN                  (void *)(0x70855b38)
#define   UI_CARD_WEATHER_BIN                      (void *)(0x70872938)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN            (void *)(0x708a88f8)
#define   UI_CLOCK_MUSIC_ICON_BIN                  (void *)(0x708b2578)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN             (void *)(0x708bc1f8)
#define   UI_CLOCK_CALENDAR_ICON_BIN               (void *)(0x708c5e78)
#define   UI_IWATCH_ICON_BIN                       (void *)(0x708cfaf8)
#define   UI_LINE_STILL_BIN                        (void *)(0x708d0a78)
#define   UI_MENU_CARD_BIN                         (void *)(0x708d0f38)
#define   UI_MENU_CELLULAR_BIN                     (void *)(0x708da438)
#define   UI_MESSAGE_ICON_BIN                      (void *)(0x708e71f8)
#define   UI_PERSON_ICON_BIN                       (void *)(0x708ea4f8)
#define   W3W_BIN                                  (void *)(0x708eab78)
#define   WATCH_HOUR_HAND_BIN                      (void *)(0x709b3bb8)
#define   WATCH_MASK_BIN                           (void *)(0x709b4a78)
#define   WATCH_MINUTE_HAND_BIN                    (void *)(0x709b4cf8)
#define   WATCH_SECOND_HAND_BIN                    (void *)(0x709b69f8)
#define   UI_CLOCK_WEATHER_ICON_BIN                (void *)(0x709b6d38)
#define   UI_WEATHER_CLEAR_BIN                     (void *)(0x709c09b8)
#define   UI_WEATHER_CLOUDY_BIN                    (void *)(0x709c17f8)
#define   UI_WEATHER_RAIN_L_BIN                    (void *)(0x709c2938)
#define   UI_WEATHER_RAIN_M_BIN                    (void *)(0x709c3878)
#define   UI_WEATHER_RAIN_S_BIN                    (void *)(0x709c47b8)
#define   UI_WEATHER_SUNNY_BIN                     (void *)(0x709c56f8)
#define   UI_CARD_WEATHER_DAY_BIN                  (void *)(0x709c6538)
#define   UI_CARD_WEATHER_NIGHT_BIN                (void *)(0x709e1538)
#define   WEATHER_DAY_SCR_BG_BIN                   (void *)(0x709fc538)
#define   WEATHER_LOCATION_BIN                     (void *)(0x70a60d78)
#define   WEATHER_NIGHT_SCR_BG_BIN                 (void *)(0x70a61538)

#endif
