// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT settinggroup02

lv_obj_t * ui_settinggroup02_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_settinggroup02;
    cui_settinggroup02 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_settinggroup02, 410);
    lv_obj_set_height(cui_settinggroup02, 426);
    lv_obj_set_x(cui_settinggroup02, 0);
    lv_obj_set_y(cui_settinggroup02, 36);
    lv_obj_set_align(cui_settinggroup02, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_settinggroup02, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_settinggroup02, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(cui_settinggroup02, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(cui_settinggroup02, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_settinggroup02, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_settinggroup02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_settinggroup02, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_settinggroup02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_settinggroup02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_settinggroup02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_settinggroup02, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_settinggroup02, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_settinggroup02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_settinggroup02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dial_group;
    cui_dial_group = lv_obj_create(cui_settinggroup02);
    lv_obj_set_width(cui_dial_group, 410);
    lv_obj_set_height(cui_dial_group, 120);
    lv_obj_set_x(cui_dial_group, -5);
    lv_obj_set_y(cui_dial_group, -51);
    lv_obj_set_align(cui_dial_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_dial_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_dial_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_dial_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dial_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_dial_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dial_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dial_icon_70;
    cui_dial_icon_70 = lv_image_create(cui_dial_group);
    lv_obj_set_width(cui_dial_icon_70, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(cui_dial_icon_70, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(cui_dial_icon_70, -140);
    lv_obj_set_y(cui_dial_icon_70, 0);
    lv_obj_set_align(cui_dial_icon_70, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_dial_icon_70, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_dial_icon_70, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_lin_01;
    cui_lin_01 = lv_obj_create(cui_dial_group);
    lv_obj_set_width(cui_lin_01, 382);
    lv_obj_set_height(cui_lin_01, 2);
    lv_obj_set_x(cui_lin_01, 0);
    lv_obj_set_y(cui_lin_01, 14);
    lv_obj_set_align(cui_lin_01, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(cui_lin_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_lin_01, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_lin_01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_lin_01, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_lin_01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dial_txt;
    cui_dial_txt = lv_label_create(cui_dial_group);
    lv_obj_set_width(cui_dial_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_dial_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_dial_txt, 30);
    lv_obj_set_y(cui_dial_txt, 0);
    lv_obj_set_align(cui_dial_txt, LV_ALIGN_CENTER);
    lv_label_set_text(cui_dial_txt, "Dial & Desktop");
    lv_obj_set_style_text_font(cui_dial_txt, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SETTINGGROUP02_NUM);
    children[UI_COMP_SETTINGGROUP02_SETTINGGROUP02] = cui_settinggroup02;
    children[UI_COMP_SETTINGGROUP02_DIAL_GROUP] = cui_dial_group;
    children[UI_COMP_SETTINGGROUP02_DIAL_GROUP_DIAL_ICON_70] = cui_dial_icon_70;
    children[UI_COMP_SETTINGGROUP02_DIAL_GROUP_LIN_01] = cui_lin_01;
    children[UI_COMP_SETTINGGROUP02_DIAL_GROUP_DIAL_TXT] = cui_dial_txt;
    lv_obj_add_event_cb(cui_settinggroup02, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_settinggroup02, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_settinggroup02_create_hook(cui_settinggroup02);
    return cui_settinggroup02;
}

