// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_INDOORGROUP_H
#define _UI_COMP_INDOORGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT indoorgroup
#define UI_COMP_INDOORGROUP_INDOORGROUP 0
#define UI_COMP_INDOORGROUP_LABEL101 1
#define UI_COMP_INDOORGROUP_IMAGE20 2
#define _UI_COMP_INDOORGROUP_NUM 3
lv_obj_t * ui_indoorgroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
