// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_MOTIONDATAGROUP_H
#define _UI_COMP_MOTIONDATAGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT motionDatagroup
#define UI_COMP_MOTIONDATAGROUP_MOTIONDATAGROUP 0
#define UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT 1
#define UI_COMP_MOTIONDATAGROUP_KM_TXT 2
#define UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE 3
#define UI_COMP_MOTIONDATAGROUP_MOTION_LINE 4
#define _UI_COMP_MOTIONDATAGROUP_NUM 5
lv_obj_t * ui_motionDatagroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
