// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT Outdoor Run group

lv_obj_t * ui_Outdoor_Run_group_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Outdoor_Run_group;
    cui_Outdoor_Run_group = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Outdoor_Run_group, 406);
    lv_obj_set_height(cui_Outdoor_Run_group, 112);
    lv_obj_set_x(cui_Outdoor_Run_group, 2);
    lv_obj_set_y(cui_Outdoor_Run_group, 82);
    lv_obj_remove_flag(cui_Outdoor_Run_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Outdoor_Run_icon;
    cui_Outdoor_Run_icon = lv_image_create(cui_Outdoor_Run_group);
    lv_obj_set_width(cui_Outdoor_Run_icon, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(cui_Outdoor_Run_icon, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(cui_Outdoor_Run_icon, 6);
    lv_obj_set_y(cui_Outdoor_Run_icon, 0);
    lv_obj_add_flag(cui_Outdoor_Run_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Outdoor_Run_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Outdoor_Run_txt;
    cui_Outdoor_Run_txt = lv_label_create(cui_Outdoor_Run_group);
    lv_obj_set_width(cui_Outdoor_Run_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Outdoor_Run_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Outdoor_Run_txt, 95);
    lv_obj_set_y(cui_Outdoor_Run_txt, 6);
    lv_label_set_text(cui_Outdoor_Run_txt, "Outdoor Run");
    lv_obj_set_style_text_font(cui_Outdoor_Run_txt, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Outdoor_Run_untargeted_txt;
    cui_Outdoor_Run_untargeted_txt = lv_label_create(cui_Outdoor_Run_group);
    lv_obj_set_width(cui_Outdoor_Run_untargeted_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Outdoor_Run_untargeted_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Outdoor_Run_untargeted_txt, 95);
    lv_obj_set_y(cui_Outdoor_Run_untargeted_txt, 48);
    lv_label_set_text(cui_Outdoor_Run_untargeted_txt, "Untargeted");
    lv_obj_set_style_text_color(cui_Outdoor_Run_untargeted_txt, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Outdoor_Run_untargeted_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Outdoor_Run_untargeted_txt, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Outdoor_Run_set_up_icon;
    cui_Outdoor_Run_set_up_icon = lv_image_create(cui_Outdoor_Run_group);
    lv_obj_set_width(cui_Outdoor_Run_set_up_icon, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(cui_Outdoor_Run_set_up_icon, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(cui_Outdoor_Run_set_up_icon, 170);
    lv_obj_set_y(cui_Outdoor_Run_set_up_icon, 0);
    lv_obj_set_align(cui_Outdoor_Run_set_up_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Outdoor_Run_set_up_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Outdoor_Run_set_up_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_OUTDOOR_RUN_GROUP_NUM);
    children[UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_GROUP] = cui_Outdoor_Run_group;
    children[UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_ICON] = cui_Outdoor_Run_icon;
    children[UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_TXT] = cui_Outdoor_Run_txt;
    children[UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_UNTARGETED_TXT] = cui_Outdoor_Run_untargeted_txt;
    children[UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_SET_UP_ICON] = cui_Outdoor_Run_set_up_icon;
    lv_obj_add_event_cb(cui_Outdoor_Run_group, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Outdoor_Run_group, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Outdoor_Run_group_create_hook(cui_Outdoor_Run_group);
    return cui_Outdoor_Run_group;
}

