// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_OUTDOOR_RUN_GROUP1_H
#define _UI_COMP_OUTDOOR_RUN_GROUP1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Outdoor Run group1
#define UI_COMP_OUTDOOR_RUN_GROUP1_OUTDOOR_RUN_GROUP1 0
#define UI_COMP_OUTDOOR_RUN_GROUP1_OUTDOOR_RUN_ICON1 1
#define UI_COMP_OUTDOOR_RUN_GROUP1_PANEL24 2
#define UI_COMP_OUTDOOR_RUN_GROUP1_OUTDOOR_RUN_TXT1 3
#define UI_COMP_OUTDOOR_RUN_GROUP1_OUTDOOR_RUN_UNTARGETED_TXT1 4
#define UI_COMP_OUTDOOR_RUN_GROUP1_IMAGE1 5
#define _UI_COMP_OUTDOOR_RUN_GROUP1_NUM 6
lv_obj_t * ui_Outdoor_Run_group1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
