// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_CONTAINER2_H
#define _UI_COMP_CONTAINER2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Container2
#define UI_COMP_CONTAINER2_CONTAINER2 0
#define UI_COMP_CONTAINER2_IMAGE18 1
#define _UI_COMP_CONTAINER2_NUM 2
lv_obj_t * ui_Container2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
