// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_DIALGROUP02_H
#define _UI_COMP_DIALGROUP02_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dialgroup02
#define UI_COMP_DIALGROUP02_DIALGROUP02 0
#define UI_COMP_DIALGROUP02_DIAL_ICON_2 1
#define UI_COMP_DIALGROUP02_LIN_2 2
#define UI_COMP_DIALGROUP02_DIAL_TXT_GROUP 3
#define UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2 4
#define _UI_COMP_DIALGROUP02_NUM 5
lv_obj_t * ui_dialgroup02_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
