// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT Container2

lv_obj_t * ui_Container2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Container2;
    cui_Container2 = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Container2);
    lv_obj_set_width(cui_Container2, 333);
    lv_obj_set_height(cui_Container2, 94);
    lv_obj_set_x(cui_Container2, 33);
    lv_obj_set_y(cui_Container2, 78);
    lv_obj_remove_flag(cui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image18;
    cui_Image18 = lv_image_create(cui_Container2);
    lv_obj_set_width(cui_Image18, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(cui_Image18, LV_SIZE_CONTENT);    /// 88
    lv_obj_add_flag(cui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINER2_NUM);
    children[UI_COMP_CONTAINER2_CONTAINER2] = cui_Container2;
    children[UI_COMP_CONTAINER2_IMAGE18] = cui_Image18;
    lv_obj_add_event_cb(cui_Container2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Container2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Container2_create_hook(cui_Container2);
    return cui_Container2;
}

