// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_INDOORGROUP3_H
#define _UI_COMP_INDOORGROUP3_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT indoorgroup3
#define UI_COMP_INDOORGROUP3_INDOORGROUP3 0
#define UI_COMP_INDOORGROUP3_LABEL99 1
#define UI_COMP_INDOORGROUP3_LABEL100 2
#define UI_COMP_INDOORGROUP3_LABEL103 3
#define _UI_COMP_INDOORGROUP3_NUM 4
lv_obj_t * ui_indoorgroup3_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
