// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT Panel32

lv_obj_t * ui_Panel32_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel32;
    cui_Panel32 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel32, 400);
    lv_obj_set_height(cui_Panel32, 100);
    lv_obj_set_x(cui_Panel32, 0);
    lv_obj_set_y(cui_Panel32, -95);
    lv_obj_set_align(cui_Panel32, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_Panel32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label99;
    cui_Label99 = lv_label_create(cui_Panel32);
    lv_obj_set_width(cui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label99, "3600");
    lv_obj_set_style_text_font(cui_Label99, &ui_font_HONORS_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL32_NUM);
    children[UI_COMP_PANEL32_PANEL32] = cui_Panel32;
    children[UI_COMP_PANEL32_LABEL99] = cui_Label99;
    lv_obj_add_event_cb(cui_Panel32, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel32, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel32_create_hook(cui_Panel32);
    return cui_Panel32;
}

