// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_PRIMARY_STATUS_BAR_H
#define _UI_COMP_PRIMARY_STATUS_BAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Primary status bar
#define UI_COMP_PRIMARY_STATUS_BAR_PRIMARY_STATUS_BAR 0
#define UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON 1
#define UI_COMP_PRIMARY_STATUS_BAR_CAPTION_TIME 2
#define _UI_COMP_PRIMARY_STATUS_BAR_NUM 3
lv_obj_t * ui_Primary_status_bar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
