// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT dialgroup1

lv_obj_t * ui_dialgroup1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dialgroup1;
    cui_dialgroup1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_dialgroup1, 410);
    lv_obj_set_height(cui_dialgroup1, 120);
    lv_obj_set_x(cui_dialgroup1, -5);
    lv_obj_set_y(cui_dialgroup1, -47);
    lv_obj_set_align(cui_dialgroup1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_dialgroup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_lin_3;
    cui_lin_3 = lv_obj_create(cui_dialgroup1);
    lv_obj_set_width(cui_lin_3, 382);
    lv_obj_set_height(cui_lin_3, 2);
    lv_obj_set_x(cui_lin_3, 0);
    lv_obj_set_y(cui_lin_3, 14);
    lv_obj_set_align(cui_lin_3, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(cui_lin_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_lin_3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_lin_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_lin_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_lin_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label107;
    cui_Label107 = lv_label_create(cui_dialgroup1);
    lv_obj_set_width(cui_Label107, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label107, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label107, 12);
    lv_obj_set_y(cui_Label107, 49);
    lv_label_set_text(cui_Label107, "5 Seconds");
    lv_obj_set_style_text_color(cui_Label107, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label107, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Label107, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label107, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dial_txt_group1;
    cui_dial_txt_group1 = lv_obj_create(cui_dialgroup1);
    lv_obj_set_width(cui_dial_txt_group1, 280);
    lv_obj_set_height(cui_dial_txt_group1, 50);
    lv_obj_set_x(cui_dial_txt_group1, -44);
    lv_obj_set_y(cui_dial_txt_group1, -13);
    lv_obj_set_align(cui_dial_txt_group1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_dial_txt_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_dial_txt_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dial_txt_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_dial_txt_group1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dial_txt_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_dial_txt1;
    cui_dial_txt1 = lv_label_create(cui_dial_txt_group1);
    lv_obj_set_width(cui_dial_txt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_dial_txt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_dial_txt1, -10);
    lv_obj_set_y(cui_dial_txt1, -20);
    lv_label_set_long_mode(cui_dial_txt1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_dial_txt1, "Brightness Duration");
    lv_obj_set_style_text_align(cui_dial_txt1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_dial_txt1, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DIALGROUP1_NUM);
    children[UI_COMP_DIALGROUP1_DIALGROUP1] = cui_dialgroup1;
    children[UI_COMP_DIALGROUP1_LIN_3] = cui_lin_3;
    children[UI_COMP_DIALGROUP1_LABEL107] = cui_Label107;
    children[UI_COMP_DIALGROUP1_DIAL_TXT_GROUP1] = cui_dial_txt_group1;
    children[UI_COMP_DIALGROUP1_DIAL_TXT_GROUP1_DIAL_TXT1] = cui_dial_txt1;
    lv_obj_add_event_cb(cui_dialgroup1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dialgroup1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dialgroup1_create_hook(cui_dialgroup1);
    return cui_dialgroup1;
}

