// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_OUTDOOR_RUN_GROUP_H
#define _UI_COMP_OUTDOOR_RUN_GROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Outdoor Run group
#define UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_GROUP 0
#define UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_ICON 1
#define UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_TXT 2
#define UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_UNTARGETED_TXT 3
#define UI_COMP_OUTDOOR_RUN_GROUP_OUTDOOR_RUN_SET_UP_ICON 4
#define _UI_COMP_OUTDOOR_RUN_GROUP_NUM 5
lv_obj_t * ui_Outdoor_Run_group_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
