// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT Feature group

lv_obj_t * ui_Feature_group_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Feature_group;
    cui_Feature_group = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Feature_group, 380);
    lv_obj_set_height(cui_Feature_group, 110);
    lv_obj_set_x(cui_Feature_group, 0);
    lv_obj_set_y(cui_Feature_group, -156);
    lv_obj_set_align(cui_Feature_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Feature_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Feature_group, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Feature_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Feature_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Movement_icon;
    cui_Movement_icon = lv_image_create(cui_Feature_group);
    lv_obj_set_width(cui_Movement_icon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Movement_icon, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(cui_Movement_icon, -130);
    lv_obj_set_y(cui_Movement_icon, 0);
    lv_obj_set_align(cui_Movement_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Movement_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Movement_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Exercise_txt;
    cui_Exercise_txt = lv_label_create(cui_Feature_group);
    lv_obj_set_width(cui_Exercise_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Exercise_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Exercise_txt, 120);
    lv_obj_set_y(cui_Exercise_txt, 20);
    lv_label_set_text(cui_Exercise_txt, "Exercise");
    lv_obj_set_style_text_font(cui_Exercise_txt, &ui_font_HONOR_M_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_FEATURE_GROUP_NUM);
    children[UI_COMP_FEATURE_GROUP_FEATURE_GROUP] = cui_Feature_group;
    children[UI_COMP_FEATURE_GROUP_MOVEMENT_ICON] = cui_Movement_icon;
    children[UI_COMP_FEATURE_GROUP_EXERCISE_TXT] = cui_Exercise_txt;
    lv_obj_add_event_cb(cui_Feature_group, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Feature_group, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Feature_group_create_hook(cui_Feature_group);
    return cui_Feature_group;
}

