// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_PANEL32_H
#define _UI_COMP_PANEL32_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel32
#define UI_COMP_PANEL32_PANEL32 0
#define UI_COMP_PANEL32_LABEL99 1
#define _UI_COMP_PANEL32_NUM 2
lv_obj_t * ui_Panel32_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
