// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT indoorgroup3

lv_obj_t * ui_indoorgroup3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_indoorgroup3;
    cui_indoorgroup3 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_indoorgroup3, 360);
    lv_obj_set_height(cui_indoorgroup3, 60);
    lv_obj_set_x(cui_indoorgroup3, 0);
    lv_obj_set_y(cui_indoorgroup3, 76);
    lv_obj_remove_flag(cui_indoorgroup3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_indoorgroup3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_indoorgroup3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_indoorgroup3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_indoorgroup3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label99;
    cui_Label99 = lv_label_create(cui_indoorgroup3);
    lv_obj_set_width(cui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label99, -12);
    lv_obj_set_y(cui_Label99, -13);
    lv_label_set_text(cui_Label99, "1.25");
    lv_obj_set_style_text_color(cui_Label99, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label99, &ui_font_HONOR_M_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label100;
    cui_Label100 = lv_label_create(cui_indoorgroup3);
    lv_obj_set_width(cui_Label100, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label100, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label100, 98);
    lv_obj_set_y(cui_Label100, -17);
    lv_label_set_text(cui_Label100, "Gap");
    lv_obj_set_style_text_font(cui_Label100, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label103;
    cui_Label103 = lv_label_create(cui_indoorgroup3);
    lv_obj_set_width(cui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label103, 98);
    lv_obj_set_y(cui_Label103, 11);
    lv_label_set_text(cui_Label103, "km");
    lv_obj_set_style_text_font(cui_Label103, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_INDOORGROUP3_NUM);
    children[UI_COMP_INDOORGROUP3_INDOORGROUP3] = cui_indoorgroup3;
    children[UI_COMP_INDOORGROUP3_LABEL99] = cui_Label99;
    children[UI_COMP_INDOORGROUP3_LABEL100] = cui_Label100;
    children[UI_COMP_INDOORGROUP3_LABEL103] = cui_Label103;
    lv_obj_add_event_cb(cui_indoorgroup3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_indoorgroup3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_indoorgroup3_create_hook(cui_indoorgroup3);
    return cui_indoorgroup3;
}

