// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT Panel28

lv_obj_t * ui_Panel28_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel28;
    cui_Panel28 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel28, 380);
    lv_obj_set_height(cui_Panel28, 80);
    lv_obj_set_x(cui_Panel28, -1);
    lv_obj_set_y(cui_Panel28, -149);
    lv_obj_set_align(cui_Panel28, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Panel28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label66;
    cui_Label66 = lv_label_create(cui_Panel28);
    lv_obj_set_width(cui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label66, 90);
    lv_obj_set_y(cui_Label66, 8);
    lv_label_set_text(cui_Label66, "Fill in the title");
    lv_obj_set_style_text_font(cui_Label66, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel27;
    cui_Panel27 = lv_obj_create(cui_Panel28);
    lv_obj_set_width(cui_Panel27, 60);
    lv_obj_set_height(cui_Panel27, 60);
    lv_obj_set_x(cui_Panel27, -135);
    lv_obj_set_y(cui_Panel27, 0);
    lv_obj_set_align(cui_Panel27, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel27, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL28_NUM);
    children[UI_COMP_PANEL28_PANEL28] = cui_Panel28;
    children[UI_COMP_PANEL28_LABEL66] = cui_Label66;
    children[UI_COMP_PANEL28_PANEL27] = cui_Panel27;
    lv_obj_add_event_cb(cui_Panel28, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel28, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel28_create_hook(cui_Panel28);
    return cui_Panel28;
}

