// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_SETTING_GROUP_H
#define _UI_COMP_SETTING_GROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Setting group
#define UI_COMP_SETTING_GROUP_SETTING_GROUP 0
#define UI_COMP_SETTING_GROUP_LINE 1
#define UI_COMP_SETTING_GROUP_GOAL_ICON 2
#define UI_COMP_SETTING_GROUP_GOAL_TXT 3
#define UI_COMP_SETTING_GROUP_GOAL_TXT_01 4
#define _UI_COMP_SETTING_GROUP_NUM 5
lv_obj_t * ui_Setting_group_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
