// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _UI_COMP_SETTINGGROUP02_H
#define _UI_COMP_SETTINGGROUP02_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT settinggroup02
#define UI_COMP_SETTINGGROUP02_SETTINGGROUP02 0
#define UI_COMP_SETTINGGROUP02_DIAL_GROUP 1
#define UI_COMP_SETTINGGROUP02_DIAL_GROUP_DIAL_ICON_70 2
#define UI_COMP_SETTINGGROUP02_DIAL_GROUP_LIN_01 3
#define UI_COMP_SETTINGGROUP02_DIAL_GROUP_DIAL_TXT 4
#define _UI_COMP_SETTINGGROUP02_NUM 5
lv_obj_t * ui_settinggroup02_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
