// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT motionDatagroup

lv_obj_t * ui_motionDatagroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_motionDatagroup;
    cui_motionDatagroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_motionDatagroup, 366);
    lv_obj_set_height(cui_motionDatagroup, 110);
    lv_obj_set_x(cui_motionDatagroup, 0);
    lv_obj_set_y(cui_motionDatagroup, 73);
    lv_obj_set_align(cui_motionDatagroup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_motionDatagroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_motionDatagroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_motionDatagroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_motionDatagroup, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_motionDatagroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Total_distance_txt;
    cui_Total_distance_txt = lv_label_create(cui_motionDatagroup);
    lv_obj_set_width(cui_Total_distance_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Total_distance_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Total_distance_txt, -12);
    lv_obj_set_y(cui_Total_distance_txt, -10);
    lv_label_set_text(cui_Total_distance_txt, "Total distance");
    lv_obj_set_style_text_font(cui_Total_distance_txt, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_km_txt;
    cui_km_txt = lv_label_create(cui_motionDatagroup);
    lv_obj_set_width(cui_km_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_km_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_km_txt, -12);
    lv_obj_set_y(cui_km_txt, 35);
    lv_label_set_text(cui_km_txt, "km");
    lv_obj_set_style_text_color(cui_km_txt, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_km_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_km_txt, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Total_distance_date;
    cui_Total_distance_date = lv_label_create(cui_motionDatagroup);
    lv_obj_set_width(cui_Total_distance_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Total_distance_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Total_distance_date, 10);
    lv_obj_set_y(cui_Total_distance_date, -10);
    lv_obj_set_align(cui_Total_distance_date, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(cui_Total_distance_date, "2.25");
    lv_obj_set_style_text_color(cui_Total_distance_date, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Total_distance_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Total_distance_date, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_motion_line;
    cui_motion_line = lv_obj_create(cui_motionDatagroup);
    lv_obj_set_width(cui_motion_line, 364);
    lv_obj_set_height(cui_motion_line, 2);
    lv_obj_set_x(cui_motion_line, 0);
    lv_obj_set_y(cui_motion_line, 50);
    lv_obj_set_align(cui_motion_line, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_motion_line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_motion_line, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_motion_line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_motion_line, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_motion_line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_MOTIONDATAGROUP_NUM);
    children[UI_COMP_MOTIONDATAGROUP_MOTIONDATAGROUP] = cui_motionDatagroup;
    children[UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT] = cui_Total_distance_txt;
    children[UI_COMP_MOTIONDATAGROUP_KM_TXT] = cui_km_txt;
    children[UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE] = cui_Total_distance_date;
    children[UI_COMP_MOTIONDATAGROUP_MOTION_LINE] = cui_motion_line;
    lv_obj_add_event_cb(cui_motionDatagroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_motionDatagroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_motionDatagroup_create_hook(cui_motionDatagroup);
    return cui_motionDatagroup;
}

