// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

void ui_comp_Container2_create_hook(lv_obj_t * comp)
{
}

void ui_comp_dialgroup02_create_hook(lv_obj_t * comp)
{
}

void ui_comp_dialgroup1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Feature_group_create_hook(lv_obj_t * comp)
{
}

void ui_comp_indoorgroup_create_hook(lv_obj_t * comp)
{
}

void ui_comp_indoorgroup3_create_hook(lv_obj_t * comp)
{
}

void ui_comp_motionDatagroup_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Outdoor_Run_group_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Outdoor_Run_group1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel28_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Panel32_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Primary_status_bar_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Setting_group_create_hook(lv_obj_t * comp)
{
}

void ui_comp_settinggroup02_create_hook(lv_obj_t * comp)
{
}
