// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

// COMPONENT indoorgroup

lv_obj_t * ui_indoorgroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_indoorgroup;
    cui_indoorgroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_indoorgroup, 360);
    lv_obj_set_height(cui_indoorgroup, 60);
    lv_obj_set_x(cui_indoorgroup, 0);
    lv_obj_set_y(cui_indoorgroup, 76);
    lv_obj_remove_flag(cui_indoorgroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_indoorgroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_indoorgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_indoorgroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_indoorgroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label101;
    cui_Label101 = lv_label_create(cui_indoorgroup);
    lv_obj_set_width(cui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label101, 0);
    lv_obj_set_y(cui_Label101, -13);
    lv_label_set_text(cui_Label101, "88 BPM");
    lv_obj_set_style_text_color(cui_Label101, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label101, &ui_font_HONOR_M_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image20;
    cui_Image20 = lv_image_create(cui_indoorgroup);
    lv_obj_set_width(cui_Image20, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(cui_Image20, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(cui_Image20, 39);
    lv_obj_set_y(cui_Image20, -3);
    lv_obj_set_align(cui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_INDOORGROUP_NUM);
    children[UI_COMP_INDOORGROUP_INDOORGROUP] = cui_indoorgroup;
    children[UI_COMP_INDOORGROUP_LABEL101] = cui_Label101;
    children[UI_COMP_INDOORGROUP_IMAGE20] = cui_Image20;
    lv_obj_add_event_cb(cui_indoorgroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_indoorgroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_indoorgroup_create_hook(cui_indoorgroup);
    return cui_indoorgroup;
}

