// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_17;
lv_obj_t * ui_clk17_bg_group;
lv_obj_t * ui_clk17_bg;
lv_obj_t * ui_Label76;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Label79;
lv_obj_t * ui_Label77;
lv_obj_t * ui_Label81;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Label83;
lv_obj_t * ui_Label85;
lv_obj_t * ui_Label86;
lv_obj_t * ui_Label84;
lv_obj_t * ui_Label88;
lv_obj_t * ui_Label89;
lv_obj_t * ui_Label87;
lv_obj_t * ui_Label91;
lv_obj_t * ui_Label92;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label90;
lv_obj_t * ui_Label94;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Bar2;

// event funtions
void ui_event_clk_17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk17colon_Animation(ui_Label89, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_01, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_01_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_16, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_16_screen_init);
    }
}

void ui_event_Bar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label94, target, "", "%");
    }
}

// build funtions

void ui_clk_17_screen_init(void)
{
    ui_clk_17 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_clk_17, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_17, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_clk17_bg_group = lv_obj_create(ui_clk_17);
    lv_obj_set_width(ui_clk17_bg_group, 410);
    lv_obj_set_height(ui_clk17_bg_group, 502);
    lv_obj_set_align(ui_clk17_bg_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk17_bg_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk17_bg_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk17_bg_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk17_bg_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk17_bg_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk17_bg = lv_image_create(ui_clk17_bg_group);
    lv_image_set_src(ui_clk17_bg, &clk17_bg);
    lv_obj_set_width(ui_clk17_bg, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_clk17_bg, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_clk17_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk17_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk17_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label76 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label76, -137);
    lv_obj_set_y(ui_Label76, 67);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label76, "CALORIE");
    lv_obj_set_style_text_color(ui_Label76, lv_color_hex(0x8B1801), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label76, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label76, &ui_font_BEBAS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label78 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label78, -1);
    lv_obj_set_y(ui_Label78, 67);
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "STEPS");
    lv_obj_set_style_text_color(ui_Label78, lv_color_hex(0x015800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label78, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label78, &ui_font_BEBAS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label79 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label79, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label79, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label79, 136);
    lv_obj_set_y(ui_Label79, 67);
    lv_obj_set_align(ui_Label79, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label79, "H.RATE");
    lv_obj_set_style_text_color(ui_Label79, lv_color_hex(0x004F6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label79, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label79, &ui_font_BEBAS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label77 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label77, -137);
    lv_obj_set_y(ui_Label77, 129);
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label77, "342");
    lv_obj_set_style_text_color(ui_Label77, lv_color_hex(0xE98F28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label77, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label77, &ui_font_HONORS_D_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label81 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label81, -1);
    lv_obj_set_y(ui_Label81, 129);
    lv_obj_set_align(ui_Label81, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label81, "3960");
    lv_obj_set_style_text_color(ui_Label81, lv_color_hex(0x20D277), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label81, &ui_font_HONORS_D_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label82 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label82, 139);
    lv_obj_set_y(ui_Label82, 129);
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label82, "126");
    lv_obj_set_style_text_color(ui_Label82, lv_color_hex(0x38DDD1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label82, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label82, &ui_font_HONORS_D_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label80 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, -2);
    lv_obj_set_y(ui_Label80, 176);
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label80, "5.65");
    lv_obj_set_style_text_color(ui_Label80, lv_color_hex(0x27402D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label80, &ui_font_HONORS_D_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label83 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label83, -137);
    lv_obj_set_y(ui_Label83, 174);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label83, "KCAL");
    lv_obj_set_style_text_color(ui_Label83, lv_color_hex(0x955F1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label83, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label83, &ui_font_HONORS_R_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label85 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label85, 139);
    lv_obj_set_y(ui_Label85, 174);
    lv_obj_set_align(ui_Label85, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label85, "BPM");
    lv_obj_set_style_text_color(ui_Label85, lv_color_hex(0x249684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label85, &ui_font_HONORS_R_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label86 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label86, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label86, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label86, 0);
    lv_obj_set_y(ui_Label86, 215);
    lv_obj_set_align(ui_Label86, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label86, "KM");
    lv_obj_set_style_text_color(ui_Label86, lv_color_hex(0x5D725F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label86, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label86, &ui_font_HONORS_R_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label84 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label84, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label84, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label84, -102);
    lv_obj_set_y(ui_Label84, -30);
    lv_obj_set_align(ui_Label84, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label84, "09");
    lv_obj_set_style_text_color(ui_Label84, lv_color_hex(0x01EB86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label84, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label84, &ui_font_HONORS_H_140, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label88 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label88, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label88, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label88, 100);
    lv_obj_set_y(ui_Label88, -30);
    lv_obj_set_align(ui_Label88, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label88, "09");
    lv_obj_set_style_text_color(ui_Label88, lv_color_hex(0xF9DB16), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label88, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label88, &ui_font_HONORS_H_140, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label89 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label89, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label89, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label89, 0);
    lv_obj_set_y(ui_Label89, -45);
    lv_obj_set_align(ui_Label89, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label89, ":");
    lv_obj_set_style_text_color(ui_Label89, lv_color_hex(0x01EB86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label89, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label89, &ui_font_HONORS_H_140, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label87 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label87, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label87, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label87, -127);
    lv_obj_set_y(ui_Label87, -146);
    lv_obj_set_align(ui_Label87, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label87, "01-25");
    lv_obj_set_style_text_font(ui_Label87, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label91 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label91, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label91, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label91, -8);
    lv_obj_set_y(ui_Label91, -146);
    lv_obj_set_align(ui_Label91, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label91, "MON");
    lv_obj_set_style_text_font(ui_Label91, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label92 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label92, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label92, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label92, 118);
    lv_obj_set_y(ui_Label92, -146);
    lv_obj_set_align(ui_Label92, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label92, "DEC.21");
    lv_obj_set_style_text_font(ui_Label92, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_image_create(ui_clk_17);
    lv_image_set_src(ui_Image13, &clk17_alarm);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Image13, 0);
    lv_obj_set_y(ui_Image13, -216);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_clk_17);
    lv_image_set_src(ui_Image14, &clk17_weather);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image14, 76);
    lv_obj_set_y(ui_Image14, -216);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label90 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label90, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label90, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label90, 120);
    lv_obj_set_y(ui_Label90, -210);
    lv_obj_set_align(ui_Label90, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label90, "25℃");
    lv_obj_set_style_text_font(ui_Label90, &ui_font_HONORS_R_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label94 = lv_label_create(ui_clk_17);
    lv_obj_set_width(ui_Label94, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label94, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label94, 91);
    lv_obj_set_y(ui_Label94, 31);
    lv_label_set_text(ui_Label94, "80%");
    lv_obj_set_style_text_font(ui_Label94, &ui_font_HONORS_R_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_clk_17);
    lv_image_set_src(ui_Image15, &clk17_bat_bg);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image15, -135);
    lv_obj_set_y(ui_Image15, -210);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar2 = lv_bar_create(ui_clk_17);
    lv_bar_set_value(ui_Bar2, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 26);
    lv_obj_set_height(ui_Bar2, 12);
    lv_obj_set_x(ui_Bar2, -136);
    lv_obj_set_y(ui_Bar2, -210);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xAEAEAE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar2,
                                                                                           lv_obj_get_style_pad_right(ui_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Bar2, ui_event_Bar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_17, ui_event_clk_17, LV_EVENT_ALL, NULL);

}

void ui_clk_17_screen_destroy(void)
{
    if(ui_clk_17) lv_obj_del(ui_clk_17);

    // NULL screen variables
    ui_clk_17 = NULL;
    ui_clk17_bg_group = NULL;
    ui_clk17_bg = NULL;
    ui_Label76 = NULL;
    ui_Label78 = NULL;
    ui_Label79 = NULL;
    ui_Label77 = NULL;
    ui_Label81 = NULL;
    ui_Label82 = NULL;
    ui_Label80 = NULL;
    ui_Label83 = NULL;
    ui_Label85 = NULL;
    ui_Label86 = NULL;
    ui_Label84 = NULL;
    ui_Label88 = NULL;
    ui_Label89 = NULL;
    ui_Label87 = NULL;
    ui_Label91 = NULL;
    ui_Label92 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Label90 = NULL;
    ui_Label94 = NULL;
    ui_Image15 = NULL;
    ui_Bar2 = NULL;

}
