// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_09;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Image10;
lv_obj_t * ui_clk09_hour;
lv_obj_t * ui_clk09_m;

// event funtions
void ui_event_clk_09(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk09hour_Animation(ui_clk09_hour, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk09m_Animation(ui_clk09_m, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_10, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_10_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_08, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_08_screen_init);
    }
}

// build funtions

void ui_clk_09_screen_init(void)
{
    ui_clk_09 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_09, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk_09, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk_09, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_09, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_clk_09);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 180);
    lv_obj_set_x(ui_Panel3, 25);
    lv_obj_set_y(ui_Panel3, 24);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 0);
    lv_obj_set_y(ui_Label30, 14);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "09");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_HONORS_200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_clk_09);
    lv_obj_set_width(ui_Panel10, 230);
    lv_obj_set_height(ui_Panel10, 18);
    lv_obj_set_x(ui_Panel10, -68);
    lv_obj_set_y(ui_Panel10, -36);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel10, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel10, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Panel10, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_clk_09);
    lv_obj_set_width(ui_Panel9, 240);
    lv_obj_set_height(ui_Panel9, 180);
    lv_obj_set_x(ui_Panel9, 25);
    lv_obj_set_y(ui_Panel9, 191);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 0);
    lv_obj_set_y(ui_Label32, 14);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "30");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xE7E7E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_HONORS_200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 40);
    lv_obj_set_y(ui_Label31, 377);
    lv_label_set_text(ui_Label31, "FRIDAY");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFA0023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label31, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_HONOR_M_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 41);
    lv_obj_set_y(ui_Label33, 425);
    lv_label_set_text(ui_Label33, "11.27 ");
    lv_obj_set_style_text_align(ui_Label33, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_HONOR_M_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -46);
    lv_obj_set_y(ui_Label34, 46);
    lv_obj_set_align(ui_Label34, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label34, "Steps");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label34, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_HONOR_M_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -45);
    lv_obj_set_y(ui_Label35, 77);
    lv_obj_set_align(ui_Label35, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label35, "8000");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, -44);
    lv_obj_set_y(ui_Label37, 125);
    lv_obj_set_align(ui_Label37, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label37, "Calorie");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label37, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_HONOR_M_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, -45);
    lv_obj_set_y(ui_Label38, 158);
    lv_obj_set_align(ui_Label38, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label38, "347");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -45);
    lv_obj_set_y(ui_Label39, 207);
    lv_obj_set_align(ui_Label39, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label39, "Calorie");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label39, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_HONOR_M_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -45);
    lv_obj_set_y(ui_Label40, 238);
    lv_obj_set_align(ui_Label40, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label40, "18:26");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -45);
    lv_obj_set_y(ui_Label41, 290);
    lv_obj_set_align(ui_Label41, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label41, "Temp");
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label41, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_HONOR_M_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_clk_09);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -45);
    lv_obj_set_y(ui_Label42, 325);
    lv_obj_set_align(ui_Label42, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label42, "18:26");
    lv_obj_set_style_text_font(ui_Label42, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_clk_09);
    lv_obj_set_width(ui_Panel8, 112);
    lv_obj_set_height(ui_Panel8, 112);
    lv_obj_set_x(ui_Panel8, 114);
    lv_obj_set_y(ui_Panel8, 174);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 56, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_clk_09);
    lv_image_set_src(ui_Image10, &clk09_time);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 108
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 108
    lv_obj_set_x(ui_Image10, 114);
    lv_obj_set_y(ui_Image10, 175);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk09_hour = lv_image_create(ui_clk_09);
    lv_image_set_src(ui_clk09_hour, &clk09_hour);
    lv_obj_set_width(ui_clk09_hour, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_height(ui_clk09_hour, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_clk09_hour, 114);
    lv_obj_set_y(ui_clk09_hour, 163);
    lv_obj_set_align(ui_clk09_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk09_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk09_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_clk09_hour, 2, 42);

    ui_clk09_m = lv_image_create(ui_clk_09);
    lv_image_set_src(ui_clk09_m, &clk09_min);
    lv_obj_set_width(ui_clk09_m, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_clk09_m, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_clk09_m, 114);
    lv_obj_set_y(ui_clk09_m, 158);
    lv_obj_set_align(ui_clk09_m, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk09_m, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk09_m, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_clk09_m, 6, 52);

    lv_obj_add_event_cb(ui_clk_09, ui_event_clk_09, LV_EVENT_ALL, NULL);

}

void ui_clk_09_screen_destroy(void)
{
    if(ui_clk_09) lv_obj_del(ui_clk_09);

    // NULL screen variables
    ui_clk_09 = NULL;
    ui_Panel3 = NULL;
    ui_Label30 = NULL;
    ui_Panel10 = NULL;
    ui_Panel9 = NULL;
    ui_Label32 = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_Label34 = NULL;
    ui_Label35 = NULL;
    ui_Label37 = NULL;
    ui_Label38 = NULL;
    ui_Label39 = NULL;
    ui_Label40 = NULL;
    ui_Label41 = NULL;
    ui_Label42 = NULL;
    ui_Panel8 = NULL;
    ui_Image10 = NULL;
    ui_clk09_hour = NULL;
    ui_clk09_m = NULL;

}
