// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_14_H
#define UI_CLK_14_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_14
extern void ui_clk_14_screen_init(void);
extern void ui_clk_14_screen_destroy(void);
extern void ui_event_clk_14(lv_event_t * e);
extern lv_obj_t * ui_clk_14;
extern lv_obj_t * ui_clk14_bg_group;
extern lv_obj_t * ui_clk14_kcal_group;
extern lv_obj_t * ui_clk14_bg;
extern lv_obj_t * ui_clk14_step_group;
extern lv_obj_t * ui_clk14_sports_prg;
extern lv_obj_t * ui_clk14_sports_icon;
extern lv_obj_t * ui_clk14_bat_group;
extern lv_obj_t * ui_clk14_bat_icon;
extern lv_obj_t * ui_clk14_bat_prg;
extern lv_obj_t * ui_clk14_week_date;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Arc11;
extern lv_obj_t * ui_clk14_Img_circle01;
extern lv_obj_t * ui_clk14_hour;
extern lv_obj_t * ui_clk14_minut;
extern lv_obj_t * ui_clk14_sec;
extern lv_obj_t * ui_clk14_Img_circle02;
extern void ui_event_Arc12(lv_event_t * e);
extern lv_obj_t * ui_Arc12;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

