// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_12_H
#define UI_CLK_12_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_12
extern void ui_clk_12_screen_init(void);
extern void ui_clk_12_screen_destroy(void);
extern void ui_event_clk_12(lv_event_t * e);
extern lv_obj_t * ui_clk_12;
extern lv_obj_t * ui_clk12_bg_group;
extern lv_obj_t * ui_clk12_bg;
extern lv_obj_t * ui_clk12_kcal_group;
extern lv_obj_t * ui_clk12_kcal_icon;
extern void ui_event_clk12_kcal_prg(lv_event_t * e);
extern lv_obj_t * ui_clk12_kcal_prg;
extern lv_obj_t * ui_clk12_kcal_date;
extern lv_obj_t * ui_clk12_hr_icon;
extern lv_obj_t * ui_clk12_hr_date;
extern lv_obj_t * ui_clk12_step_group;
extern void ui_event_clk12_step_prg(lv_event_t * e);
extern lv_obj_t * ui_clk12_step_prg;
extern lv_obj_t * ui_clk12_step_icon;
extern lv_obj_t * ui_clk12_step_date;
extern lv_obj_t * ui_clk12_wewk_date_group;
extern lv_obj_t * ui_clk12_week_txt;
extern lv_obj_t * ui_clk12_date;
extern lv_obj_t * ui_clk12_Img_hour;
extern lv_obj_t * ui_clk12_Img_minut;
extern lv_obj_t * ui_clk12_Img_circle;
extern lv_obj_t * ui_clk12_Img_sec;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

