// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CALORIMETRIC_H
#define UI_CALORIMETRIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_calorimetric
extern void ui_calorimetric_screen_init(void);
extern void ui_calorimetric_screen_destroy(void);
extern lv_obj_t * ui_calorimetric;
extern lv_obj_t * ui_Campaign_List_group4;
extern lv_obj_t * ui_Primarystatusbar4;
extern lv_obj_t * ui_bnt_group3;
extern lv_obj_t * ui_cancel_icon3;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label95;
extern void ui_event_Panel30(lv_event_t * e);
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Image17;
extern void ui_event_Panel31(lv_event_t * e);
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Image19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

