// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_14;
lv_obj_t * ui_clk14_kcal_group;
lv_obj_t * ui_clk14_bg;
lv_obj_t * ui_clk14_step_group;
lv_obj_t * ui_clk14_sports_prg;
lv_obj_t * ui_clk14_sports_icon;
lv_obj_t * ui_clk14_bat_group;
lv_obj_t * ui_clk14_bat_icon;
lv_obj_t * ui_clk14_bat_prg;
lv_obj_t * ui_clk14_week_date;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Arc11;
lv_obj_t * ui_clk14_Img_circle01;
lv_obj_t * ui_clk14_hour;
lv_obj_t * ui_clk14_minut;
lv_obj_t * ui_clk14_sec;
lv_obj_t * ui_clk14_Img_circle02;
lv_obj_t * ui_Arc12;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;

// event funtions
void ui_event_clk_14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk14hour_Animation(ui_clk14_hour, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk14minut_Animation(ui_clk14_minut, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk14sec_Animation(ui_clk14_sec, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_15, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_15_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_13, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_13_screen_init);
    }
}

void ui_event_Arc12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label47, target, "", "");
    }
}

// build funtions

void ui_clk_14_screen_init(void)
{
    ui_clk_14 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk_14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk_14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk14_kcal_group = lv_obj_create(ui_clk_14);
    lv_obj_set_width(ui_clk14_kcal_group, 200);
    lv_obj_set_height(ui_clk14_kcal_group, 200);
    lv_obj_set_x(ui_clk14_kcal_group, 11);
    lv_obj_set_y(ui_clk14_kcal_group, 271);
    lv_obj_remove_flag(ui_clk14_kcal_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk14_kcal_group, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk14_kcal_group, lv_color_hex(0xC5BEB8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk14_kcal_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk14_kcal_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk14_kcal_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk14_bg = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_bg, &clk14_bg);
    lv_obj_set_width(ui_clk14_bg, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_clk14_bg, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_x(ui_clk14_bg, 11);
    lv_obj_set_y(ui_clk14_bg, 29);
    lv_obj_add_flag(ui_clk14_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk14_step_group = lv_obj_create(ui_clk_14);
    lv_obj_set_width(ui_clk14_step_group, 170);
    lv_obj_set_height(ui_clk14_step_group, 170);
    lv_obj_set_x(ui_clk14_step_group, 230);
    lv_obj_set_y(ui_clk14_step_group, 257);
    lv_obj_remove_flag(ui_clk14_step_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk14_step_group, 85, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk14_step_group, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk14_step_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk14_step_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk14_step_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk14_sports_prg = lv_arc_create(ui_clk14_step_group);
    lv_obj_set_width(ui_clk14_sports_prg, 160);
    lv_obj_set_height(ui_clk14_sports_prg, 160);
    lv_obj_set_align(ui_clk14_sports_prg, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_clk14_sports_prg, 50);
    lv_arc_set_bg_angles(ui_clk14_sports_prg, 0, 360);
    lv_arc_set_rotation(ui_clk14_sports_prg, 270);
    lv_obj_set_style_arc_color(ui_clk14_sports_prg, lv_color_hex(0x423810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk14_sports_prg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk14_sports_prg, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_clk14_sports_prg, lv_color_hex(0xDAB12C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk14_sports_prg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk14_sports_prg, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clk14_sports_prg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk14_sports_prg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk14_sports_icon = lv_image_create(ui_clk14_step_group);
    lv_image_set_src(ui_clk14_sports_icon, &clk14_sports);
    lv_obj_set_width(ui_clk14_sports_icon, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_clk14_sports_icon, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_clk14_sports_icon, 1);
    lv_obj_set_y(ui_clk14_sports_icon, -1);
    lv_obj_set_align(ui_clk14_sports_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk14_sports_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_sports_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk14_bat_group = lv_obj_create(ui_clk_14);
    lv_obj_set_width(ui_clk14_bat_group, 80);
    lv_obj_set_height(ui_clk14_bat_group, 80);
    lv_obj_set_x(ui_clk14_bat_group, 187);
    lv_obj_set_y(ui_clk14_bat_group, 387);
    lv_obj_remove_flag(ui_clk14_bat_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk14_bat_group, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk14_bat_group, lv_color_hex(0x232323), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk14_bat_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk14_bat_group, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk14_bat_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk14_bat_icon = lv_image_create(ui_clk14_bat_group);
    lv_image_set_src(ui_clk14_bat_icon, &clk14_bat);
    lv_obj_set_width(ui_clk14_bat_icon, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_clk14_bat_icon, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_align(ui_clk14_bat_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk14_bat_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_bat_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk14_bat_prg = lv_arc_create(ui_clk14_bat_group);
    lv_obj_set_width(ui_clk14_bat_prg, 74);
    lv_obj_set_height(ui_clk14_bat_prg, 74);
    lv_obj_set_align(ui_clk14_bat_prg, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_clk14_bat_prg, 70);
    lv_arc_set_bg_angles(ui_clk14_bat_prg, 0, 360);
    lv_arc_set_rotation(ui_clk14_bat_prg, 270);
    lv_obj_set_style_arc_color(ui_clk14_bat_prg, lv_color_hex(0x4D632D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk14_bat_prg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk14_bat_prg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_clk14_bat_prg, lv_color_hex(0x9DD647), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk14_bat_prg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk14_bat_prg, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clk14_bat_prg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk14_bat_prg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk14_week_date = lv_label_create(ui_clk_14);
    lv_obj_set_width(ui_clk14_week_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk14_week_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk14_week_date, 116);
    lv_obj_set_y(ui_clk14_week_date, 205);
    lv_obj_set_align(ui_clk14_week_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk14_week_date, "FRI 26");
    lv_obj_set_style_text_color(ui_clk14_week_date, lv_color_hex(0x9CD641), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk14_week_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk14_week_date, &ui_font_Ping_Fang_B_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_Image24, &clk14_kcar);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 41
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 47
    lv_obj_set_x(ui_Image24, -95);
    lv_obj_set_y(ui_Image24, 133);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc11 = lv_arc_create(ui_clk_14);
    lv_obj_set_width(ui_Arc11, 172);
    lv_obj_set_height(ui_Arc11, 172);
    lv_obj_set_x(ui_Arc11, -94);
    lv_obj_set_y(ui_Arc11, 121);
    lv_obj_set_align(ui_Arc11, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc11, 50);
    lv_arc_set_bg_angles(ui_Arc11, 0, 220);
    lv_obj_set_style_arc_color(ui_Arc11, lv_color_hex(0x8B8681), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc11, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc11, lv_color_hex(0x010107), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc11, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc11, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk14_Img_circle01 = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_Img_circle01, &clk14_circle_01);
    lv_obj_set_width(ui_clk14_Img_circle01, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_clk14_Img_circle01, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_clk14_Img_circle01, 151);
    lv_obj_set_y(ui_clk14_Img_circle01, 169);
    lv_obj_add_flag(ui_clk14_Img_circle01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_Img_circle01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk14_hour = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_hour, &clk14_hour);
    lv_obj_set_width(ui_clk14_hour, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_clk14_hour, LV_SIZE_CONTENT);    /// 82
    lv_obj_set_x(ui_clk14_hour, 158);
    lv_obj_set_y(ui_clk14_hour, 101);
    lv_obj_add_flag(ui_clk14_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_clk14_hour, 7, 80);

    ui_clk14_minut = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_minut, &clk14_min);
    lv_obj_set_width(ui_clk14_minut, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_clk14_minut, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_clk14_minut, 160);
    lv_obj_set_y(ui_clk14_minut, 57);
    lv_obj_add_flag(ui_clk14_minut, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_minut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_clk14_minut, 5, 126);

    ui_clk14_sec = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_sec, &clk14_sec);
    lv_obj_set_width(ui_clk14_sec, LV_SIZE_CONTENT);   /// 6
    lv_obj_set_height(ui_clk14_sec, LV_SIZE_CONTENT);    /// 130
    lv_obj_set_x(ui_clk14_sec, 162);
    lv_obj_set_y(ui_clk14_sec, 53);
    lv_obj_add_flag(ui_clk14_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_clk14_sec, 3, 128);

    ui_clk14_Img_circle02 = lv_image_create(ui_clk_14);
    lv_image_set_src(ui_clk14_Img_circle02, &clk14_circle_02);
    lv_obj_set_width(ui_clk14_Img_circle02, LV_SIZE_CONTENT);   /// 12
    lv_obj_set_height(ui_clk14_Img_circle02, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_clk14_Img_circle02, 159);
    lv_obj_set_y(ui_clk14_Img_circle02, 176);
    lv_obj_add_flag(ui_clk14_Img_circle02, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk14_Img_circle02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc12 = lv_arc_create(ui_clk_14);
    lv_obj_set_width(ui_Arc12, 430);
    lv_obj_set_height(ui_Arc12, 430);
    lv_obj_set_x(ui_Arc12, -28);
    lv_obj_set_y(ui_Arc12, -75);
    lv_obj_set_align(ui_Arc12, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc12, 0, 10000);
    lv_arc_set_value(ui_Arc12, 4568);
    lv_arc_set_bg_angles(ui_Arc12, 30, 80);
    lv_arc_set_rotation(ui_Arc12, 290);
    lv_obj_set_style_arc_color(ui_Arc12, lv_color_hex(0x433810), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc12, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc12, lv_color_hex(0xDAB12C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc12, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc12, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc12, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc12, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_clk_14);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 150);
    lv_obj_set_y(ui_Label46, -188);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "STEPS");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0xFFE214), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label46, &ui_font_Ping_Fang_B_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label46, 600, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label47 = lv_label_create(ui_clk_14);
    lv_obj_set_width(ui_Label47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label47, 369);
    lv_obj_set_y(ui_Label47, 157);
    lv_label_set_text(ui_Label47, "4568");
    lv_obj_set_style_text_align(ui_Label47, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label47, &ui_font_Ping_Fang_B_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label47, 920, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc12, ui_event_Arc12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_14, ui_event_clk_14, LV_EVENT_ALL, NULL);

}

void ui_clk_14_screen_destroy(void)
{
    if(ui_clk_14) lv_obj_del(ui_clk_14);

    // NULL screen variables
    ui_clk_14 = NULL;
    ui_clk14_kcal_group = NULL;
    ui_clk14_bg = NULL;
    ui_clk14_step_group = NULL;
    ui_clk14_sports_prg = NULL;
    ui_clk14_sports_icon = NULL;
    ui_clk14_bat_group = NULL;
    ui_clk14_bat_icon = NULL;
    ui_clk14_bat_prg = NULL;
    ui_clk14_week_date = NULL;
    ui_Image24 = NULL;
    ui_Arc11 = NULL;
    ui_clk14_Img_circle01 = NULL;
    ui_clk14_hour = NULL;
    ui_clk14_minut = NULL;
    ui_clk14_sec = NULL;
    ui_clk14_Img_circle02 = NULL;
    ui_Arc12 = NULL;
    ui_Label46 = NULL;
    ui_Label47 = NULL;

}
