// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_10_H
#define UI_CLK_10_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_10
extern void ui_clk_10_screen_init(void);
extern void ui_clk_10_screen_destroy(void);
extern void ui_event_clk_10(lv_event_t * e);
extern lv_obj_t * ui_clk_10;
extern lv_obj_t * ui_clk10_bg_group1;
extern lv_obj_t * ui_clk10_time_group;
extern lv_obj_t * ui_clk10_time_colon_;
extern lv_obj_t * ui_clk10_time_date;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_clk10_hr_group;
extern lv_obj_t * ui_clk10_hr_date;
extern lv_obj_t * ui_clk10_hr_icon;
extern lv_obj_t * ui_clk10_week_group;
extern lv_obj_t * ui_clk10_week_txt;
extern lv_obj_t * ui_clk10_date;
extern lv_obj_t * ui_clk10_kcal_group;
extern lv_obj_t * ui_clk10_kcal_date;
extern lv_obj_t * ui_clk10_kcal_icon;
extern lv_obj_t * ui_clk10__mile_group;
extern lv_obj_t * ui_clk10__mile_date;
extern lv_obj_t * ui_clk10__mile_icon;
extern lv_obj_t * ui_clk10_steps_date;
extern lv_obj_t * ui_clk10_steps_txt;
extern void ui_event_Arc8(lv_event_t * e);
extern lv_obj_t * ui_Arc8;
extern lv_obj_t * ui_clk10_steps_icon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

