// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_09_H
#define UI_CLK_09_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_09
extern void ui_clk_09_screen_init(void);
extern void ui_clk_09_screen_destroy(void);
extern void ui_event_clk_09(lv_event_t * e);
extern lv_obj_t * ui_clk_09;
extern lv_obj_t * ui_clk09_bg_group2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_clk09_hour;
extern lv_obj_t * ui_clk09_m;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

