// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_16;
lv_obj_t * ui_clk16_bg_group;
lv_obj_t * ui_clk16_hr_group;
lv_obj_t * ui_clk16_hr_icon;
lv_obj_t * ui_Label66;
lv_obj_t * ui_clk16_step_group;
lv_obj_t * ui_clk16_spots_icon;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Arc9;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label73;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label75;
lv_obj_t * ui_clk16_time_hour;
lv_obj_t * ui_clk16_data_txt;
lv_obj_t * ui_clk16_time_min;
lv_obj_t * ui_clk16_data_txt2;

// event funtions
void ui_event_clk_16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_17, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_17_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_15, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_15_screen_init);
    }
}

void ui_event_Arc9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label72, target, "", "%");
    }
}

// build funtions

void ui_clk_16_screen_init(void)
{
    ui_clk_16 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk_16, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_bg_group = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_clk16_bg_group, 410);
    lv_obj_set_height(ui_clk16_bg_group, 502);
    lv_obj_set_align(ui_clk16_bg_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk16_bg_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk16_bg_group, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk16_bg_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk16_bg_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk16_bg_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk16_bg_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_hr_group = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_clk16_hr_group, 92);
    lv_obj_set_height(ui_clk16_hr_group, 92);
    lv_obj_set_x(ui_clk16_hr_group, 11);
    lv_obj_set_y(ui_clk16_hr_group, 90);
    lv_obj_remove_flag(ui_clk16_hr_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk16_hr_group, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk16_hr_group, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk16_hr_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk16_hr_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk16_hr_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_hr_icon = lv_image_create(ui_clk16_hr_group);
    lv_image_set_src(ui_clk16_hr_icon, &clk16_heart);
    lv_obj_set_width(ui_clk16_hr_icon, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_clk16_hr_icon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_clk16_hr_icon, 0);
    lv_obj_set_y(ui_clk16_hr_icon, -24);
    lv_obj_set_align(ui_clk16_hr_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk16_hr_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk16_hr_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label66 = lv_label_create(ui_clk16_hr_group);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label66, 0);
    lv_obj_set_y(ui_Label66, 10);
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label66, "84");
    lv_obj_set_style_text_font(ui_Label66, &ui_font_HONORS_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_step_group = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_clk16_step_group, 92);
    lv_obj_set_height(ui_clk16_step_group, 92);
    lv_obj_set_x(ui_clk16_step_group, 11);
    lv_obj_set_y(ui_clk16_step_group, 205);
    lv_obj_remove_flag(ui_clk16_step_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk16_step_group, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk16_step_group, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk16_step_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk16_step_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk16_step_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_spots_icon = lv_image_create(ui_clk16_step_group);
    lv_image_set_src(ui_clk16_spots_icon, &clk16_sports);
    lv_obj_set_width(ui_clk16_spots_icon, LV_SIZE_CONTENT);   /// 57
    lv_obj_set_height(ui_clk16_spots_icon, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_align(ui_clk16_spots_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk16_spots_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk16_spots_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel22 = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_Panel22, 92);
    lv_obj_set_height(ui_Panel22, 92);
    lv_obj_set_x(ui_Panel22, 11);
    lv_obj_set_y(ui_Panel22, 320);
    lv_obj_remove_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel22, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc9 = lv_arc_create(ui_Panel22);
    lv_obj_set_width(ui_Arc9, 92);
    lv_obj_set_height(ui_Arc9, 92);
    lv_obj_set_align(ui_Arc9, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc9, 80);
    lv_arc_set_bg_angles(ui_Arc9, 198, 158);
    lv_obj_set_style_arc_color(ui_Arc9, lv_color_hex(0x303D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc9, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc9, lv_color_hex(0xA0D7F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc9, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image11 = lv_image_create(ui_Panel22);
    lv_image_set_src(ui_Image11, &clk16_bat);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Image11, -39);
    lv_obj_set_y(ui_Image11, 2);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label72 = lv_label_create(ui_clk_16);
    lv_obj_set_width(ui_Label72, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label72, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label72, -149);
    lv_obj_set_y(ui_Label72, 117);
    lv_obj_set_align(ui_Label72, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label72, "80%");
    lv_obj_set_style_text_letter_space(ui_Label72, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label72, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label72, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_Panel14, 192);
    lv_obj_set_height(ui_Panel14, 40);
    lv_obj_set_x(ui_Panel14, 109);
    lv_obj_set_y(ui_Panel14, 440);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label73 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label73, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label73, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label73, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label73, "Fri, Jan 20");
    lv_obj_set_style_text_letter_space(ui_Label73, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label73, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label73, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_Panel20, 120);
    lv_obj_set_height(ui_Panel20, 60);
    lv_obj_set_x(ui_Panel20, -108);
    lv_obj_set_y(ui_Panel20, -201);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label74, -5);
    lv_obj_set_y(ui_Label74, 16);
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label74, "Weather");
    lv_obj_set_style_text_color(ui_Label74, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label74, &ui_font_HONORS_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_image_create(ui_Panel20);
    lv_image_set_src(ui_Image12, &clk16_weather);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 29
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image12, -39);
    lv_obj_set_y(ui_Image12, -13);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label75 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label75, 7);
    lv_obj_set_y(ui_Label75, -11);
    lv_obj_set_align(ui_Label75, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label75, "25℃");
    lv_obj_set_style_text_font(ui_Label75, &ui_font_HONORS_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_time_hour = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_clk16_time_hour, 268);
    lv_obj_set_height(ui_clk16_time_hour, 190);
    lv_obj_set_x(ui_clk16_time_hour, 59);
    lv_obj_set_y(ui_clk16_time_hour, -121);
    lv_obj_set_align(ui_clk16_time_hour, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk16_time_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk16_time_hour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk16_time_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk16_time_hour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk16_time_hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_data_txt = lv_label_create(ui_clk16_time_hour);
    lv_obj_set_width(ui_clk16_data_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk16_data_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk16_data_txt, -1);
    lv_obj_set_y(ui_clk16_data_txt, 16);
    lv_obj_set_align(ui_clk16_data_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk16_data_txt, "09");
    lv_obj_set_style_text_color(ui_clk16_data_txt, lv_color_hex(0xA0D7F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk16_data_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk16_data_txt, &ui_font_HONORS_230, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_time_min = lv_obj_create(ui_clk_16);
    lv_obj_set_width(ui_clk16_time_min, 268);
    lv_obj_set_height(ui_clk16_time_min, 190);
    lv_obj_set_x(ui_clk16_time_min, 59);
    lv_obj_set_y(ui_clk16_time_min, 75);
    lv_obj_set_align(ui_clk16_time_min, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk16_time_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk16_time_min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk16_time_min, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk16_time_min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk16_time_min, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk16_data_txt2 = lv_label_create(ui_clk16_time_min);
    lv_obj_set_width(ui_clk16_data_txt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk16_data_txt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk16_data_txt2, -1);
    lv_obj_set_y(ui_clk16_data_txt2, 16);
    lv_obj_set_align(ui_clk16_data_txt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk16_data_txt2, "08");
    lv_obj_set_style_text_color(ui_clk16_data_txt2, lv_color_hex(0xA0D7F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk16_data_txt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk16_data_txt2, &ui_font_HONORS_230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_clk16_data_txt2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_clk16_data_txt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc9, ui_event_Arc9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_16, ui_event_clk_16, LV_EVENT_ALL, NULL);

}

void ui_clk_16_screen_destroy(void)
{
    if(ui_clk_16) lv_obj_del(ui_clk_16);

    // NULL screen variables
    ui_clk_16 = NULL;
    ui_clk16_bg_group = NULL;
    ui_clk16_hr_group = NULL;
    ui_clk16_hr_icon = NULL;
    ui_Label66 = NULL;
    ui_clk16_step_group = NULL;
    ui_clk16_spots_icon = NULL;
    ui_Panel22 = NULL;
    ui_Arc9 = NULL;
    ui_Image11 = NULL;
    ui_Label72 = NULL;
    ui_Panel14 = NULL;
    ui_Label73 = NULL;
    ui_Panel20 = NULL;
    ui_Label74 = NULL;
    ui_Image12 = NULL;
    ui_Label75 = NULL;
    ui_clk16_time_hour = NULL;
    ui_clk16_data_txt = NULL;
    ui_clk16_time_min = NULL;
    ui_clk16_data_txt2 = NULL;

}
