// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_08;
lv_obj_t * ui_clk07_bg1;
lv_obj_t * ui_heart_rate;
lv_obj_t * ui_steps;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Image9;
lv_obj_t * ui_clk08_spo2;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_clk08_dist;
lv_obj_t * ui_Arc5;
lv_obj_t * ui_clk08_kcal;
lv_obj_t * ui_Arc6;
lv_obj_t * ui_clk08_power;
lv_obj_t * ui_Arc7;
lv_obj_t * ui_clk08_power_txt;
lv_obj_t * ui_clk08_sp02_txt;
lv_obj_t * ui_clk08_kcal_txt;
lv_obj_t * ui_clk08_dist_txt;
lv_obj_t * ui_clk08_hr_txt;
lv_obj_t * ui_clk08_time;
lv_obj_t * ui_clk08_steps_txt;
lv_obj_t * ui_Label29;

// event funtions
void ui_event_clk_08(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_09, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_09_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_07, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_07_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk08dots_Animation(ui_Label29, 0);
    }
}

void ui_event_Arc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_clk08_steps_txt, target, "", "");
    }
}

// build funtions

void ui_clk_08_screen_init(void)
{
    ui_clk_08 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_08, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk07_bg1 = lv_image_create(ui_clk_08);
    lv_image_set_src(ui_clk07_bg1, &clk08_bg);
    lv_obj_set_width(ui_clk07_bg1, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_clk07_bg1, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_clk07_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk07_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk07_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heart_rate = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_heart_rate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heart_rate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heart_rate, 0);
    lv_obj_set_y(ui_heart_rate, -65);
    lv_obj_set_align(ui_heart_rate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heart_rate, "HEART RATE");
    lv_obj_set_style_text_color(ui_heart_rate, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_heart_rate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_heart_rate, &ui_font_HONO_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steps = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_steps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_steps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_steps, 0);
    lv_obj_set_y(ui_steps, 55);
    lv_obj_set_align(ui_steps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_steps, "STEPS");
    lv_obj_set_style_text_color(ui_steps, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_steps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_steps, &ui_font_HONO_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_clk_08);
    lv_obj_set_width(ui_Arc2, 270);
    lv_obj_set_height(ui_Arc2, 270);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc2, 0, 10000);
    lv_arc_set_value(ui_Arc2, 5960);
    lv_arc_set_bg_angles(ui_Arc2, 25, 155);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x313131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xA5A5A5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_clk_08);
    lv_image_set_src(ui_Image9, &clk08_hr_prg);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 254
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 99
    lv_obj_set_x(ui_Image9, 80);
    lv_obj_set_y(ui_Image9, 116);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk08_spo2 = lv_obj_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_spo2, 167);
    lv_obj_set_height(ui_clk08_spo2, 116);
    lv_obj_set_x(ui_clk08_spo2, -106);
    lv_obj_set_y(ui_clk08_spo2, -176);
    lv_obj_set_align(ui_clk08_spo2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk08_spo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk08_spo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk08_spo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk08_spo2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk08_spo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_clk08_spo2);
    lv_obj_set_width(ui_Arc4, 454);
    lv_obj_set_height(ui_Arc4, 454);
    lv_obj_set_x(ui_Arc4, 105);
    lv_obj_set_y(ui_Arc4, 177);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 50);
    lv_arc_set_bg_angles(ui_Arc4, 318, 0);
    lv_arc_set_rotation(ui_Arc4, 260);
    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xF5D8C2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk08_dist = lv_obj_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_dist, 170);
    lv_obj_set_height(ui_clk08_dist, 116);
    lv_obj_set_x(ui_clk08_dist, 100);
    lv_obj_set_y(ui_clk08_dist, 177);
    lv_obj_set_align(ui_clk08_dist, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk08_dist, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk08_dist, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk08_dist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk08_dist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk08_dist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc5 = lv_arc_create(ui_clk08_dist);
    lv_obj_set_width(ui_Arc5, 454);
    lv_obj_set_height(ui_Arc5, 454);
    lv_obj_set_x(ui_Arc5, -100);
    lv_obj_set_y(ui_Arc5, -177);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc5, 50);
    lv_arc_set_bg_angles(ui_Arc5, 318, 0);
    lv_arc_set_rotation(ui_Arc5, 80);
    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xF5D8C2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk08_kcal = lv_obj_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_kcal, 156);
    lv_obj_set_height(ui_clk08_kcal, 101);
    lv_obj_set_x(ui_clk08_kcal, -102);
    lv_obj_set_y(ui_clk08_kcal, 178);
    lv_obj_set_align(ui_clk08_kcal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk08_kcal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk08_kcal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk08_kcal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk08_kcal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk08_kcal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc6 = lv_arc_create(ui_clk08_kcal);
    lv_obj_set_width(ui_Arc6, 454);
    lv_obj_set_height(ui_Arc6, 454);
    lv_obj_set_x(ui_Arc6, 102);
    lv_obj_set_y(ui_Arc6, -179);
    lv_obj_set_align(ui_Arc6, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc6, 50);
    lv_arc_set_bg_angles(ui_Arc6, 320, 0);
    lv_arc_set_rotation(ui_Arc6, 140);
    lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc6, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0xF5D8C2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc6, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk08_power = lv_obj_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_power, 150);
    lv_obj_set_height(ui_clk08_power, 95);
    lv_obj_set_x(ui_clk08_power, 106);
    lv_obj_set_y(ui_clk08_power, -176);
    lv_obj_set_align(ui_clk08_power, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk08_power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk08_power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk08_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk08_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk08_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc7 = lv_arc_create(ui_clk08_power);
    lv_obj_set_width(ui_Arc7, 454);
    lv_obj_set_height(ui_Arc7, 454);
    lv_obj_set_x(ui_Arc7, -104);
    lv_obj_set_y(ui_Arc7, 178);
    lv_obj_set_align(ui_Arc7, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc7, 50);
    lv_arc_set_bg_angles(ui_Arc7, 320, 0);
    lv_arc_set_rotation(ui_Arc7, 320);
    lv_obj_set_style_arc_color(ui_Arc7, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc7, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc7, lv_color_hex(0xF5D8C2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc7, 16, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc7, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk08_power_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_power_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_power_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_power_txt, 143);
    lv_obj_set_y(ui_clk08_power_txt, -227);
    lv_obj_set_align(ui_clk08_power_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_power_txt, "POWER");
    lv_obj_set_style_text_font(ui_clk08_power_txt, &ui_font_HONO_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_clk08_power_txt, 300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_sp02_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_sp02_txt, 62);
    lv_obj_set_height(ui_clk08_sp02_txt, 21);
    lv_obj_set_x(ui_clk08_sp02_txt, -145);
    lv_obj_set_y(ui_clk08_sp02_txt, -185);
    lv_obj_set_align(ui_clk08_sp02_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_sp02_txt, "SPO2");
    lv_obj_set_style_text_font(ui_clk08_sp02_txt, &ui_font_HONO_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_clk08_sp02_txt, -350, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_kcal_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_kcal_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_kcal_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_kcal_txt, -120);
    lv_obj_set_y(ui_clk08_kcal_txt, 199);
    lv_obj_set_align(ui_clk08_kcal_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_kcal_txt, "KCAL");
    lv_obj_set_style_text_font(ui_clk08_kcal_txt, &ui_font_HONO_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_clk08_kcal_txt, 310, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_dist_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_dist_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_dist_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_dist_txt, 127);
    lv_obj_set_y(ui_clk08_dist_txt, 228);
    lv_obj_set_align(ui_clk08_dist_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_dist_txt, "DIST");
    lv_obj_set_style_text_font(ui_clk08_dist_txt, &ui_font_HONO_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_clk08_dist_txt, -300, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_hr_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_hr_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_hr_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_hr_txt, 0);
    lv_obj_set_y(ui_clk08_hr_txt, -96);
    lv_obj_set_align(ui_clk08_hr_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_hr_txt, "0");
    lv_obj_set_style_text_color(ui_clk08_hr_txt, lv_color_hex(0xDFDBDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk08_hr_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk08_hr_txt, &ui_font_GOTH_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_time = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_time, 0);
    lv_obj_set_y(ui_clk08_time, -2);
    lv_obj_set_align(ui_clk08_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_time, "10 09");
    lv_obj_set_style_text_font(ui_clk08_time, &ui_font_GOTH_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk08_steps_txt = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_clk08_steps_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk08_steps_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk08_steps_txt, 0);
    lv_obj_set_y(ui_clk08_steps_txt, 84);
    lv_obj_set_align(ui_clk08_steps_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk08_steps_txt, "5960");
    lv_obj_set_style_text_color(ui_clk08_steps_txt, lv_color_hex(0xDFDBDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk08_steps_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk08_steps_txt, &ui_font_GOTH_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_clk_08);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -8);
    lv_obj_set_y(ui_Label29, -9);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, ":");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_GOTH_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_08, ui_event_clk_08, LV_EVENT_ALL, NULL);

}

void ui_clk_08_screen_destroy(void)
{
    if(ui_clk_08) lv_obj_del(ui_clk_08);

    // NULL screen variables
    ui_clk_08 = NULL;
    ui_clk07_bg1 = NULL;
    ui_heart_rate = NULL;
    ui_steps = NULL;
    ui_Arc2 = NULL;
    ui_Image9 = NULL;
    ui_clk08_spo2 = NULL;
    ui_Arc4 = NULL;
    ui_clk08_dist = NULL;
    ui_Arc5 = NULL;
    ui_clk08_kcal = NULL;
    ui_Arc6 = NULL;
    ui_clk08_power = NULL;
    ui_Arc7 = NULL;
    ui_clk08_power_txt = NULL;
    ui_clk08_sp02_txt = NULL;
    ui_clk08_kcal_txt = NULL;
    ui_clk08_dist_txt = NULL;
    ui_clk08_hr_txt = NULL;
    ui_clk08_time = NULL;
    ui_clk08_steps_txt = NULL;
    ui_Label29 = NULL;

}
