// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_01_H
#define UI_CLK_01_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_01
extern void ui_clk_01_screen_init(void);
extern void ui_clk_01_screen_destroy(void);
extern void ui_event_clk_01(lv_event_t * e);
extern lv_obj_t * ui_clk_01;
extern lv_obj_t * ui_hour_;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_min;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_step_icon;
extern lv_obj_t * ui_Label1;
extern void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

