// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_15;
lv_obj_t * ui_clk15_bg_group;
lv_obj_t * ui_Image30;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label49;
lv_obj_t * ui_clk15_am_txt;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label54;
lv_obj_t * ui_Label53;
lv_obj_t * ui_Image31;
lv_obj_t * ui_Label56;
lv_obj_t * ui_Label57;
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label59;
lv_obj_t * ui_Image32;
lv_obj_t * ui_Label55;
lv_obj_t * ui_Label61;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label65;
lv_obj_t * ui_Image33;
lv_obj_t * ui_Image34;
lv_obj_t * ui_Image35;
lv_obj_t * ui_Label60;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Image36;

// event funtions
void ui_event_clk_15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk15nobot_Animation(ui_Label49, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_16, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_16_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_14, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_14_screen_init);
    }
}

// build funtions

void ui_clk_15_screen_init(void)
{
    ui_clk_15 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk15_bg_group = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_clk15_bg_group, 410);
    lv_obj_set_height(ui_clk15_bg_group, 502);
    lv_obj_set_align(ui_clk15_bg_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk15_bg_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_clk15_bg_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk15_bg_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image30 = lv_image_create(ui_clk15_bg_group);
    lv_image_set_src(ui_Image30, &clk15_bg);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label48 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label48, 54);
    lv_obj_set_y(ui_Label48, 124);
    lv_label_set_text(ui_Label48, "88 88");
    lv_obj_set_style_text_color(ui_Label48, lv_color_hex(0xADB79B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label48, &ui_font_DIGI_90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label50 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label50, 54);
    lv_obj_set_y(ui_Label50, 124);
    lv_label_set_text(ui_Label50, "09 45");
    lv_obj_set_style_text_color(ui_Label50, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label50, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label50, &ui_font_DIGI_90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label49 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label49, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label49, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label49, 0);
    lv_obj_set_y(ui_Label49, -54);
    lv_obj_set_align(ui_Label49, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label49, ":");
    lv_obj_set_style_text_color(ui_Label49, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label49, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label49, &ui_font_HONOR_80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk15_am_txt = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_clk15_am_txt, 48);
    lv_obj_set_height(ui_clk15_am_txt, 30);
    lv_obj_set_x(ui_clk15_am_txt, 133);
    lv_obj_set_y(ui_clk15_am_txt, 21);
    lv_obj_set_align(ui_clk15_am_txt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk15_am_txt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk15_am_txt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk15_am_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk15_am_txt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk15_am_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label51 = lv_label_create(ui_clk15_am_txt);
    lv_obj_set_width(ui_Label51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label51, 0);
    lv_obj_set_y(ui_Label51, -1);
    lv_obj_set_align(ui_Label51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label51, "AM");
    lv_obj_set_style_text_font(ui_Label51, &ui_font_DIGI_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label52 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label52, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label52, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label52, -85);
    lv_obj_set_y(ui_Label52, -151);
    lv_obj_set_align(ui_Label52, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label52, "88 88");
    lv_obj_set_style_text_color(ui_Label52, lv_color_hex(0xADB79B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label52, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label52, &ui_font_DIGI_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label54 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label54, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label54, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label54, -85);
    lv_obj_set_y(ui_Label54, -151);
    lv_obj_set_align(ui_Label54, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label54, "09 26");
    lv_obj_set_style_text_color(ui_Label54, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label54, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label54, &ui_font_DIGI_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label53 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, -87);
    lv_obj_set_y(ui_Label53, -141);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, ".");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_HONOR_M_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image31 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image31, &clk15_weather);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 46
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image31, 47);
    lv_obj_set_y(ui_Image31, -149);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label56 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 285);
    lv_obj_set_y(ui_Label56, 73);
    lv_label_set_text(ui_Label56, "88");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0xADB79B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_DIGI_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label57 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label57, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label57, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label57, 285);
    lv_obj_set_y(ui_Label57, 73);
    lv_label_set_text(ui_Label57, "26");
    lv_obj_set_style_text_color(ui_Label57, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label57, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label57, &ui_font_DIGI_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label58, 205);
    lv_obj_set_y(ui_Label58, 260);
    lv_label_set_text(ui_Label58, "88 88");
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0xADB79B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &ui_font_DIGI_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 205);
    lv_obj_set_y(ui_Label59, 260);
    lv_label_set_text(ui_Label59, "06 50");
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_DIGI_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image32 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image32, &clk15_point);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_Image32, 34);
    lv_obj_set_y(ui_Image32, 34);
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label55 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 81);
    lv_obj_set_y(ui_Label55, 378);
    lv_label_set_text(ui_Label55, "88888");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xB0B6A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 81);
    lv_obj_set_y(ui_Label61, 378);
    lv_label_set_text(ui_Label61, "59600");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label62, 81);
    lv_obj_set_y(ui_Label62, 425);
    lv_label_set_text(ui_Label62, "888");
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0xB0B6A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, 82);
    lv_obj_set_y(ui_Label63, 425);
    lv_label_set_text(ui_Label63, "396");
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 288);
    lv_obj_set_y(ui_Label64, 378);
    lv_label_set_text(ui_Label64, "888");
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xB0B6A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 306);
    lv_obj_set_y(ui_Label65, 378);
    lv_label_set_text(ui_Label65, "109");
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_DIGI_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image33 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image33, &clk15_bluetooth);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 29
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image33, 61);
    lv_obj_set_y(ui_Image33, 200);
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image34 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image34, &clk15_disturb);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image34, 104);
    lv_obj_set_y(ui_Image34, 201);
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image35 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image35, &clk15_alarm);
    lv_obj_set_width(ui_Image35, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image35, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image35, 143);
    lv_obj_set_y(ui_Image35, 201);
    lv_obj_set_align(ui_Image35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image35, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label60 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, -140);
    lv_obj_set_y(ui_Label60, 83);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60, "SUN");
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, -85);
    lv_obj_set_y(ui_Label67, 83);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label67, "MON");
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0xED342C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label67, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, -30);
    lv_obj_set_y(ui_Label68, 83);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label68, "TUE");
    lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label68, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 27);
    lv_obj_set_y(ui_Label69, 83);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label69, "WED");
    lv_obj_set_style_text_color(ui_Label69, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label69, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label69, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label70 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label70, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label70, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label70, 81);
    lv_obj_set_y(ui_Label70, 83);
    lv_obj_set_align(ui_Label70, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label70, "FRI");
    lv_obj_set_style_text_color(ui_Label70, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label70, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label70, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label71 = lv_label_create(ui_clk_15);
    lv_obj_set_width(ui_Label71, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label71, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label71, 136);
    lv_obj_set_y(ui_Label71, 83);
    lv_obj_set_align(ui_Label71, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label71, "SAT");
    lv_obj_set_style_text_color(ui_Label71, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label71, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label71, &ui_font_DJB_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel26, 20);
    lv_obj_set_height(ui_Panel26, 4);
    lv_obj_set_x(ui_Panel26, -85);
    lv_obj_set_y(ui_Panel26, 99);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0xED342C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel15, 20);
    lv_obj_set_height(ui_Panel15, 4);
    lv_obj_set_x(ui_Panel15, -140);
    lv_obj_set_y(ui_Panel15, 99);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel16, 20);
    lv_obj_set_height(ui_Panel16, 4);
    lv_obj_set_x(ui_Panel16, -30);
    lv_obj_set_y(ui_Panel16, 99);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel17, 20);
    lv_obj_set_height(ui_Panel17, 4);
    lv_obj_set_x(ui_Panel17, 25);
    lv_obj_set_y(ui_Panel17, 99);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel18, 20);
    lv_obj_set_height(ui_Panel18, 4);
    lv_obj_set_x(ui_Panel18, 80);
    lv_obj_set_y(ui_Panel18, 99);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_clk_15);
    lv_obj_set_width(ui_Panel19, 20);
    lv_obj_set_height(ui_Panel19, 4);
    lv_obj_set_x(ui_Panel19, 135);
    lv_obj_set_y(ui_Panel19, 99);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xCFD9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_clk_15);
    lv_slider_set_value(ui_Slider4, 49, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 127);
    lv_obj_set_height(ui_Slider4, 22);
    lv_obj_set_x(ui_Slider4, 77);
    lv_obj_set_y(ui_Slider4, -225);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider4, &clk15_bat_prg, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Slider4, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Slider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Slider4, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider4, &clk15_bat_prg, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Slider4, lv_color_hex(0x4E8ADE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Slider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_Slider4, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider4,
                                                                                              lv_obj_get_style_pad_right(ui_Slider4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image36 = lv_image_create(ui_clk_15);
    lv_image_set_src(ui_Image36, &clk15_bat);
    lv_obj_set_width(ui_Image36, LV_SIZE_CONTENT);   /// 15
    lv_obj_set_height(ui_Image36, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image36, 1);
    lv_obj_set_y(ui_Image36, -225);
    lv_obj_set_align(ui_Image36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image36, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_clk_15, ui_event_clk_15, LV_EVENT_ALL, NULL);

}

void ui_clk_15_screen_destroy(void)
{
    if(ui_clk_15) lv_obj_del(ui_clk_15);

    // NULL screen variables
    ui_clk_15 = NULL;
    ui_clk15_bg_group = NULL;
    ui_Image30 = NULL;
    ui_Label48 = NULL;
    ui_Label50 = NULL;
    ui_Label49 = NULL;
    ui_clk15_am_txt = NULL;
    ui_Label51 = NULL;
    ui_Label52 = NULL;
    ui_Label54 = NULL;
    ui_Label53 = NULL;
    ui_Image31 = NULL;
    ui_Label56 = NULL;
    ui_Label57 = NULL;
    ui_Label58 = NULL;
    ui_Label59 = NULL;
    ui_Image32 = NULL;
    ui_Label55 = NULL;
    ui_Label61 = NULL;
    ui_Label62 = NULL;
    ui_Label63 = NULL;
    ui_Label64 = NULL;
    ui_Label65 = NULL;
    ui_Image33 = NULL;
    ui_Image34 = NULL;
    ui_Image35 = NULL;
    ui_Label60 = NULL;
    ui_Label67 = NULL;
    ui_Label68 = NULL;
    ui_Label69 = NULL;
    ui_Label70 = NULL;
    ui_Label71 = NULL;
    ui_Panel26 = NULL;
    ui_Panel15 = NULL;
    ui_Panel16 = NULL;
    ui_Panel17 = NULL;
    ui_Panel18 = NULL;
    ui_Panel19 = NULL;
    ui_Slider4 = NULL;
    ui_Image36 = NULL;

}
