// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_05;
lv_obj_t * ui_clk04_bg2;
lv_obj_t * ui_clk_04_bg1;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label20;
lv_obj_t * ui_clk05_am_txt;
lv_obj_t * ui_clk05_week_txt;
lv_obj_t * ui_clk05_date_txt;
lv_obj_t * ui_clk05_hr_txt;
lv_obj_t * ui_clk05_hr_icon;
lv_obj_t * ui_clk05_bat_prg;
lv_obj_t * ui_clk05_bat_icon;
lv_obj_t * ui_clk_kcal;
lv_obj_t * ui_Ck05_kcal_txt;
lv_obj_t * ui_kcal_txt;
lv_obj_t * ui_clk05_kcal_prg;
lv_obj_t * ui_clk05_kcal_icon;
lv_obj_t * ui_clk05_kcal;
lv_obj_t * ui_Ck05_step;
lv_obj_t * ui_clk05_step_prg;
lv_obj_t * ui_ckl05_step;
lv_obj_t * ui_Ck05_step_txt;
lv_obj_t * ui_clk05_step_txt;
lv_obj_t * ui_clk05_step_icon;

// event funtions
void ui_event_clk_05(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        clk05dots_Animation(ui_Label20, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_06, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_06_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_04, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_04_screen_init);
    }
}

void ui_event_clk05_kcal_prg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_kcal_txt, target, "", "");
    }
}

void ui_event_clk05_step_prg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_clk05_step_txt, target, "", "");
    }
}

// build funtions

void ui_clk_05_screen_init(void)
{
    ui_clk_05 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_05, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk_05, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk04_bg2 = lv_obj_create(ui_clk_05);
    lv_obj_set_width(ui_clk04_bg2, 410);
    lv_obj_set_height(ui_clk04_bg2, 502);
    lv_obj_set_align(ui_clk04_bg2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk04_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clk04_bg2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk04_bg2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk04_bg2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk04_bg2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk04_bg2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk_04_bg1 = lv_image_create(ui_clk04_bg2);
    lv_image_set_src(ui_clk_04_bg1, &clk05_bg);
    lv_obj_set_width(ui_clk_04_bg1, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_clk_04_bg1, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_clk_04_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk_04_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk_04_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "09 36");
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_BAIDU_122, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, -19);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, ":");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_BAIDU_122, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_am_txt = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_clk05_am_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_am_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_am_txt, 35);
    lv_obj_set_y(ui_clk05_am_txt, 155);
    lv_label_set_text(ui_clk05_am_txt, "AM");
    lv_obj_set_style_text_color(ui_clk05_am_txt, lv_color_hex(0x747474), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk05_am_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk05_am_txt, &ui_font_YOUSHE_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_week_txt = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_clk05_week_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_week_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_week_txt, 35);
    lv_obj_set_y(ui_clk05_week_txt, 79);
    lv_label_set_text(ui_clk05_week_txt, "MON");
    lv_obj_set_style_text_color(ui_clk05_week_txt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk05_week_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_clk05_week_txt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_clk05_week_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clk05_week_txt, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk05_week_txt, &ui_font_YOUSHE_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_date_txt = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_clk05_date_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_date_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_date_txt, 35);
    lv_obj_set_y(ui_clk05_date_txt, 38);
    lv_label_set_text(ui_clk05_date_txt, "08/26");
    lv_obj_set_style_text_letter_space(ui_clk05_date_txt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_clk05_date_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clk05_date_txt, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk05_date_txt, &ui_font_YOUSHE_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_hr_txt = lv_label_create(ui_clk_05);
    lv_obj_set_width(ui_clk05_hr_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_hr_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_hr_txt, 317);
    lv_obj_set_y(ui_clk05_hr_txt, 367);
    lv_label_set_text(ui_clk05_hr_txt, "129");
    lv_obj_set_style_text_font(ui_clk05_hr_txt, &ui_font_YOUSHE_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_hr_icon = lv_image_create(ui_clk_05);
    lv_image_set_src(ui_clk05_hr_icon, &clk05_hr_icon);
    lv_obj_set_width(ui_clk05_hr_icon, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_clk05_hr_icon, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_clk05_hr_icon, 157);
    lv_obj_set_y(ui_clk05_hr_icon, 93);
    lv_obj_set_align(ui_clk05_hr_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk05_hr_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk05_hr_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk05_bat_prg = lv_slider_create(ui_clk_05);
    lv_slider_set_value(ui_clk05_bat_prg, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_clk05_bat_prg) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_clk05_bat_prg, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_clk05_bat_prg, 127);
    lv_obj_set_height(ui_clk05_bat_prg, 32);
    lv_obj_set_x(ui_clk05_bat_prg, 248);
    lv_obj_set_y(ui_clk05_bat_prg, 423);
    lv_obj_set_style_radius(ui_clk05_bat_prg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk05_bat_prg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk05_bat_prg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_clk05_bat_prg, &clk05_bat_prg, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_clk05_bat_prg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clk05_bat_prg, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk05_bat_prg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_clk05_bat_prg, &clk05_bat_prg,
                                  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_clk05_bat_prg, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_clk05_bat_prg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_clk05_bat_prg, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clk05_bat_prg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk05_bat_prg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_clk05_bat_prg, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_clk05_bat_prg,
                                                                                                    lv_obj_get_style_pad_right(ui_clk05_bat_prg, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_clk05_bat_icon = lv_image_create(ui_clk_05);
    lv_image_set_src(ui_clk05_bat_icon, &clk05_bat_icon);
    lv_obj_set_width(ui_clk05_bat_icon, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_clk05_bat_icon, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_clk05_bat_icon, 22);
    lv_obj_set_y(ui_clk05_bat_icon, 187);
    lv_obj_set_align(ui_clk05_bat_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk05_bat_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk05_bat_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk_kcal = lv_obj_create(ui_clk_05);
    lv_obj_set_width(ui_clk_kcal, 215);
    lv_obj_set_height(ui_clk_kcal, 135);
    lv_obj_set_x(ui_clk_kcal, 78);
    lv_obj_set_y(ui_clk_kcal, -150);
    lv_obj_set_align(ui_clk_kcal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk_kcal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk_kcal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_kcal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk_kcal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk_kcal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ck05_kcal_txt = lv_obj_create(ui_clk_kcal);
    lv_obj_set_width(ui_Ck05_kcal_txt, 104);
    lv_obj_set_height(ui_Ck05_kcal_txt, 40);
    lv_obj_set_x(ui_Ck05_kcal_txt, -56);
    lv_obj_set_y(ui_Ck05_kcal_txt, 15);
    lv_obj_set_align(ui_Ck05_kcal_txt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Ck05_kcal_txt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ck05_kcal_txt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ck05_kcal_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Ck05_kcal_txt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Ck05_kcal_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_kcal_txt = lv_label_create(ui_Ck05_kcal_txt);
    lv_obj_set_width(ui_kcal_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_kcal_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_kcal_txt, 15);
    lv_obj_set_y(ui_kcal_txt, -23);
    lv_obj_set_align(ui_kcal_txt, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_kcal_txt, "396");
    lv_obj_set_style_text_letter_space(ui_kcal_txt, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_kcal_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_kcal_txt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_kcal_txt, &ui_font_BEBAS_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_kcal_prg = lv_arc_create(ui_clk_kcal);
    lv_obj_set_width(ui_clk05_kcal_prg, 124);
    lv_obj_set_height(ui_clk05_kcal_prg, 124);
    lv_obj_set_x(ui_clk05_kcal_prg, 41);
    lv_obj_set_y(ui_clk05_kcal_prg, 0);
    lv_obj_set_align(ui_clk05_kcal_prg, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_clk05_kcal_prg, 0, 1000);
    lv_arc_set_value(ui_clk05_kcal_prg, 496);
    lv_arc_set_bg_angles(ui_clk05_kcal_prg, 190, 130);
    lv_obj_set_style_arc_color(ui_clk05_kcal_prg, lv_color_hex(0x332403), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk05_kcal_prg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk05_kcal_prg, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_clk05_kcal_prg, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_clk05_kcal_prg, lv_color_hex(0xFFB60F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk05_kcal_prg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk05_kcal_prg, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_clk05_kcal_prg, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clk05_kcal_prg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk05_kcal_prg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_clk05_kcal_icon = lv_image_create(ui_clk_kcal);
    lv_image_set_src(ui_clk05_kcal_icon, &clk05_kcal_icon);
    lv_obj_set_width(ui_clk05_kcal_icon, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_clk05_kcal_icon, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_clk05_kcal_icon, 40);
    lv_obj_set_y(ui_clk05_kcal_icon, -2);
    lv_obj_set_align(ui_clk05_kcal_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk05_kcal_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk05_kcal_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk05_kcal = lv_label_create(ui_clk_kcal);
    lv_obj_set_width(ui_clk05_kcal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_kcal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_kcal, -38);
    lv_obj_set_y(ui_clk05_kcal, 50);
    lv_obj_set_align(ui_clk05_kcal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk05_kcal, "KCAL");
    lv_obj_set_style_text_color(ui_clk05_kcal, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk05_kcal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk05_kcal, &ui_font_YOUSHE_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ck05_step = lv_obj_create(ui_clk_05);
    lv_obj_set_width(ui_Ck05_step, 190);
    lv_obj_set_height(ui_Ck05_step, 135);
    lv_obj_set_x(ui_Ck05_step, -90);
    lv_obj_set_y(ui_Ck05_step, 146);
    lv_obj_set_align(ui_Ck05_step, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Ck05_step, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ck05_step, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ck05_step, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Ck05_step, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Ck05_step, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_step_prg = lv_arc_create(ui_Ck05_step);
    lv_obj_set_width(ui_clk05_step_prg, 124);
    lv_obj_set_height(ui_clk05_step_prg, 124);
    lv_obj_set_x(ui_clk05_step_prg, -27);
    lv_obj_set_y(ui_clk05_step_prg, 0);
    lv_obj_set_align(ui_clk05_step_prg, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_clk05_step_prg, 0, 5000);
    lv_arc_set_value(ui_clk05_step_prg, 3900);
    lv_arc_set_bg_angles(ui_clk05_step_prg, 10, 290);
    lv_obj_set_style_arc_color(ui_clk05_step_prg, lv_color_hex(0x0D2E1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk05_step_prg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk05_step_prg, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_clk05_step_prg, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_clk05_step_prg, lv_color_hex(0x3FE883), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_clk05_step_prg, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_clk05_step_prg, 14, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_clk05_step_prg, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clk05_step_prg, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk05_step_prg, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ckl05_step = lv_label_create(ui_Ck05_step);
    lv_obj_set_width(ui_ckl05_step, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ckl05_step, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ckl05_step, 74);
    lv_obj_set_y(ui_ckl05_step, 27);
    lv_label_set_text(ui_ckl05_step, "STEPS");
    lv_obj_set_style_text_color(ui_ckl05_step, lv_color_hex(0x5D5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ckl05_step, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ckl05_step, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ckl05_step, &ui_font_YOUSHE_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ck05_step_txt = lv_obj_create(ui_Ck05_step);
    lv_obj_set_width(ui_Ck05_step_txt, 96);
    lv_obj_set_height(ui_Ck05_step_txt, 40);
    lv_obj_set_x(ui_Ck05_step_txt, 44);
    lv_obj_set_y(ui_Ck05_step_txt, -42);
    lv_obj_set_align(ui_Ck05_step_txt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Ck05_step_txt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Ck05_step_txt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ck05_step_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Ck05_step_txt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Ck05_step_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_step_txt = lv_label_create(ui_Ck05_step_txt);
    lv_obj_set_width(ui_clk05_step_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk05_step_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk05_step_txt, -16);
    lv_obj_set_y(ui_clk05_step_txt, -23);
    lv_label_set_text(ui_clk05_step_txt, "3900");
    lv_obj_set_style_text_letter_space(ui_clk05_step_txt, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_clk05_step_txt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clk05_step_txt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk05_step_txt, &ui_font_BEBAS_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk05_step_icon = lv_image_create(ui_Ck05_step);
    lv_image_set_src(ui_clk05_step_icon, &clk05_step_icon);
    lv_obj_set_width(ui_clk05_step_icon, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_clk05_step_icon, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_clk05_step_icon, -29);
    lv_obj_set_y(ui_clk05_step_icon, -2);
    lv_obj_set_align(ui_clk05_step_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk05_step_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk05_step_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_clk05_kcal_prg, ui_event_clk05_kcal_prg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk05_step_prg, ui_event_clk05_step_prg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_05, ui_event_clk_05, LV_EVENT_ALL, NULL);

}

void ui_clk_05_screen_destroy(void)
{
    if(ui_clk_05) lv_obj_del(ui_clk_05);

    // NULL screen variables
    ui_clk_05 = NULL;
    ui_clk04_bg2 = NULL;
    ui_clk_04_bg1 = NULL;
    ui_Label15 = NULL;
    ui_Label20 = NULL;
    ui_clk05_am_txt = NULL;
    ui_clk05_week_txt = NULL;
    ui_clk05_date_txt = NULL;
    ui_clk05_hr_txt = NULL;
    ui_clk05_hr_icon = NULL;
    ui_clk05_bat_prg = NULL;
    ui_clk05_bat_icon = NULL;
    ui_clk_kcal = NULL;
    ui_Ck05_kcal_txt = NULL;
    ui_kcal_txt = NULL;
    ui_clk05_kcal_prg = NULL;
    ui_clk05_kcal_icon = NULL;
    ui_clk05_kcal = NULL;
    ui_Ck05_step = NULL;
    ui_clk05_step_prg = NULL;
    ui_ckl05_step = NULL;
    ui_Ck05_step_txt = NULL;
    ui_clk05_step_txt = NULL;
    ui_clk05_step_icon = NULL;

}
