// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CAMPAIGN_COUNTDOWN_H
#define UI_CAMPAIGN_COUNTDOWN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Campaign_Countdown
extern void ui_Campaign_Countdown_screen_init(void);
extern void ui_Campaign_Countdown_screen_destroy(void);
extern lv_obj_t * ui_Campaign_Countdown;
extern void ui_event_Campaign_List_group7(lv_event_t * e);
extern lv_obj_t * ui_Campaign_List_group7;
extern lv_obj_t * ui_count_down_date;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

