// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_07_H
#define UI_CLK_07_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_07
extern void ui_clk_07_screen_init(void);
extern void ui_clk_07_screen_destroy(void);
extern void ui_event_clk_07(lv_event_t * e);
extern lv_obj_t * ui_clk_07;
extern lv_obj_t * ui_clk07_bg_group;
extern lv_obj_t * ui_clk07_bg;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

