// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_17_H
#define UI_CLK_17_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_17
extern void ui_clk_17_screen_init(void);
extern void ui_clk_17_screen_destroy(void);
extern void ui_event_clk_17(lv_event_t * e);
extern lv_obj_t * ui_clk_17;
extern lv_obj_t * ui_clk17_bg_group;
extern lv_obj_t * ui_clk17_bg;
extern lv_obj_t * ui_Label76;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_Label79;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_Label81;
extern lv_obj_t * ui_Label82;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_Label85;
extern lv_obj_t * ui_Label86;
extern lv_obj_t * ui_Label84;
extern lv_obj_t * ui_Label88;
extern lv_obj_t * ui_Label89;
extern lv_obj_t * ui_Label87;
extern lv_obj_t * ui_Label91;
extern lv_obj_t * ui_Label92;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label90;
extern lv_obj_t * ui_Label94;
extern lv_obj_t * ui_Image15;
extern void ui_event_Bar2(lv_event_t * e);
extern lv_obj_t * ui_Bar2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

