// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_15_H
#define UI_CLK_15_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_15
extern void ui_clk_15_screen_init(void);
extern void ui_clk_15_screen_destroy(void);
extern void ui_event_clk_15(lv_event_t * e);
extern lv_obj_t * ui_clk_15;
extern lv_obj_t * ui_clk15_bg_group;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_clk15_am_txt;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Label57;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Image32;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label61;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
extern lv_obj_t * ui_Image33;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Image35;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Image36;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

