// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_16_H
#define UI_CLK_16_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_16
extern void ui_clk_16_screen_init(void);
extern void ui_clk_16_screen_destroy(void);
extern void ui_event_clk_16(lv_event_t * e);
extern lv_obj_t * ui_clk_16;
extern lv_obj_t * ui_clk16_bg_group;
extern lv_obj_t * ui_clk16_hr_group;
extern lv_obj_t * ui_clk16_hr_icon;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_clk16_step_group;
extern lv_obj_t * ui_clk16_spots_icon;
extern lv_obj_t * ui_Panel22;
extern void ui_event_Arc9(lv_event_t * e);
extern lv_obj_t * ui_Arc9;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label73;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label75;
extern lv_obj_t * ui_clk16_time_hour;
extern lv_obj_t * ui_clk16_data_txt;
extern lv_obj_t * ui_clk16_time_min;
extern lv_obj_t * ui_clk16_data_txt2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

