// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_02;
lv_obj_t * ui_scr_bg1;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_steps_02;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label8;
lv_obj_t * ui_steps_2;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Label10;

// event funtions
void ui_event_clk_02(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_03, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_03_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_01, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_01_screen_init);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label8, target, "", "%");
    }
}

void ui_event_Arc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label10, target, "", "%");
    }
}

// build funtions

void ui_clk_02_screen_init(void)
{
    ui_clk_02 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk_02, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk_02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_bg1 = lv_obj_create(ui_clk_02);
    lv_obj_set_width(ui_scr_bg1, 410);
    lv_obj_set_height(ui_scr_bg1, 502);
    lv_obj_set_align(ui_scr_bg1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_scr_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_scr_bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_scr_bg1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_scr_bg1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scr_bg1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scr_bg1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_scr_bg1);
    lv_image_set_src(ui_Image5, &clk02_bg);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_clk_02);
    lv_obj_set_width(ui_Panel2, 250);
    lv_obj_set_height(ui_Panel2, 190);
    lv_obj_set_x(ui_Panel2, 72);
    lv_obj_set_y(ui_Panel2, -50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, 245);
    lv_obj_set_height(ui_Label4, 186);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "09");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xEFFFB9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_HONORS_200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_clk_02);
    lv_obj_set_width(ui_Panel5, 250);
    lv_obj_set_height(ui_Panel5, 190);
    lv_obj_set_x(ui_Panel5, 72);
    lv_obj_set_y(ui_Panel5, 133);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label7, 245);
    lv_obj_set_height(ui_Label7, 186);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "45");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xBCFF4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_HONORS_200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_clk_02);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 113);
    lv_obj_set_y(ui_Label6, -161);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "85%");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xB9B9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_clk_02);
    lv_image_set_src(ui_Image7, &clk02_power);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image7, 72);
    lv_obj_set_y(ui_Image7, -162);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_steps_02 = lv_obj_create(ui_clk_02);
    lv_obj_set_width(ui_steps_02, 120);
    lv_obj_set_height(ui_steps_02, 120);
    lv_obj_set_x(ui_steps_02, -127);
    lv_obj_set_y(ui_steps_02, -10);
    lv_obj_set_align(ui_steps_02, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_steps_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_steps_02, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_steps_02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_steps_02, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_steps_02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_steps_02);
    lv_image_set_src(ui_Image8, &clk02_step);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Image8, 1);
    lv_obj_set_y(ui_Image8, -42);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_steps_02);
    lv_obj_set_width(ui_Arc1, 110);
    lv_obj_set_height(ui_Arc1, 110);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 60);
    lv_arc_set_bg_angles(ui_Arc1, 310, 230);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_steps_02);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 1);
    lv_obj_set_y(ui_Label8, 4);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "60%");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xB9B9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_HONORS_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_steps_2 = lv_obj_create(ui_clk_02);
    lv_obj_set_width(ui_steps_2, 120);
    lv_obj_set_height(ui_steps_2, 120);
    lv_obj_set_x(ui_steps_2, -127);
    lv_obj_set_y(ui_steps_2, 136);
    lv_obj_set_align(ui_steps_2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_steps_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_steps_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_steps_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_steps_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_steps_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_steps_2);
    lv_image_set_src(ui_Image2, &clk02_power);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Image2, 1);
    lv_obj_set_y(ui_Image2, -42);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc3 = lv_arc_create(ui_steps_2);
    lv_obj_set_width(ui_Arc3, 110);
    lv_obj_set_height(ui_Arc3, 110);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 70);
    lv_arc_set_bg_angles(ui_Arc3, 310, 230);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xB9B9B9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_steps_2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, 4);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "70%");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xB9B9B9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_HONORS_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_02, ui_event_clk_02, LV_EVENT_ALL, NULL);

}

void ui_clk_02_screen_destroy(void)
{
    if(ui_clk_02) lv_obj_del(ui_clk_02);

    // NULL screen variables
    ui_clk_02 = NULL;
    ui_scr_bg1 = NULL;
    ui_Image5 = NULL;
    ui_Panel2 = NULL;
    ui_Label4 = NULL;
    ui_Panel5 = NULL;
    ui_Label7 = NULL;
    ui_Label6 = NULL;
    ui_Image7 = NULL;
    ui_steps_02 = NULL;
    ui_Image8 = NULL;
    ui_Arc1 = NULL;
    ui_Label8 = NULL;
    ui_steps_2 = NULL;
    ui_Image2 = NULL;
    ui_Arc3 = NULL;
    ui_Label10 = NULL;

}
