// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_03_H
#define UI_CLK_03_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_03
extern void ui_clk_03_screen_init(void);
extern void ui_clk_03_screen_destroy(void);
extern void ui_event_clk_03(lv_event_t * e);
extern lv_obj_t * ui_clk_03;
extern lv_obj_t * ui_clk03_bg;
extern lv_obj_t * ui_clk03_bg01;
extern lv_obj_t * ui_clk03_week;
extern lv_obj_t * ui_week_txt;
extern lv_obj_t * ui_clk03_time;
extern lv_obj_t * ui_clk03_h_txt;
extern lv_obj_t * ui_clk03_m_txt;
extern lv_obj_t * ui_clk03_am_txt;
extern lv_obj_t * ui_clk03_week_txt;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

