// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_11_H
#define UI_CLK_11_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_11
extern void ui_clk_11_screen_init(void);
extern void ui_clk_11_screen_destroy(void);
extern void ui_event_clk_11(lv_event_t * e);
extern lv_obj_t * ui_clk_11;
extern lv_obj_t * ui_clk11_bg_group;
extern lv_obj_t * ui_clk11_bg;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label45;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

