// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_06_H
#define UI_CLK_06_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_06
extern void ui_clk_06_screen_init(void);
extern void ui_clk_06_screen_destroy(void);
extern void ui_event_clk_06(lv_event_t * e);
extern lv_obj_t * ui_clk_06;
extern lv_obj_t * ui_clk06_bg_group;
extern lv_obj_t * ui_clk06_bg;
extern lv_obj_t * ui_clk06_week_group;
extern lv_obj_t * ui_clk06_week_txt;
extern lv_obj_t * ui_clk06_weather_group;
extern lv_obj_t * ui_clk06_weather_icon;
extern lv_obj_t * ui_clk06_hr_group;
extern lv_obj_t * ui_clk06_hr_txt;
extern lv_obj_t * ui_clk06_date_txt;
extern void ui_event_clk06_step_prg(lv_event_t * e);
extern lv_obj_t * ui_clk06_step_prg;
extern lv_obj_t * ui_clk06_step_icon;
extern lv_obj_t * ui_clk06_step_txt;
extern lv_obj_t * ui_clk06_kcal_icon;
extern lv_obj_t * ui_clk06_kcal_txt;
extern lv_obj_t * ui_Panel11;
extern void ui_event_clk06_kcal_prg(lv_event_t * e);
extern lv_obj_t * ui_clk06_kcal_prg;
extern void ui_event_clk06_bat_prg(lv_event_t * e);
extern lv_obj_t * ui_clk06_bat_prg;
extern lv_obj_t * ui_clk06_bat_icon;
extern lv_obj_t * ui_clk06_bat_txt;
extern lv_obj_t * ui_clk06_hour;
extern lv_obj_t * ui_clk06_minut;
extern lv_obj_t * ui_clk06_circle;
extern lv_obj_t * ui_clk06_sec;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

