// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CAMPAIGN_PAUSE_H
#define UI_CAMPAIGN_PAUSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Campaign_Pause
extern void ui_Campaign_Pause_screen_init(void);
extern void ui_Campaign_Pause_screen_destroy(void);
extern void ui_event_Campaign_Pause(lv_event_t * e);
extern lv_obj_t * ui_Campaign_Pause;
extern lv_obj_t * ui_Campaign_List_group9;
extern lv_obj_t * ui_Primarystatusbar9;
extern lv_obj_t * ui_bar1;
extern lv_obj_t * ui_bar_icon_1;
extern lv_obj_t * ui_bar_icon_2;
extern lv_obj_t * ui_bar_icon_3;
extern lv_obj_t * ui_move_lock_up_icon;
extern lv_obj_t * ui_move_sound_icon;
extern void ui_event_move_abort_icon(lv_event_t * e);
extern lv_obj_t * ui_move_abort_icon;
extern lv_obj_t * ui_move_pause_icon01;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

