// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CAMPAIGN_LIST_H
#define UI_CAMPAIGN_LIST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Campaign_List
extern void ui_Campaign_List_screen_init(void);
extern void ui_Campaign_List_screen_destroy(void);
extern void ui_event_Campaign_List(lv_event_t * e);
extern lv_obj_t * ui_Campaign_List;
extern lv_obj_t * ui_Campaign_List_group;
extern void ui_event_Primarystatusbar_Primary_status_bar(lv_event_t * e);
extern lv_obj_t * ui_Primarystatusbar;
extern lv_obj_t * ui_Campaign_List_group01;
extern void ui_event_OutdoorRungroup3_Outdoor_Run_group1(lv_event_t * e);
extern lv_obj_t * ui_OutdoorRungroup3;
extern void ui_event_OutdoorRungroup3_Image1(lv_event_t * e);
extern void ui_event_OutdoorRungroup2_Outdoor_Run_group1(lv_event_t * e);
extern lv_obj_t * ui_OutdoorRungroup2;
extern void ui_event_OutdoorRungroup2_Image1(lv_event_t * e);
extern lv_obj_t * ui_OutdoorRungroup4;
extern lv_obj_t * ui_OutdoorRungroup5;
extern lv_obj_t * ui_OutdoorRungroup6;
extern lv_obj_t * ui_OutdoorRungroup7;
extern lv_obj_t * ui_OutdoorRungroup8;
extern lv_obj_t * ui_OutdoorRungroup9;
extern lv_obj_t * ui_OutdoorRungroup10;
extern lv_obj_t * ui_OutdoorRungroup11;
extern lv_obj_t * ui_OutdoorRungroup12;
extern lv_obj_t * ui_OutdoorRungroup13;
extern lv_obj_t * ui_OutdoorRungroup14;
extern lv_obj_t * ui_OutdoorRungroup15;
extern lv_obj_t * ui_OutdoorRungroup16;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

