// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_clk_03;
lv_obj_t * ui_clk03_bg;
lv_obj_t * ui_clk03_bg01;
lv_obj_t * ui_clk03_week;
lv_obj_t * ui_week_txt;
lv_obj_t * ui_clk03_time;
lv_obj_t * ui_clk03_h_txt;
lv_obj_t * ui_clk03_m_txt;
lv_obj_t * ui_clk03_am_txt;
lv_obj_t * ui_clk03_week_txt;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Slider2;

// event funtions
void ui_event_clk_03(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_04, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_clk_04_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_02, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_02_screen_init);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label12, target, "", "%");
    }
}

// build funtions

void ui_clk_03_screen_init(void)
{
    ui_clk_03 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_clk_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk03_bg = lv_obj_create(ui_clk_03);
    lv_obj_set_width(ui_clk03_bg, 410);
    lv_obj_set_height(ui_clk03_bg, 502);
    lv_obj_set_align(ui_clk03_bg, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk03_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_clk03_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk03_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_bg01 = lv_image_create(ui_clk03_bg);
    lv_image_set_src(ui_clk03_bg01, &clk03_bg);
    lv_obj_set_width(ui_clk03_bg01, LV_SIZE_CONTENT);   /// 410
    lv_obj_set_height(ui_clk03_bg01, LV_SIZE_CONTENT);    /// 502
    lv_obj_set_align(ui_clk03_bg01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clk03_bg01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_clk03_bg01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clk03_week = lv_obj_create(ui_clk_03);
    lv_obj_set_width(ui_clk03_week, 275);
    lv_obj_set_height(ui_clk03_week, 150);
    lv_obj_set_x(ui_clk03_week, 56);
    lv_obj_set_y(ui_clk03_week, -5);
    lv_obj_set_align(ui_clk03_week, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk03_week, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk03_week, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk03_week, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk03_week, lv_color_hex(0xD40D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk03_week, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week_txt = lv_label_create(ui_clk03_week);
    lv_obj_set_width(ui_week_txt, LV_SIZE_CONTENT);   /// 112
    lv_obj_set_height(ui_week_txt, LV_SIZE_CONTENT);    /// 126
    lv_obj_set_x(ui_week_txt, -12);
    lv_obj_set_y(ui_week_txt, -34);
    lv_label_set_text(ui_week_txt, "MON");
    lv_obj_set_style_text_align(ui_week_txt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week_txt, &ui_font_LED_180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_time = lv_obj_create(ui_clk_03);
    lv_obj_set_width(ui_clk03_time, 370);
    lv_obj_set_height(ui_clk03_time, 150);
    lv_obj_set_x(ui_clk03_time, 0);
    lv_obj_set_y(ui_clk03_time, 149);
    lv_obj_set_align(ui_clk03_time, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_clk03_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clk03_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clk03_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clk03_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clk03_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_h_txt = lv_label_create(ui_clk03_time);
    lv_obj_set_width(ui_clk03_h_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk03_h_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk03_h_txt, -5);
    lv_obj_set_y(ui_clk03_h_txt, -38);
    lv_label_set_text(ui_clk03_h_txt, "08");
    lv_obj_set_style_text_font(ui_clk03_h_txt, &ui_font_LED_190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_m_txt = lv_label_create(ui_clk03_time);
    lv_obj_set_width(ui_clk03_m_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk03_m_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk03_m_txt, 169);
    lv_obj_set_y(ui_clk03_m_txt, -38);
    lv_label_set_text(ui_clk03_m_txt, "26");
    lv_obj_set_style_text_color(ui_clk03_m_txt, lv_color_hex(0xE63640), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk03_m_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clk03_m_txt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk03_m_txt, &ui_font_LED_190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_am_txt = lv_label_create(ui_clk_03);
    lv_obj_set_width(ui_clk03_am_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk03_am_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk03_am_txt, -102);
    lv_obj_set_y(ui_clk03_am_txt, -53);
    lv_obj_set_align(ui_clk03_am_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk03_am_txt, "AM");
    lv_obj_set_style_text_align(ui_clk03_am_txt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk03_am_txt, &ui_font_LED_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clk03_week_txt = lv_label_create(ui_clk_03);
    lv_obj_set_width(ui_clk03_week_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clk03_week_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_clk03_week_txt, -129);
    lv_obj_set_y(ui_clk03_week_txt, 51);
    lv_obj_set_align(ui_clk03_week_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clk03_week_txt, "WEEK >>");
    lv_obj_set_style_text_color(ui_clk03_week_txt, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clk03_week_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_clk03_week_txt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clk03_week_txt, &ui_font_LED_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_clk_03);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 294);
    lv_obj_set_y(ui_Label9, 90);
    lv_label_set_text(ui_Label9, "06");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_LED_86, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_clk_03);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 294);
    lv_obj_set_y(ui_Label11, 48);
    lv_label_set_text(ui_Label11, "MAR");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_LED_54, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_clk_03);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 294);
    lv_obj_set_y(ui_Label12, 22);
    lv_label_set_text(ui_Label12, "60%");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_HONORS_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_clk_03);
    lv_slider_set_value(ui_Slider2, 60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 145);
    lv_obj_set_height(ui_Slider2, 24);
    lv_obj_set_x(ui_Slider2, 120);
    lv_obj_set_y(ui_Slider2, 22);
    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Slider2, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider2, &clk03_slider, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Slider2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider2, &clk03_slider, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_clk_03, ui_event_clk_03, LV_EVENT_ALL, NULL);

}

void ui_clk_03_screen_destroy(void)
{
    if(ui_clk_03) lv_obj_del(ui_clk_03);

    // NULL screen variables
    ui_clk_03 = NULL;
    ui_clk03_bg = NULL;
    ui_clk03_bg01 = NULL;
    ui_clk03_week = NULL;
    ui_week_txt = NULL;
    ui_clk03_time = NULL;
    ui_clk03_h_txt = NULL;
    ui_clk03_m_txt = NULL;
    ui_clk03_am_txt = NULL;
    ui_clk03_week_txt = NULL;
    ui_Label9 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Slider2 = NULL;

}
