// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_CLK_04_H
#define UI_CLK_04_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_clk_04
extern void ui_clk_04_screen_init(void);
extern void ui_clk_04_screen_destroy(void);
extern void ui_event_clk_04(lv_event_t * e);
extern lv_obj_t * ui_clk_04;
extern lv_obj_t * ui_clk04_bg1;
extern lv_obj_t * ui_clk_04_bg;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_clk04_hr_txt;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_clk04_dots;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

