// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_DISPLAY_BRIGHTNESS_H
#define UI_DISPLAY_BRIGHTNESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Display_Brightness
extern void ui_Display_Brightness_screen_init(void);
extern void ui_Display_Brightness_screen_destroy(void);
extern lv_obj_t * ui_Display_Brightness;
extern lv_obj_t * ui_setting_group1;
extern void ui_event_Primary_status_bar2(lv_event_t * e);
extern lv_obj_t * ui_Primary_status_bar2;
extern lv_obj_t * ui_caption_group2;
extern lv_obj_t * ui_caption_icon3;
extern lv_obj_t * ui_caption_time3;
extern lv_obj_t * ui_setting_group2;
extern lv_obj_t * ui_dialgroup10;
extern lv_obj_t * ui_Label106;
extern void ui_event_Image38(lv_event_t * e);
extern lv_obj_t * ui_Image38;
extern lv_obj_t * ui_Image39;
extern void ui_event_Image37(lv_event_t * e);
extern lv_obj_t * ui_Image37;
extern lv_obj_t * ui_Image40;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Panel36;
extern void ui_event_dialgroup1_dialgroup1(lv_event_t * e);
extern lv_obj_t * ui_dialgroup1;
extern lv_obj_t * ui_dialgroup12;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_dialgroup13;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_dial_txt1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

