// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * uic_Exercise_group;
lv_obj_t * ui_Feature_List;
lv_obj_t * ui_Feature_List_group;
lv_obj_t * ui_Feature_group;
lv_obj_t * ui_Exercise_group;
lv_obj_t * ui_Sports_record;
lv_obj_t * ui_Activity_group;
lv_obj_t * ui_Heart_rate_group;
lv_obj_t * ui_SpO2_group;
lv_obj_t * ui_sleep_group;
lv_obj_t * ui_stresses_group;
lv_obj_t * ui_surveying_group;
lv_obj_t * ui_physiology_group;
lv_obj_t * ui_card_bag_group;
lv_obj_t * ui_contacts_group;
lv_obj_t * ui_telephones_group;
lv_obj_t * ui_climatic_group;
lv_obj_t * ui_breathe_group;
lv_obj_t * ui_alipay;
lv_obj_t * ui_wechat_pay_group;
lv_obj_t * ui_music_group;
lv_obj_t * ui_cameras_group;
lv_obj_t * ui_drink_group;
lv_obj_t * ui_alarm_group;
lv_obj_t * ui_stopwatch_group;
lv_obj_t * ui_count_down_group;
lv_obj_t * ui_counter_group;
lv_obj_t * ui_record_group;
lv_obj_t * ui_compass_group;
lv_obj_t * ui_torch_group;
lv_obj_t * ui_find_group;
lv_obj_t * ui_setting_group;
lv_obj_t * ui_Bar4;

// event funtions
void ui_event_Feature_List(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_01, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clk_01_screen_init);
    }
}

void ui_event_Exercise_group_Feature_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_List, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Campaign_List_screen_init);
    }
}

void ui_event_Sports_record_Feature_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_List, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Campaign_List_screen_init);
    }
}

void ui_event_setting_group_Feature_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_setting_screen_init);
    }
}

// build funtions

void ui_Feature_List_screen_init(void)
{
    ui_Feature_List = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Feature_List, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Feature_List, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feature_List, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Feature_List, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feature_List, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Feature_List_group = lv_obj_create(ui_Feature_List);
    lv_obj_set_width(ui_Feature_List_group, lv_pct(100));
    lv_obj_set_height(ui_Feature_List_group, lv_pct(100));
    lv_obj_set_align(ui_Feature_List_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Feature_List_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Feature_List_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Feature_List_group, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Feature_List_group, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Feature_List_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feature_List_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Feature_List_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Feature_List_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Feature_List_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Feature_group = lv_obj_create(ui_Feature_List_group);
    lv_obj_set_width(ui_Feature_group, lv_pct(100));
    lv_obj_set_height(ui_Feature_group, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Feature_group, -15);
    lv_obj_set_y(ui_Feature_group, 88);
    lv_obj_set_align(ui_Feature_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Feature_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Feature_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Feature_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Feature_group, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Feature_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Feature_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Feature_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Feature_group, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Feature_group, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Exercise_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_Exercise_group, 0);
    lv_obj_set_y(ui_Exercise_group, -155);

    lv_image_set_src(ui_comp_get_child(ui_Exercise_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_movement_icon);

    ui_Sports_record = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_Sports_record, 0);
    lv_obj_set_y(ui_Sports_record, -156);

    lv_image_set_src(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_sports_record_icon);

    lv_obj_set_x(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), -1);
    lv_label_set_long_mode(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT),
                           LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Sports \nRecords");
    lv_obj_set_style_text_letter_space(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 1,
                                       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_comp_get_child(ui_Sports_record, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 3,
                                     LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Activity_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_Activity_group, 0);
    lv_obj_set_y(ui_Activity_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_Activity_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_activity_icon);

    lv_label_set_text(ui_comp_get_child(ui_Activity_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Activity Center");

    ui_Heart_rate_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_Heart_rate_group, -49);
    lv_obj_set_y(ui_Heart_rate_group, -384);

    lv_image_set_src(ui_comp_get_child(ui_Heart_rate_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_heart_rate_icon);

    lv_label_set_text(ui_comp_get_child(ui_Heart_rate_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Heart Rate");

    ui_SpO2_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_SpO2_group, 0);
    lv_obj_set_y(ui_SpO2_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_SpO2_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_spo2_icon);

    lv_label_set_text(ui_comp_get_child(ui_SpO2_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "SpO2");

    ui_sleep_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_sleep_group, 0);
    lv_obj_set_y(ui_sleep_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_sleep_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_sleep_icon);

    lv_label_set_text(ui_comp_get_child(ui_sleep_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Sleep");

    ui_stresses_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_stresses_group, 0);
    lv_obj_set_y(ui_stresses_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_stresses_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_stresses_icon);

    lv_label_set_text(ui_comp_get_child(ui_stresses_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Stresses");

    ui_surveying_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_surveying_group, 0);
    lv_obj_set_y(ui_surveying_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_surveying_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_surveying_icon);

    lv_obj_set_x(ui_comp_get_child(ui_surveying_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_surveying_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_surveying_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "One-click \nMeasurement");

    ui_physiology_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_physiology_group, 0);
    lv_obj_set_y(ui_physiology_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_physiology_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_physiology_icon);

    lv_obj_set_x(ui_comp_get_child(ui_physiology_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_physiology_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_physiology_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Physiological \nPeriod");

    ui_card_bag_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_card_bag_group, 0);
    lv_obj_set_y(ui_card_bag_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_card_bag_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_card_bag_icon);

    lv_label_set_text(ui_comp_get_child(ui_card_bag_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Card Bag");

    ui_contacts_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_contacts_group, 0);
    lv_obj_set_y(ui_contacts_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_contacts_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_contacts_icon);

    lv_label_set_text(ui_comp_get_child(ui_contacts_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Contacts");

    ui_telephones_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_telephones_group, 0);
    lv_obj_set_y(ui_telephones_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_telephones_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_telephones_icon);

    lv_label_set_text(ui_comp_get_child(ui_telephones_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Call Record");

    ui_climatic_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_climatic_group, 0);
    lv_obj_set_y(ui_climatic_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_climatic_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_climatic_icon);

    lv_label_set_text(ui_comp_get_child(ui_climatic_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Climatic");

    ui_breathe_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_breathe_group, 0);
    lv_obj_set_y(ui_breathe_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_breathe_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_breathe_icon);

    lv_obj_set_x(ui_comp_get_child(ui_breathe_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_breathe_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_breathe_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Breathing \nTraining");

    ui_alipay = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_alipay, 0);
    lv_obj_set_y(ui_alipay, -156);

    lv_image_set_src(ui_comp_get_child(ui_alipay, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_alipay_icon);

    lv_label_set_text(ui_comp_get_child(ui_alipay, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Alipay");

    ui_wechat_pay_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_wechat_pay_group, 0);
    lv_obj_set_y(ui_wechat_pay_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_wechat_pay_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_wechat_pay_icon);

    lv_label_set_text(ui_comp_get_child(ui_wechat_pay_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "WeChat Pay");

    ui_music_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_music_group, 0);
    lv_obj_set_y(ui_music_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_music_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_music_icon);

    lv_label_set_text(ui_comp_get_child(ui_music_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Music");

    ui_cameras_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_cameras_group, 0);
    lv_obj_set_y(ui_cameras_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_cameras_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_cameras_icon);

    lv_obj_set_x(ui_comp_get_child(ui_cameras_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_cameras_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_cameras_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Remote \nControl Photo");

    ui_drink_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_drink_group, 0);
    lv_obj_set_y(ui_drink_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_drink_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_drink_icon);

    lv_label_set_text(ui_comp_get_child(ui_drink_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Drinker");

    ui_alarm_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_alarm_group, 0);
    lv_obj_set_y(ui_alarm_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_alarm_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_alarm_icon);

    lv_label_set_text(ui_comp_get_child(ui_alarm_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Alarm");

    ui_stopwatch_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_stopwatch_group, 0);
    lv_obj_set_y(ui_stopwatch_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_stopwatch_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_stopwatch_icon);

    lv_label_set_text(ui_comp_get_child(ui_stopwatch_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Stopwatch");

    ui_count_down_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_count_down_group, 0);
    lv_obj_set_y(ui_count_down_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_count_down_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_count_down_icon);

    lv_label_set_text(ui_comp_get_child(ui_count_down_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Count Down");

    ui_counter_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_counter_group, 0);
    lv_obj_set_y(ui_counter_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_counter_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_counter_icon);

    lv_label_set_text(ui_comp_get_child(ui_counter_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Calculators");

    ui_record_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_record_group, 0);
    lv_obj_set_y(ui_record_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_record_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_record_icon);

    lv_label_set_text(ui_comp_get_child(ui_record_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Audio Memo");

    ui_compass_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_compass_group, 0);
    lv_obj_set_y(ui_compass_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_compass_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_compass_icon);

    lv_label_set_text(ui_comp_get_child(ui_compass_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Compass");

    ui_torch_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_torch_group, 0);
    lv_obj_set_y(ui_torch_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_torch_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_torch_icon);

    lv_obj_set_x(ui_comp_get_child(ui_torch_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_torch_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_torch_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Clectric \nHand Torch");

    ui_find_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_find_group, 0);
    lv_obj_set_y(ui_find_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_find_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_find_icon);

    lv_obj_set_x(ui_comp_get_child(ui_find_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 120);
    lv_obj_set_y(ui_comp_get_child(ui_find_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), 0);
    lv_label_set_text(ui_comp_get_child(ui_find_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Find a \ncell phone");

    ui_setting_group = ui_Feature_group_create(ui_Feature_group);
    lv_obj_set_x(ui_setting_group, 0);
    lv_obj_set_y(ui_setting_group, -156);

    lv_image_set_src(ui_comp_get_child(ui_setting_group, UI_COMP_FEATURE_GROUP_MOVEMENT_ICON),
                     &func_list_setting_icon);

    lv_label_set_text(ui_comp_get_child(ui_setting_group, UI_COMP_FEATURE_GROUP_EXERCISE_TXT), "Setting");

    ui_Bar4 = lv_bar_create(ui_Feature_List);
    lv_bar_set_value(ui_Bar4, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 10);
    lv_obj_set_height(ui_Bar4, 120);
    lv_obj_set_x(ui_Bar4, 194);
    lv_obj_set_y(ui_Bar4, 0);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bar4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Bar4, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar4,
                                                                                           lv_obj_get_style_pad_right(ui_Bar4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Exercise_group, ui_event_Exercise_group_Feature_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sports_record, ui_event_Sports_record_Feature_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting_group, ui_event_setting_group_Feature_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Feature_List, ui_event_Feature_List, LV_EVENT_ALL, NULL);
    uic_Exercise_group = ui_Exercise_group;

}

void ui_Feature_List_screen_destroy(void)
{
    if(ui_Feature_List) lv_obj_del(ui_Feature_List);

    // NULL screen variables
    ui_Feature_List = NULL;
    ui_Feature_List_group = NULL;
    ui_Feature_group = NULL;
    uic_Exercise_group = NULL;
    ui_Exercise_group = NULL;
    ui_Sports_record = NULL;
    ui_Activity_group = NULL;
    ui_Heart_rate_group = NULL;
    ui_SpO2_group = NULL;
    ui_sleep_group = NULL;
    ui_stresses_group = NULL;
    ui_surveying_group = NULL;
    ui_physiology_group = NULL;
    ui_card_bag_group = NULL;
    ui_contacts_group = NULL;
    ui_telephones_group = NULL;
    ui_climatic_group = NULL;
    ui_breathe_group = NULL;
    ui_alipay = NULL;
    ui_wechat_pay_group = NULL;
    ui_music_group = NULL;
    ui_cameras_group = NULL;
    ui_drink_group = NULL;
    ui_alarm_group = NULL;
    ui_stopwatch_group = NULL;
    ui_count_down_group = NULL;
    ui_counter_group = NULL;
    ui_record_group = NULL;
    ui_compass_group = NULL;
    ui_torch_group = NULL;
    ui_find_group = NULL;
    ui_setting_group = NULL;
    ui_Bar4 = NULL;

}
