// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_GOAL_H
#define UI_GOAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Goal
extern void ui_Goal_screen_init(void);
extern void ui_Goal_screen_destroy(void);
extern lv_obj_t * ui_Goal;
extern lv_obj_t * ui_Campaign_List_group2;
extern void ui_event_Primarystatusbar2_Primary_status_bar(lv_event_t * e);
extern lv_obj_t * ui_Primarystatusbar2;
extern lv_obj_t * ui_Setting_group1;
extern void ui_event_goal_group1_Setting_group(lv_event_t * e);
extern lv_obj_t * ui_goal_group1;
extern void ui_event_Aimless_group2_Setting_group(lv_event_t * e);
extern lv_obj_t * ui_Aimless_group2;
extern void ui_event_calorimetric_group3_Setting_group(lv_event_t * e);
extern lv_obj_t * ui_calorimetric_group3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

