// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_INTERVAL_TIME_H
#define UI_INTERVAL_TIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Interval_Time
extern void ui_Interval_Time_screen_init(void);
extern void ui_Interval_Time_screen_destroy(void);
extern void ui_event_Interval_Time(lv_event_t * e);
extern lv_obj_t * ui_Interval_Time;
extern lv_obj_t * ui_setting_group3;
extern lv_obj_t * ui_Primarystatusbar15;
extern lv_obj_t * ui_setting_group4;
extern lv_obj_t * ui_dialgroup14;
extern lv_obj_t * ui_lin_1;
extern lv_obj_t * ui_dial_txt_group2;
extern lv_obj_t * ui_dial_txt3;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_dialgroup15;
extern lv_obj_t * ui_lin_5;
extern lv_obj_t * ui_dial_txt_group4;
extern lv_obj_t * ui_dial_txt5;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_dialgroup16;
extern lv_obj_t * ui_lin_6;
extern lv_obj_t * ui_dial_txt_group5;
extern lv_obj_t * ui_dial_txt6;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_dialgroup17;
extern lv_obj_t * ui_dial_txt_group6;
extern lv_obj_t * ui_dial_txt7;
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

