// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Indoor_Run_data_;
lv_obj_t * ui_Campaign_List_group8;
lv_obj_t * ui_Primarystatusbar8;
lv_obj_t * ui_indoor_run_time;
lv_obj_t * ui_time_date;
lv_obj_t * ui_Functional_data_group;
lv_obj_t * ui_indoor_hr_group;
lv_obj_t * ui_indoor_kcal_group;
lv_obj_t * ui_indoor_gap_group;
lv_obj_t * ui_indoor_step_group;
lv_obj_t * ui_indoor_pace_group;
lv_obj_t * ui_indoor_gearing_group;
lv_obj_t * ui_bar;
lv_obj_t * ui_bar_icon_01;
lv_obj_t * ui_bar_icon_02;
lv_obj_t * ui_bar_icon_03;

// event funtions
void ui_event_Indoor_Run_data_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Campaign_Pause, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Campaign_Pause_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Music, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Music_screen_init);
    }
}

// build funtions

void ui_Indoor_Run_data__screen_init(void)
{
    ui_Indoor_Run_data_ = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Indoor_Run_data_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Indoor_Run_data_, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Indoor_Run_data_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Indoor_Run_data_, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Indoor_Run_data_, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group8 = lv_obj_create(ui_Indoor_Run_data_);
    lv_obj_set_width(ui_Campaign_List_group8, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group8, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group8, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Campaign_List_group8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Campaign_List_group8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar8 = ui_Primary_status_bar_create(ui_Indoor_Run_data_);
    lv_obj_set_x(ui_Primarystatusbar8, 0);
    lv_obj_set_y(ui_Primarystatusbar8, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar8, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Indoor Run");

    ui_indoor_run_time = lv_obj_create(ui_Indoor_Run_data_);
    lv_obj_set_width(ui_indoor_run_time, 360);
    lv_obj_set_height(ui_indoor_run_time, 60);
    lv_obj_set_x(ui_indoor_run_time, 25);
    lv_obj_set_y(ui_indoor_run_time, 80);
    lv_obj_remove_flag(ui_indoor_run_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_indoor_run_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_indoor_run_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_indoor_run_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_indoor_run_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_date = lv_label_create(ui_indoor_run_time);
    lv_obj_set_width(ui_time_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time_date, -12);
    lv_obj_set_y(ui_time_date, -13);
    lv_label_set_text(ui_time_date, "00:21:51");
    lv_obj_set_style_text_color(ui_time_date, lv_color_hex(0xFEF63F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_date, &ui_font_HONOR_M_56, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Functional_data_group = lv_obj_create(ui_Indoor_Run_data_);
    lv_obj_set_width(ui_Functional_data_group, 410);
    lv_obj_set_height(ui_Functional_data_group, 250);
    lv_obj_set_x(ui_Functional_data_group, 0);
    lv_obj_set_y(ui_Functional_data_group, 35);
    lv_obj_set_align(ui_Functional_data_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Functional_data_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Functional_data_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Functional_data_group, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Functional_data_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Functional_data_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Functional_data_group, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Functional_data_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_hr_group = ui_indoorgroup_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_hr_group, 0);
    lv_obj_set_y(ui_indoor_hr_group, 76);

    lv_obj_set_x(ui_comp_get_child(ui_indoor_hr_group, UI_COMP_INDOORGROUP_LABEL101), -12);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_hr_group, UI_COMP_INDOORGROUP_LABEL101), -13);

    lv_image_set_src(ui_comp_get_child(ui_indoor_hr_group, UI_COMP_INDOORGROUP_IMAGE20),
                     &campaign_list_move_hr_icon1);
    lv_obj_set_x(ui_comp_get_child(ui_indoor_hr_group, UI_COMP_INDOORGROUP_IMAGE20), 33);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_hr_group, UI_COMP_INDOORGROUP_IMAGE20), -3);

    ui_indoor_kcal_group = ui_indoorgroup_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_kcal_group, 0);
    lv_obj_set_y(ui_indoor_kcal_group, 76);

    lv_obj_set_x(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_LABEL101), -12);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_LABEL101), -13);
    lv_label_set_text(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_LABEL101), "396 Kcal");

    lv_image_set_src(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_IMAGE20),
                     &campaign_list_move_kcal_icon);
    lv_obj_set_x(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_IMAGE20), 40);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_kcal_group, UI_COMP_INDOORGROUP_IMAGE20), -3);

    ui_indoor_gap_group = ui_indoorgroup3_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_gap_group, 0);
    lv_obj_set_y(ui_indoor_gap_group, 76);

    ui_indoor_step_group = ui_indoorgroup3_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_step_group, 0);
    lv_obj_set_y(ui_indoor_step_group, 76);

    lv_obj_set_x(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL99), -12);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL99), -13);
    lv_label_set_text(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL99), "8000");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL100), 113);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL100), -17);
    lv_label_set_text(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL100), "Steps");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL103), 113);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL103), 11);
    lv_label_set_text(ui_comp_get_child(ui_indoor_step_group, UI_COMP_INDOORGROUP3_LABEL103), "step");

    ui_indoor_pace_group = ui_indoorgroup3_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_pace_group, 0);
    lv_obj_set_y(ui_indoor_pace_group, 76);

    lv_label_set_text(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL99), "250");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL100), 85);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL100), -17);
    lv_label_set_text(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL100), "Pace");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL103), 85);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL103), 11);
    lv_label_set_text(ui_comp_get_child(ui_indoor_pace_group, UI_COMP_INDOORGROUP3_LABEL103), "/min");

    ui_indoor_gearing_group = ui_indoorgroup3_create(ui_Functional_data_group);
    lv_obj_set_x(ui_indoor_gearing_group, 0);
    lv_obj_set_y(ui_indoor_gearing_group, 76);

    lv_label_set_text(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL99), "15'52\"");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL100), 130);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL100), -17);
    lv_label_set_text(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL100), "Gearing");

    lv_obj_set_x(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL103), 130);
    lv_obj_set_y(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL103), 11);
    lv_label_set_text(ui_comp_get_child(ui_indoor_gearing_group, UI_COMP_INDOORGROUP3_LABEL103), "/km");

    ui_bar = lv_obj_create(ui_Indoor_Run_data_);
    lv_obj_set_width(ui_bar, 45);
    lv_obj_set_height(ui_bar, 10);
    lv_obj_set_x(ui_bar, 0);
    lv_obj_set_y(ui_bar, 235);
    lv_obj_set_align(ui_bar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar, lv_color_hex(0xAB8080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_01 = lv_obj_create(ui_bar);
    lv_obj_set_width(ui_bar_icon_01, 8);
    lv_obj_set_height(ui_bar_icon_01, 8);
    lv_obj_set_x(ui_bar_icon_01, -16);
    lv_obj_set_y(ui_bar_icon_01, 0);
    lv_obj_set_align(ui_bar_icon_01, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_01, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_01, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_01, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_02 = lv_obj_create(ui_bar);
    lv_obj_set_width(ui_bar_icon_02, 8);
    lv_obj_set_height(ui_bar_icon_02, 8);
    lv_obj_set_align(ui_bar_icon_02, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_02, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_02, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_02, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_03 = lv_obj_create(ui_bar);
    lv_obj_set_width(ui_bar_icon_03, 8);
    lv_obj_set_height(ui_bar_icon_03, 8);
    lv_obj_set_x(ui_bar_icon_03, 16);
    lv_obj_set_y(ui_bar_icon_03, 0);
    lv_obj_set_align(ui_bar_icon_03, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_03, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_03, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_03, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_03, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Indoor_Run_data_, ui_event_Indoor_Run_data_, LV_EVENT_ALL, NULL);

}

void ui_Indoor_Run_data__screen_destroy(void)
{
    if(ui_Indoor_Run_data_) lv_obj_del(ui_Indoor_Run_data_);

    // NULL screen variables
    ui_Indoor_Run_data_ = NULL;
    ui_Campaign_List_group8 = NULL;
    ui_Primarystatusbar8 = NULL;
    ui_indoor_run_time = NULL;
    ui_time_date = NULL;
    ui_Functional_data_group = NULL;
    ui_indoor_hr_group = NULL;
    ui_indoor_kcal_group = NULL;
    ui_indoor_gap_group = NULL;
    ui_indoor_step_group = NULL;
    ui_indoor_pace_group = NULL;
    ui_indoor_gearing_group = NULL;
    ui_bar = NULL;
    ui_bar_icon_01 = NULL;
    ui_bar_icon_02 = NULL;
    ui_bar_icon_03 = NULL;

}
