// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_INTERVAL_ALERT_H
#define UI_INTERVAL_ALERT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_interval_alert
extern void ui_interval_alert_screen_init(void);
extern void ui_interval_alert_screen_destroy(void);
extern lv_obj_t * ui_interval_alert;
extern lv_obj_t * ui_Campaign_List_group3;
extern lv_obj_t * ui_Primarystatusbar5;
extern lv_obj_t * ui_Setting_group2;
extern void ui_event_goal_group2_Setting_group(lv_event_t * e);
extern lv_obj_t * ui_goal_group2;
extern void ui_event_Aimless_group3_Setting_group(lv_event_t * e);
extern lv_obj_t * ui_Aimless_group3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

