// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Indoor_Run;
lv_obj_t * ui_Campaign_List_group6;
lv_obj_t * ui_Primarystatusbar7;
lv_obj_t * ui_indoor_run_icon_184;
lv_obj_t * ui_ready_txt;
lv_obj_t * ui_indoor_run_group;
lv_obj_t * ui_indoor_run_hr_icon;
lv_obj_t * ui_indoor_run_date;

// event funtions
void ui_event_Indoor_Run(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Campaign_List, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Campaign_List_screen_init);
    }
}

void ui_event_Campaign_List_group6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Campaign_Countdown, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Campaign_Countdown_screen_init);
    }
}

void ui_event_indoor_run_icon_184(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_Countdown, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Campaign_Countdown_screen_init);
    }
}

void ui_event_ready_txt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_Countdown, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Campaign_Countdown_screen_init);
    }
}

// build funtions

void ui_Indoor_Run_screen_init(void)
{
    ui_Indoor_Run = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Indoor_Run, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Indoor_Run, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Indoor_Run, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group6 = lv_obj_create(ui_Indoor_Run);
    lv_obj_set_width(ui_Campaign_List_group6, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group6, lv_pct(100));
    lv_obj_set_x(ui_Campaign_List_group6, 0);
    lv_obj_set_y(ui_Campaign_List_group6, -2);
    lv_obj_set_align(ui_Campaign_List_group6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group6, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Campaign_List_group6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar7 = ui_Primary_status_bar_create(ui_Indoor_Run);
    lv_obj_set_x(ui_Primarystatusbar7, 0);
    lv_obj_set_y(ui_Primarystatusbar7, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar7, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Indoor Run");

    ui_indoor_run_icon_184 = lv_image_create(ui_Indoor_Run);
    lv_image_set_src(ui_indoor_run_icon_184, &campaign_list_indoor_run_icon184);
    lv_obj_set_width(ui_indoor_run_icon_184, LV_SIZE_CONTENT);   /// 184
    lv_obj_set_height(ui_indoor_run_icon_184, LV_SIZE_CONTENT);    /// 184
    lv_obj_set_x(ui_indoor_run_icon_184, 0);
    lv_obj_set_y(ui_indoor_run_icon_184, -60);
    lv_obj_set_align(ui_indoor_run_icon_184, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indoor_run_icon_184, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_indoor_run_icon_184, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ready_txt = lv_label_create(ui_Indoor_Run);
    lv_obj_set_width(ui_ready_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ready_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ready_txt, 0);
    lv_obj_set_y(ui_ready_txt, 90);
    lv_obj_set_align(ui_ready_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ready_txt, "         Ready to go\nClick to start exercising");
    lv_obj_remove_flag(ui_ready_txt, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_align(ui_ready_txt, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ready_txt, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_group = lv_obj_create(ui_Indoor_Run);
    lv_obj_set_width(ui_indoor_run_group, 120);
    lv_obj_set_height(ui_indoor_run_group, 50);
    lv_obj_set_x(ui_indoor_run_group, 0);
    lv_obj_set_y(ui_indoor_run_group, 180);
    lv_obj_set_align(ui_indoor_run_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_indoor_run_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_indoor_run_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_indoor_run_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_indoor_run_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_indoor_run_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_hr_icon = lv_image_create(ui_indoor_run_group);
    lv_image_set_src(ui_indoor_run_hr_icon, &campaign_list_move_hr_icon);
    lv_obj_set_width(ui_indoor_run_hr_icon, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_indoor_run_hr_icon, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_indoor_run_hr_icon, -20);
    lv_obj_set_y(ui_indoor_run_hr_icon, 0);
    lv_obj_set_align(ui_indoor_run_hr_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indoor_run_hr_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_indoor_run_hr_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indoor_run_date = lv_label_create(ui_indoor_run_group);
    lv_obj_set_width(ui_indoor_run_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor_run_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor_run_date, 40);
    lv_obj_set_y(ui_indoor_run_date, -7);
    lv_label_set_text(ui_indoor_run_date, "88");
    lv_obj_set_style_text_font(ui_indoor_run_date, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Campaign_List_group6, ui_event_Campaign_List_group6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_indoor_run_icon_184, ui_event_indoor_run_icon_184, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ready_txt, ui_event_ready_txt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Indoor_Run, ui_event_Indoor_Run, LV_EVENT_ALL, NULL);

}

void ui_Indoor_Run_screen_destroy(void)
{
    if(ui_Indoor_Run) lv_obj_del(ui_Indoor_Run);

    // NULL screen variables
    ui_Indoor_Run = NULL;
    ui_Campaign_List_group6 = NULL;
    ui_Primarystatusbar7 = NULL;
    ui_indoor_run_icon_184 = NULL;
    ui_ready_txt = NULL;
    ui_indoor_run_group = NULL;
    ui_indoor_run_hr_icon = NULL;
    ui_indoor_run_date = NULL;

}
