// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_INDOOR_RUN_DATA__H
#define UI_INDOOR_RUN_DATA__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Indoor_Run_data_
extern void ui_Indoor_Run_data__screen_init(void);
extern void ui_Indoor_Run_data__screen_destroy(void);
extern void ui_event_Indoor_Run_data_(lv_event_t * e);
extern lv_obj_t * ui_Indoor_Run_data_;
extern lv_obj_t * ui_Campaign_List_group8;
extern lv_obj_t * ui_Primarystatusbar8;
extern lv_obj_t * ui_indoor_run_time;
extern lv_obj_t * ui_time_date;
extern lv_obj_t * ui_Functional_data_group;
extern lv_obj_t * ui_indoor_hr_group;
extern lv_obj_t * ui_indoor_kcal_group;
extern lv_obj_t * ui_indoor_gap_group;
extern lv_obj_t * ui_indoor_step_group;
extern lv_obj_t * ui_indoor_pace_group;
extern lv_obj_t * ui_indoor_gearing_group;
extern lv_obj_t * ui_bar;
extern lv_obj_t * ui_bar_icon_01;
extern lv_obj_t * ui_bar_icon_02;
extern lv_obj_t * ui_bar_icon_03;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

