// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_INDOOR_RUN_H
#define UI_INDOOR_RUN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Indoor_Run
extern void ui_Indoor_Run_screen_init(void);
extern void ui_Indoor_Run_screen_destroy(void);
extern void ui_event_Indoor_Run(lv_event_t * e);
extern lv_obj_t * ui_Indoor_Run;
extern void ui_event_Campaign_List_group6(lv_event_t * e);
extern lv_obj_t * ui_Campaign_List_group6;
extern lv_obj_t * ui_Primarystatusbar7;
extern void ui_event_indoor_run_icon_184(lv_event_t * e);
extern lv_obj_t * ui_indoor_run_icon_184;
extern void ui_event_ready_txt(lv_event_t * e);
extern lv_obj_t * ui_ready_txt;
extern lv_obj_t * ui_indoor_run_group;
extern lv_obj_t * ui_indoor_run_hr_icon;
extern lv_obj_t * ui_indoor_run_date;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

