// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Interval_Time;
lv_obj_t * ui_setting_group3;
lv_obj_t * ui_Primarystatusbar15;
lv_obj_t * ui_setting_group4;
lv_obj_t * ui_dialgroup14;
lv_obj_t * ui_lin_1;
lv_obj_t * ui_dial_txt_group2;
lv_obj_t * ui_dial_txt3;
lv_obj_t * ui_Button12;
lv_obj_t * ui_dialgroup15;
lv_obj_t * ui_lin_5;
lv_obj_t * ui_dial_txt_group4;
lv_obj_t * ui_dial_txt5;
lv_obj_t * ui_Button3;
lv_obj_t * ui_dialgroup16;
lv_obj_t * ui_lin_6;
lv_obj_t * ui_dial_txt_group5;
lv_obj_t * ui_dial_txt6;
lv_obj_t * ui_Button4;
lv_obj_t * ui_dialgroup17;
lv_obj_t * ui_dial_txt_group6;
lv_obj_t * ui_dial_txt7;
lv_obj_t * ui_Button5;

// event funtions
void ui_event_Interval_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Display_Brightness, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Display_Brightness_screen_init);
    }
}

// build funtions

void ui_Interval_Time_screen_init(void)
{
    ui_Interval_Time = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Interval_Time, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_Interval_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Interval_Time, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Interval_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Interval_Time, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Interval_Time, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_setting_group3 = lv_obj_create(ui_Interval_Time);
    lv_obj_set_width(ui_setting_group3, lv_pct(100));
    lv_obj_set_height(ui_setting_group3, lv_pct(100));
    lv_obj_set_align(ui_setting_group3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting_group3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_group3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_setting_group3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_setting_group3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setting_group3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_group3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting_group3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_setting_group3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_setting_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar15 = ui_Primary_status_bar_create(ui_Interval_Time);
    lv_obj_set_x(ui_Primarystatusbar15, 0);
    lv_obj_set_y(ui_Primarystatusbar15, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar15, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Interval Time");

    ui_setting_group4 = lv_obj_create(ui_Interval_Time);
    lv_obj_set_width(ui_setting_group4, 410);
    lv_obj_set_height(ui_setting_group4, 426);
    lv_obj_set_x(ui_setting_group4, 0);
    lv_obj_set_y(ui_setting_group4, 32);
    lv_obj_set_align(ui_setting_group4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting_group4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_group4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_setting_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_setting_group4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_setting_group4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setting_group4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_group4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting_group4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_setting_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_setting_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_setting_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_setting_group4, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_setting_group4, -8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_setting_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialgroup14 = lv_obj_create(ui_setting_group4);
    lv_obj_set_width(ui_dialgroup14, 410);
    lv_obj_set_height(ui_dialgroup14, 100);
    lv_obj_set_x(ui_dialgroup14, -5);
    lv_obj_set_y(ui_dialgroup14, -51);
    lv_obj_set_align(ui_dialgroup14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dialgroup14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialgroup14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialgroup14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialgroup14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_dialgroup14, &setting_rectangle_39_1,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialgroup14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialgroup14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lin_1 = lv_obj_create(ui_dialgroup14);
    lv_obj_set_width(ui_lin_1, 382);
    lv_obj_set_height(ui_lin_1, 2);
    lv_obj_set_x(ui_lin_1, 0);
    lv_obj_set_y(ui_lin_1, 14);
    lv_obj_set_align(ui_lin_1, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_lin_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lin_1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lin_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lin_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lin_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt_group2 = lv_obj_create(ui_dialgroup14);
    lv_obj_set_width(ui_dial_txt_group2, 280);
    lv_obj_set_height(ui_dial_txt_group2, 50);
    lv_obj_set_align(ui_dial_txt_group2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dial_txt_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dial_txt_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dial_txt_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dial_txt_group2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dial_txt_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt3 = lv_label_create(ui_dial_txt_group2);
    lv_obj_set_width(ui_dial_txt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dial_txt3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dial_txt3, -3);
    lv_obj_set_y(ui_dial_txt3, -9);
    lv_label_set_long_mode(ui_dial_txt3, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_dial_txt3, "5 Seconds");
    lv_obj_set_style_text_align(ui_dial_txt3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dial_txt3, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_button_create(ui_dialgroup14);
    lv_obj_set_width(ui_Button12, 36);
    lv_obj_set_height(ui_Button12, 36);
    lv_obj_set_x(ui_Button12, -156);
    lv_obj_set_y(ui_Button12, -1);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button12, &setting_single_choice,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_src(ui_Button12, &setting_single_choice_1,
                                  LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor(ui_Button12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_dialgroup15 = lv_obj_create(ui_setting_group4);
    lv_obj_set_width(ui_dialgroup15, 410);
    lv_obj_set_height(ui_dialgroup15, 100);
    lv_obj_set_x(ui_dialgroup15, -5);
    lv_obj_set_y(ui_dialgroup15, -51);
    lv_obj_set_align(ui_dialgroup15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dialgroup15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialgroup15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialgroup15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialgroup15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_dialgroup15, &setting_rectangle_39_2,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialgroup15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialgroup15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lin_5 = lv_obj_create(ui_dialgroup15);
    lv_obj_set_width(ui_lin_5, 382);
    lv_obj_set_height(ui_lin_5, 2);
    lv_obj_set_x(ui_lin_5, 0);
    lv_obj_set_y(ui_lin_5, 14);
    lv_obj_set_align(ui_lin_5, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_lin_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lin_5, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lin_5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lin_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lin_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt_group4 = lv_obj_create(ui_dialgroup15);
    lv_obj_set_width(ui_dial_txt_group4, 280);
    lv_obj_set_height(ui_dial_txt_group4, 50);
    lv_obj_set_align(ui_dial_txt_group4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dial_txt_group4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dial_txt_group4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dial_txt_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dial_txt_group4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dial_txt_group4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt5 = lv_label_create(ui_dial_txt_group4);
    lv_obj_set_width(ui_dial_txt5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dial_txt5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dial_txt5, -3);
    lv_obj_set_y(ui_dial_txt5, -9);
    lv_label_set_long_mode(ui_dial_txt5, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_dial_txt5, "10 Seconds");
    lv_obj_set_style_text_align(ui_dial_txt5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dial_txt5, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_dialgroup15);
    lv_obj_set_width(ui_Button3, 36);
    lv_obj_set_height(ui_Button3, 36);
    lv_obj_set_x(ui_Button3, -156);
    lv_obj_set_y(ui_Button3, -1);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button3, &setting_single_choice,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_src(ui_Button3, &setting_single_choice_1,
                                  LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_dialgroup16 = lv_obj_create(ui_setting_group4);
    lv_obj_set_width(ui_dialgroup16, 410);
    lv_obj_set_height(ui_dialgroup16, 100);
    lv_obj_set_x(ui_dialgroup16, -5);
    lv_obj_set_y(ui_dialgroup16, -51);
    lv_obj_set_align(ui_dialgroup16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dialgroup16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialgroup16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialgroup16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialgroup16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_dialgroup16, &setting_rectangle_39_2,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialgroup16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialgroup16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lin_6 = lv_obj_create(ui_dialgroup16);
    lv_obj_set_width(ui_lin_6, 382);
    lv_obj_set_height(ui_lin_6, 2);
    lv_obj_set_x(ui_lin_6, 0);
    lv_obj_set_y(ui_lin_6, 14);
    lv_obj_set_align(ui_lin_6, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_lin_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_lin_6, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lin_6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lin_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lin_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt_group5 = lv_obj_create(ui_dialgroup16);
    lv_obj_set_width(ui_dial_txt_group5, 280);
    lv_obj_set_height(ui_dial_txt_group5, 50);
    lv_obj_set_align(ui_dial_txt_group5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dial_txt_group5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dial_txt_group5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dial_txt_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dial_txt_group5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dial_txt_group5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt6 = lv_label_create(ui_dial_txt_group5);
    lv_obj_set_width(ui_dial_txt6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dial_txt6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dial_txt6, -3);
    lv_obj_set_y(ui_dial_txt6, -9);
    lv_label_set_long_mode(ui_dial_txt6, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_dial_txt6, "15 Seconds");
    lv_obj_set_style_text_align(ui_dial_txt6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dial_txt6, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_dialgroup16);
    lv_obj_set_width(ui_Button4, 36);
    lv_obj_set_height(ui_Button4, 36);
    lv_obj_set_x(ui_Button4, -156);
    lv_obj_set_y(ui_Button4, -1);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button4, &setting_single_choice,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_src(ui_Button4, &setting_single_choice_1,
                                  LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_dialgroup17 = lv_obj_create(ui_setting_group4);
    lv_obj_set_width(ui_dialgroup17, 410);
    lv_obj_set_height(ui_dialgroup17, 100);
    lv_obj_set_x(ui_dialgroup17, -5);
    lv_obj_set_y(ui_dialgroup17, -51);
    lv_obj_set_align(ui_dialgroup17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dialgroup17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialgroup17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialgroup17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialgroup17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_dialgroup17, &setting_rectangle_39,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialgroup17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialgroup17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt_group6 = lv_obj_create(ui_dialgroup17);
    lv_obj_set_width(ui_dial_txt_group6, 280);
    lv_obj_set_height(ui_dial_txt_group6, 50);
    lv_obj_set_align(ui_dial_txt_group6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dial_txt_group6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dial_txt_group6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dial_txt_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dial_txt_group6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dial_txt_group6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dial_txt7 = lv_label_create(ui_dial_txt_group6);
    lv_obj_set_width(ui_dial_txt7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dial_txt7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dial_txt7, -3);
    lv_obj_set_y(ui_dial_txt7, -9);
    lv_label_set_long_mode(ui_dial_txt7, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_dial_txt7, "20 Seconds");
    lv_obj_set_style_text_align(ui_dial_txt7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dial_txt7, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_dialgroup17);
    lv_obj_set_width(ui_Button5, 36);
    lv_obj_set_height(ui_Button5, 36);
    lv_obj_set_x(ui_Button5, -156);
    lv_obj_set_y(ui_Button5, -1);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button5, &setting_single_choice,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_src(ui_Button5, &setting_single_choice_1,
                                  LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_Interval_Time, ui_event_Interval_Time, LV_EVENT_ALL, NULL);

}

void ui_Interval_Time_screen_destroy(void)
{
    if(ui_Interval_Time) lv_obj_del(ui_Interval_Time);

    // NULL screen variables
    ui_Interval_Time = NULL;
    ui_setting_group3 = NULL;
    ui_Primarystatusbar15 = NULL;
    ui_setting_group4 = NULL;
    ui_dialgroup14 = NULL;
    ui_lin_1 = NULL;
    ui_dial_txt_group2 = NULL;
    ui_dial_txt3 = NULL;
    ui_Button12 = NULL;
    ui_dialgroup15 = NULL;
    ui_lin_5 = NULL;
    ui_dial_txt_group4 = NULL;
    ui_dial_txt5 = NULL;
    ui_Button3 = NULL;
    ui_dialgroup16 = NULL;
    ui_lin_6 = NULL;
    ui_dial_txt_group5 = NULL;
    ui_dial_txt6 = NULL;
    ui_Button4 = NULL;
    ui_dialgroup17 = NULL;
    ui_dial_txt_group6 = NULL;
    ui_dial_txt7 = NULL;
    ui_Button5 = NULL;

}
