// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_MUSIC_H
#define UI_MUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music
extern void ui_Music_screen_init(void);
extern void ui_Music_screen_destroy(void);
extern void ui_event_Music(lv_event_t * e);
extern lv_obj_t * ui_Music;
extern lv_obj_t * ui_Campaign_List_group10;
extern lv_obj_t * ui_Primarystatusbar10;
extern lv_obj_t * ui_bar2;
extern lv_obj_t * ui_bar_icon_4;
extern lv_obj_t * ui_bar_icon_5;
extern lv_obj_t * ui_bar_icon_6;
extern lv_obj_t * ui_music_mobile;
extern lv_obj_t * ui_music_Lyrics;
extern lv_obj_t * ui_music_Lyrics_txt;
extern lv_obj_t * ui_music_Singer;
extern lv_obj_t * ui_music_Singer_txt;
extern lv_obj_t * ui_music_middle;
extern lv_obj_t * ui_music_middle_icon;
extern lv_obj_t * ui_music_bg;
extern void ui_event_music_sound(lv_event_t * e);
extern lv_obj_t * ui_music_sound;
extern lv_obj_t * ui_music_sound_icon;
extern void ui_event_music_sound_01(lv_event_t * e);
extern lv_obj_t * ui_music_sound_01;
extern lv_obj_t * ui_music_sound_icon01;
extern lv_obj_t * ui_Volume_bar;
extern lv_obj_t * ui_music_prev;
extern lv_obj_t * ui_music_prev_icon;
extern lv_obj_t * ui_music_next;
extern lv_obj_t * ui_music_next_icon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

