// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Music;
lv_obj_t * ui_Campaign_List_group10;
lv_obj_t * ui_Primarystatusbar10;
lv_obj_t * ui_bar2;
lv_obj_t * ui_bar_icon_4;
lv_obj_t * ui_bar_icon_5;
lv_obj_t * ui_bar_icon_6;
lv_obj_t * ui_music_mobile;
lv_obj_t * ui_music_Lyrics;
lv_obj_t * ui_music_Lyrics_txt;
lv_obj_t * ui_music_Singer;
lv_obj_t * ui_music_Singer_txt;
lv_obj_t * ui_music_middle;
lv_obj_t * ui_music_middle_icon;
lv_obj_t * ui_music_bg;
lv_obj_t * ui_music_sound;
lv_obj_t * ui_music_sound_icon;
lv_obj_t * ui_music_sound_01;
lv_obj_t * ui_music_sound_icon01;
lv_obj_t * ui_Volume_bar;
lv_obj_t * ui_music_prev;
lv_obj_t * ui_music_prev_icon;
lv_obj_t * ui_music_next;
lv_obj_t * ui_music_next_icon;

// event funtions
void ui_event_Music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Indoor_Run_data_, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Indoor_Run_data__screen_init);
    }
}

void ui_event_music_sound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Volume_bar, -10, LV_ANIM_OFF);
    }
}

void ui_event_music_sound_01(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_Volume_bar, 10, LV_ANIM_ON);
    }
}

// build funtions

void ui_Music_screen_init(void)
{
    ui_Music = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group10 = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_Campaign_List_group10, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group10, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group10, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Campaign_List_group10, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Campaign_List_group10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group10, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar10 = ui_Primary_status_bar_create(ui_Music);
    lv_obj_set_x(ui_Primarystatusbar10, 0);
    lv_obj_set_y(ui_Primarystatusbar10, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar10, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Music");

    ui_bar2 = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_bar2, 45);
    lv_obj_set_height(ui_bar2, 10);
    lv_obj_set_x(ui_bar2, 0);
    lv_obj_set_y(ui_bar2, 235);
    lv_obj_set_align(ui_bar2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bar2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar2, lv_color_hex(0xAB8080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_4 = lv_obj_create(ui_bar2);
    lv_obj_set_width(ui_bar_icon_4, 8);
    lv_obj_set_height(ui_bar_icon_4, 8);
    lv_obj_set_x(ui_bar_icon_4, -16);
    lv_obj_set_y(ui_bar_icon_4, 0);
    lv_obj_set_align(ui_bar_icon_4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_5 = lv_obj_create(ui_bar2);
    lv_obj_set_width(ui_bar_icon_5, 8);
    lv_obj_set_height(ui_bar_icon_5, 8);
    lv_obj_set_align(ui_bar_icon_5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bar_icon_6 = lv_obj_create(ui_bar2);
    lv_obj_set_width(ui_bar_icon_6, 8);
    lv_obj_set_height(ui_bar_icon_6, 8);
    lv_obj_set_x(ui_bar_icon_6, 16);
    lv_obj_set_y(ui_bar_icon_6, 0);
    lv_obj_set_align(ui_bar_icon_6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_bar_icon_6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bar_icon_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bar_icon_6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bar_icon_6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bar_icon_6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_mobile = lv_image_create(ui_Music);
    lv_image_set_src(ui_music_mobile, &music_mobile);
    lv_obj_set_width(ui_music_mobile, LV_SIZE_CONTENT);   /// 17
    lv_obj_set_height(ui_music_mobile, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_music_mobile, 22);
    lv_obj_set_y(ui_music_mobile, 93);
    lv_obj_add_flag(ui_music_mobile, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_mobile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_Lyrics = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_Lyrics, 335);
    lv_obj_set_height(ui_music_Lyrics, 50);
    lv_obj_set_x(ui_music_Lyrics, 6);
    lv_obj_set_y(ui_music_Lyrics, -144);
    lv_obj_set_align(ui_music_Lyrics, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_music_Lyrics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_music_Lyrics, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_Lyrics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_Lyrics, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_Lyrics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_Lyrics_txt = lv_label_create(ui_music_Lyrics);
    lv_obj_set_width(ui_music_Lyrics_txt, lv_pct(115));
    lv_obj_set_height(ui_music_Lyrics_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_music_Lyrics_txt, -14);
    lv_obj_set_y(ui_music_Lyrics_txt, -8);
    lv_label_set_long_mode(ui_music_Lyrics_txt, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_music_Lyrics_txt,
                      "If I should stay, I would only be in your way, so I'll go, but I know, I'll think of you every step of the way, and I will always love you.");
    lv_obj_set_style_text_font(ui_music_Lyrics_txt, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_Singer = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_Singer, 335);
    lv_obj_set_height(ui_music_Singer, 50);
    lv_obj_set_x(ui_music_Singer, 2);
    lv_obj_set_y(ui_music_Singer, -100);
    lv_obj_set_align(ui_music_Singer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_music_Singer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_music_Singer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_Singer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_Singer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_Singer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_Singer_txt = lv_label_create(ui_music_Singer);
    lv_obj_set_width(ui_music_Singer_txt, lv_pct(115));
    lv_obj_set_height(ui_music_Singer_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_music_Singer_txt, -11);
    lv_obj_set_y(ui_music_Singer_txt, -8);
    lv_label_set_long_mode(ui_music_Singer_txt, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_music_Singer_txt, "I Will Always Love You - GOGO.BY   Galaxy Distribution");
    lv_obj_set_style_text_color(ui_music_Singer_txt, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_music_Singer_txt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_music_Singer_txt, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_middle = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_middle, 116);
    lv_obj_set_height(ui_music_middle, 116);
    lv_obj_set_x(ui_music_middle, 147);
    lv_obj_set_y(ui_music_middle, 218);
    lv_obj_remove_flag(ui_music_middle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_middle, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_middle, lv_color_hex(0xFF003C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_middle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_middle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_middle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_middle_icon = lv_image_create(ui_music_middle);
    lv_image_set_src(ui_music_middle_icon, &music_middle);
    lv_obj_set_width(ui_music_middle_icon, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_music_middle_icon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_music_middle_icon, 5);
    lv_obj_set_y(ui_music_middle_icon, 0);
    lv_obj_set_align(ui_music_middle_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music_middle_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_middle_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_bg = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_bg, 189);
    lv_obj_set_height(ui_music_bg, 80);
    lv_obj_set_x(ui_music_bg, 110);
    lv_obj_set_y(ui_music_bg, 370);
    lv_obj_remove_flag(ui_music_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_bg, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_sound = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_sound, 82);
    lv_obj_set_height(ui_music_sound, 82);
    lv_obj_set_x(ui_music_sound, 27);
    lv_obj_set_y(ui_music_sound, 369);
    lv_obj_remove_flag(ui_music_sound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_sound, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_music_sound, &rectangle_215,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_sound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_sound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_sound_icon = lv_image_create(ui_music_sound);
    lv_image_set_src(ui_music_sound_icon, &music_sound_01);
    lv_obj_set_width(ui_music_sound_icon, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_music_sound_icon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_music_sound_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music_sound_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_sound_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_sound_01 = lv_obj_create(ui_Music);
    lv_obj_set_width(ui_music_sound_01, 82);
    lv_obj_set_height(ui_music_sound_01, 82);
    lv_obj_set_x(ui_music_sound_01, 300);
    lv_obj_set_y(ui_music_sound_01, 369);
    lv_obj_remove_flag(ui_music_sound_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_sound_01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_sound_01, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_sound_01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_music_sound_01, &rectangle_216,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_sound_01, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_sound_01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_sound_icon01 = lv_image_create(ui_music_sound_01);
    lv_image_set_src(ui_music_sound_icon01, &music_sound_03);
    lv_obj_set_width(ui_music_sound_icon01, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_music_sound_icon01, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_music_sound_icon01, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music_sound_icon01, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_sound_icon01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Volume_bar = lv_slider_create(ui_Music);
    lv_slider_set_value(ui_Volume_bar, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Volume_bar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Volume_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Volume_bar, 170);
    lv_obj_set_height(ui_Volume_bar, 10);
    lv_obj_set_x(ui_Volume_bar, 0);
    lv_obj_set_y(ui_Volume_bar, 162);
    lv_obj_set_align(ui_Volume_bar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Volume_bar, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Volume_bar, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Volume_bar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Volume_bar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volume_bar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Volume_bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Volume_bar,
                                                                                                 lv_obj_get_style_pad_right(ui_Volume_bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_music_prev = lv_button_create(ui_Music);
    lv_obj_set_width(ui_music_prev, 86);
    lv_obj_set_height(ui_music_prev, 86);
    lv_obj_set_x(ui_music_prev, 25);
    lv_obj_set_y(ui_music_prev, 233);
    lv_obj_add_flag(ui_music_prev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_music_prev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_prev, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_prev, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_prev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_prev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_prev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_prev_icon = lv_image_create(ui_music_prev);
    lv_image_set_src(ui_music_prev_icon, &music_prev);
    lv_obj_set_width(ui_music_prev_icon, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_music_prev_icon, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_align(ui_music_prev_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music_prev_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_prev_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music_next = lv_button_create(ui_Music);
    lv_obj_set_width(ui_music_next, 86);
    lv_obj_set_height(ui_music_next, 86);
    lv_obj_set_x(ui_music_next, 299);
    lv_obj_set_y(ui_music_next, 233);
    lv_obj_add_flag(ui_music_next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_music_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_music_next, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_music_next, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_music_next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_music_next, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_music_next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_music_next_icon = lv_image_create(ui_music_next);
    lv_image_set_src(ui_music_next_icon, &music_next);
    lv_obj_set_width(ui_music_next_icon, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_music_next_icon, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_align(ui_music_next_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music_next_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_music_next_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_music_sound, ui_event_music_sound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_music_sound_01, ui_event_music_sound_01, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Music, ui_event_Music, LV_EVENT_ALL, NULL);

}

void ui_Music_screen_destroy(void)
{
    if(ui_Music) lv_obj_del(ui_Music);

    // NULL screen variables
    ui_Music = NULL;
    ui_Campaign_List_group10 = NULL;
    ui_Primarystatusbar10 = NULL;
    ui_bar2 = NULL;
    ui_bar_icon_4 = NULL;
    ui_bar_icon_5 = NULL;
    ui_bar_icon_6 = NULL;
    ui_music_mobile = NULL;
    ui_music_Lyrics = NULL;
    ui_music_Lyrics_txt = NULL;
    ui_music_Singer = NULL;
    ui_music_Singer_txt = NULL;
    ui_music_middle = NULL;
    ui_music_middle_icon = NULL;
    ui_music_bg = NULL;
    ui_music_sound = NULL;
    ui_music_sound_icon = NULL;
    ui_music_sound_01 = NULL;
    ui_music_sound_icon01 = NULL;
    ui_Volume_bar = NULL;
    ui_music_prev = NULL;
    ui_music_prev_icon = NULL;
    ui_music_next = NULL;
    ui_music_next_icon = NULL;

}
