// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Outdoor_Run_01;
lv_obj_t * ui_Campaign_List_group13;
lv_obj_t * ui_Primarystatusbar13;
lv_obj_t * ui_Outdoor_Run_icon_1;
lv_obj_t * ui_ready_txt1;
lv_obj_t * ui_indoor_run_group1;
lv_obj_t * ui_indoor_run_hr_icon1;
lv_obj_t * ui_Image20;
lv_obj_t * ui_indoor_run_date1;
lv_obj_t * ui_indoor_run_date3;

// event funtions
void ui_event_Campaign_List_group13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Outdoor_Run_02, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Outdoor_Run_02_screen_init);
    }
}

// build funtions

void ui_Outdoor_Run_01_screen_init(void)
{
    ui_Outdoor_Run_01 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Run_01, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Outdoor_Run_01, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_01, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group13 = lv_obj_create(ui_Outdoor_Run_01);
    lv_obj_set_width(ui_Campaign_List_group13, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group13, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group13, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Campaign_List_group13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar13 = ui_Primary_status_bar_create(ui_Outdoor_Run_01);
    lv_obj_set_x(ui_Primarystatusbar13, 0);
    lv_obj_set_y(ui_Primarystatusbar13, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar13, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Outdoor Run");

    ui_Outdoor_Run_icon_1 = lv_image_create(ui_Outdoor_Run_01);
    lv_image_set_src(ui_Outdoor_Run_icon_1, &campaign_list_outdoor_run_icon03);
    lv_obj_set_width(ui_Outdoor_Run_icon_1, LV_SIZE_CONTENT);   /// 184
    lv_obj_set_height(ui_Outdoor_Run_icon_1, LV_SIZE_CONTENT);    /// 184
    lv_obj_set_x(ui_Outdoor_Run_icon_1, 0);
    lv_obj_set_y(ui_Outdoor_Run_icon_1, -60);
    lv_obj_set_align(ui_Outdoor_Run_icon_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Outdoor_Run_icon_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Outdoor_Run_icon_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ready_txt1 = lv_label_create(ui_Outdoor_Run_01);
    lv_obj_set_width(ui_ready_txt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ready_txt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ready_txt1, 0);
    lv_obj_set_y(ui_ready_txt1, 90);
    lv_obj_set_align(ui_ready_txt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ready_txt1, "          Positioning...\nPlease wait in the open.");
    lv_obj_set_style_text_align(ui_ready_txt1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ready_txt1, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_group1 = lv_obj_create(ui_Outdoor_Run_01);
    lv_obj_set_width(ui_indoor_run_group1, 200);
    lv_obj_set_height(ui_indoor_run_group1, 50);
    lv_obj_set_x(ui_indoor_run_group1, 0);
    lv_obj_set_y(ui_indoor_run_group1, 180);
    lv_obj_set_align(ui_indoor_run_group1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_indoor_run_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_indoor_run_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_indoor_run_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_indoor_run_group1, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_indoor_run_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_hr_icon1 = lv_image_create(ui_indoor_run_group1);
    lv_image_set_src(ui_indoor_run_hr_icon1, &campaign_list_move_hr_icon);
    lv_obj_set_width(ui_indoor_run_hr_icon1, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_indoor_run_hr_icon1, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_indoor_run_hr_icon1, 22);
    lv_obj_set_y(ui_indoor_run_hr_icon1, 0);
    lv_obj_set_align(ui_indoor_run_hr_icon1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indoor_run_hr_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_indoor_run_hr_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_indoor_run_group1);
    lv_image_set_src(ui_Image20, &campaign_list_group_1000006182);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image20, -71);
    lv_obj_set_y(ui_Image20, -1);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indoor_run_date1 = lv_label_create(ui_indoor_run_group1);
    lv_obj_set_width(ui_indoor_run_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor_run_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor_run_date1, 123);
    lv_obj_set_y(ui_indoor_run_date1, -7);
    lv_label_set_text(ui_indoor_run_date1, "88");
    lv_obj_set_style_text_font(ui_indoor_run_date1, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_date3 = lv_label_create(ui_indoor_run_group1);
    lv_obj_set_width(ui_indoor_run_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor_run_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor_run_date3, 27);
    lv_obj_set_y(ui_indoor_run_date3, -7);
    lv_label_set_text(ui_indoor_run_date3, "GPS");
    lv_obj_set_style_text_font(ui_indoor_run_date3, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Campaign_List_group13, ui_event_Campaign_List_group13, LV_EVENT_ALL, NULL);

}

void ui_Outdoor_Run_01_screen_destroy(void)
{
    if(ui_Outdoor_Run_01) lv_obj_del(ui_Outdoor_Run_01);

    // NULL screen variables
    ui_Outdoor_Run_01 = NULL;
    ui_Campaign_List_group13 = NULL;
    ui_Primarystatusbar13 = NULL;
    ui_Outdoor_Run_icon_1 = NULL;
    ui_ready_txt1 = NULL;
    ui_indoor_run_group1 = NULL;
    ui_indoor_run_hr_icon1 = NULL;
    ui_Image20 = NULL;
    ui_indoor_run_date1 = NULL;
    ui_indoor_run_date3 = NULL;

}
