// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Outdoor_Run_03;
lv_obj_t * ui_Campaign_List_group14;
lv_obj_t * ui_count_down_date1;

// event funtions
void ui_event_Campaign_List_group14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Outdoor_Run_04, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Outdoor_Run_04_screen_init);
    }
}

// build funtions

void ui_Outdoor_Run_03_screen_init(void)
{
    ui_Outdoor_Run_03 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Run_03, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Outdoor_Run_03, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_03, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group14 = lv_obj_create(ui_Outdoor_Run_03);
    lv_obj_set_width(ui_Campaign_List_group14, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group14, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group14, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group14, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Campaign_List_group14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_count_down_date1 = lv_label_create(ui_Outdoor_Run_03);
    lv_obj_set_width(ui_count_down_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_count_down_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_count_down_date1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_count_down_date1, "3");
    lv_obj_set_style_text_font(ui_count_down_date1, &ui_font_HONORS_200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Campaign_List_group14, ui_event_Campaign_List_group14, LV_EVENT_ALL, NULL);

}

void ui_Outdoor_Run_03_screen_destroy(void)
{
    if(ui_Outdoor_Run_03) lv_obj_del(ui_Outdoor_Run_03);

    // NULL screen variables
    ui_Outdoor_Run_03 = NULL;
    ui_Campaign_List_group14 = NULL;
    ui_count_down_date1 = NULL;

}
