// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_OUTDOOR_RUN_04_H
#define UI_OUTDOOR_RUN_04_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Run_04
extern void ui_Outdoor_Run_04_screen_init(void);
extern void ui_Outdoor_Run_04_screen_destroy(void);
extern lv_obj_t * ui_Outdoor_Run_04;
extern lv_obj_t * ui_Campaign_List_group16;
extern lv_obj_t * ui_count_down_date3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label100;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label101;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

