// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_OUTDOOR_RUN_05_H
#define UI_OUTDOOR_RUN_05_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Run_05
extern void ui_Outdoor_Run_05_screen_init(void);
extern void ui_Outdoor_Run_05_screen_destroy(void);
extern void ui_event_Outdoor_Run_05(lv_event_t * e);
extern lv_obj_t * ui_Outdoor_Run_05;
extern lv_obj_t * ui_Campaign_List_group17;
extern void ui_event_Primarystatusbar14_Primary_status_bar(lv_event_t * e);
extern lv_obj_t * ui_Primarystatusbar14;
extern lv_obj_t * ui_Motion_Record_group1;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Image21;
extern void ui_event_outdoor_run_arc(lv_event_t * e);
extern lv_obj_t * ui_outdoor_run_arc;
extern lv_obj_t * ui_Label102;
extern lv_obj_t * ui_Label103;
extern lv_obj_t * ui_Motion_Recording_group1;
extern lv_obj_t * ui_Motion_Time_txt1;
extern lv_obj_t * ui_Label104;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_motionDatagroup1;
extern lv_obj_t * ui_motionDatagroup9;
extern lv_obj_t * ui_motionDatagroup10;
extern lv_obj_t * ui_motionDatagroup11;
extern lv_obj_t * ui_motionDatagroup12;
extern lv_obj_t * ui_motionDatagroup13;
extern lv_obj_t * ui_motionDatagroup14;
extern lv_obj_t * ui_motionDatagroup15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

