// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_OUTDOOR_RUN_01_H
#define UI_OUTDOOR_RUN_01_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Run_01
extern void ui_Outdoor_Run_01_screen_init(void);
extern void ui_Outdoor_Run_01_screen_destroy(void);
extern lv_obj_t * ui_Outdoor_Run_01;
extern void ui_event_Campaign_List_group13(lv_event_t * e);
extern lv_obj_t * ui_Campaign_List_group13;
extern lv_obj_t * ui_Primarystatusbar13;
extern lv_obj_t * ui_Outdoor_Run_icon_1;
extern lv_obj_t * ui_ready_txt1;
extern lv_obj_t * ui_indoor_run_group1;
extern lv_obj_t * ui_indoor_run_hr_icon1;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_indoor_run_date1;
extern lv_obj_t * ui_indoor_run_date3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

