// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Outdoor_Run_00;
lv_obj_t * ui_Campaign_List_group15;
lv_obj_t * ui_count_down_date2;
lv_obj_t * ui_gps_icon;
lv_obj_t * ui_Label99;

// event funtions
void ui_event_Campaign_List_group15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Outdoor_Run_01, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Outdoor_Run_01_screen_init);
    }
}

// build funtions

void ui_Outdoor_Run_00_screen_init(void)
{
    ui_Outdoor_Run_00 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Run_00, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Outdoor_Run_00, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_00, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group15 = lv_obj_create(ui_Outdoor_Run_00);
    lv_obj_set_width(ui_Campaign_List_group15, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group15, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group15, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group15, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Campaign_List_group15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_count_down_date2 = lv_label_create(ui_Outdoor_Run_00);
    lv_obj_set_width(ui_count_down_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_count_down_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_count_down_date2, 0);
    lv_obj_set_y(ui_count_down_date2, -38);
    lv_obj_set_align(ui_count_down_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_count_down_date2, "GPS Signal Updates");
    lv_obj_set_style_text_font(ui_count_down_date2, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gps_icon = lv_image_create(ui_Outdoor_Run_00);
    lv_image_set_src(ui_gps_icon, &campaign_list_group_1000005435);
    lv_obj_set_width(ui_gps_icon, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_gps_icon, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(ui_gps_icon, 0);
    lv_obj_set_y(ui_gps_icon, -110);
    lv_obj_set_align(ui_gps_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gps_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_gps_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label99 = lv_label_create(ui_Outdoor_Run_00);
    lv_obj_set_width(ui_Label99, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label99, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label99, -10);
    lv_obj_set_y(ui_Label99, 55);
    lv_obj_set_align(ui_Label99, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label99,
                      "       Ephemeris data has expired.\n    GPS position may become slow.\n      Please connect Wofit APP to \n           update automatically.");
    lv_obj_set_style_text_color(ui_Label99, lv_color_hex(0x797979), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label99, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label99, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label99, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label99, &ui_font_HONORS_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Campaign_List_group15, ui_event_Campaign_List_group15, LV_EVENT_ALL, NULL);

}

void ui_Outdoor_Run_00_screen_destroy(void)
{
    if(ui_Outdoor_Run_00) lv_obj_del(ui_Outdoor_Run_00);

    // NULL screen variables
    ui_Outdoor_Run_00 = NULL;
    ui_Campaign_List_group15 = NULL;
    ui_count_down_date2 = NULL;
    ui_gps_icon = NULL;
    ui_Label99 = NULL;

}
