// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_OUTDOOR_RUN_02_H
#define UI_OUTDOOR_RUN_02_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Outdoor_Run_02
extern void ui_Outdoor_Run_02_screen_init(void);
extern void ui_Outdoor_Run_02_screen_destroy(void);
extern lv_obj_t * ui_Outdoor_Run_02;
extern lv_obj_t * ui_Campaign_List_group12;
extern lv_obj_t * ui_Primarystatusbar12;
extern lv_obj_t * ui_ready_txt2;
extern lv_obj_t * ui_indoor_run_group2;
extern lv_obj_t * ui_indoor_run_hr_icon2;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_indoor_run_date2;
extern lv_obj_t * ui_indoor_run_date4;
extern lv_obj_t * ui_Outdoor_Run_but;
extern void ui_event_Outdoor_Run_icon_2(lv_event_t * e);
extern lv_obj_t * ui_Outdoor_Run_icon_2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

