// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Outdoor_Run_05;
lv_obj_t * ui_Campaign_List_group17;
lv_obj_t * ui_Primarystatusbar14;
lv_obj_t * ui_Motion_Record_group1;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Image21;
lv_obj_t * ui_outdoor_run_arc;
lv_obj_t * ui_Label102;
lv_obj_t * ui_Label103;
lv_obj_t * ui_Motion_Recording_group1;
lv_obj_t * ui_Motion_Time_txt1;
lv_obj_t * ui_Label104;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_motionDatagroup1;
lv_obj_t * ui_motionDatagroup9;
lv_obj_t * ui_motionDatagroup10;
lv_obj_t * ui_motionDatagroup11;
lv_obj_t * ui_motionDatagroup12;
lv_obj_t * ui_motionDatagroup13;
lv_obj_t * ui_motionDatagroup14;
lv_obj_t * ui_motionDatagroup15;

// event funtions
void ui_event_Outdoor_Run_05(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_clk_01, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_clk_01_screen_init);
    }
}

void ui_event_Primarystatusbar14_Primary_status_bar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_clk_01, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clk_01_screen_init);
    }
}

void ui_event_outdoor_run_arc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_comp_get_child(ui_motionDatagroup13, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), target, "",
                               "");
    }
}

// build funtions

void ui_Outdoor_Run_05_screen_init(void)
{
    ui_Outdoor_Run_05 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Run_05, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Outdoor_Run_05, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_05, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Outdoor_Run_05, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_05, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group17 = lv_obj_create(ui_Outdoor_Run_05);
    lv_obj_set_width(ui_Campaign_List_group17, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group17, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group17, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Campaign_List_group17, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_Campaign_List_group17, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Campaign_List_group17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar14 = ui_Primary_status_bar_create(ui_Outdoor_Run_05);
    lv_obj_set_x(ui_Primarystatusbar14, 0);
    lv_obj_set_y(ui_Primarystatusbar14, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar14, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Motion Record");

    ui_Motion_Record_group1 = lv_obj_create(ui_Outdoor_Run_05);
    lv_obj_set_width(ui_Motion_Record_group1, 410);
    lv_obj_set_height(ui_Motion_Record_group1, 390);
    lv_obj_set_x(ui_Motion_Record_group1, 0);
    lv_obj_set_y(ui_Motion_Record_group1, 20);
    lv_obj_set_align(ui_Motion_Record_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Motion_Record_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Motion_Record_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Motion_Record_group1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Motion_Record_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Motion_Record_group1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Motion_Record_group1, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Motion_Record_group1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Motion_Record_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_Motion_Record_group1);
    lv_obj_set_width(ui_Panel32, 370);
    lv_obj_set_height(ui_Panel32, 110);
    lv_obj_set_x(ui_Panel32, 25);
    lv_obj_set_y(ui_Panel32, 78);
    lv_obj_remove_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image21 = lv_image_create(ui_Panel32);
    lv_image_set_src(ui_Image21, &campaign_list_outdoor_run_icon02);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 88
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 88
    lv_obj_set_x(ui_Image21, -130);
    lv_obj_set_y(ui_Image21, 0);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_outdoor_run_arc = lv_arc_create(ui_Panel32);
    lv_obj_set_width(ui_outdoor_run_arc, 110);
    lv_obj_set_height(ui_outdoor_run_arc, 110);
    lv_obj_set_x(ui_outdoor_run_arc, -130);
    lv_obj_set_y(ui_outdoor_run_arc, 0);
    lv_obj_set_align(ui_outdoor_run_arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_outdoor_run_arc, 0, 10000);
    lv_arc_set_value(ui_outdoor_run_arc, 8000);
    lv_arc_set_bg_angles(ui_outdoor_run_arc, 0, 360);
    lv_arc_set_rotation(ui_outdoor_run_arc, 270);
    lv_obj_set_style_arc_width(ui_outdoor_run_arc, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_outdoor_run_arc, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_outdoor_run_arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outdoor_run_arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label102, 18);
    lv_obj_set_y(ui_Label102, -6);
    lv_obj_set_align(ui_Label102, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label102, "Outdoor Run");
    lv_obj_set_style_text_font(ui_Label102, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label103 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label103, 18);
    lv_obj_set_y(ui_Label103, 35);
    lv_obj_set_align(ui_Label103, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label103, "04/06 08:00");
    lv_obj_set_style_text_color(ui_Label103, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label103, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motion_Recording_group1 = lv_obj_create(ui_Motion_Record_group1);
    lv_obj_set_width(ui_Motion_Recording_group1, 366);
    lv_obj_set_height(ui_Motion_Recording_group1, 70);
    lv_obj_set_x(ui_Motion_Recording_group1, 0);
    lv_obj_set_y(ui_Motion_Recording_group1, 71);
    lv_obj_remove_flag(ui_Motion_Recording_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Motion_Recording_group1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Motion_Recording_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Motion_Recording_group1, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Motion_Recording_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motion_Time_txt1 = lv_label_create(ui_Motion_Recording_group1);
    lv_obj_set_width(ui_Motion_Time_txt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motion_Time_txt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motion_Time_txt1, -12);
    lv_obj_set_y(ui_Motion_Time_txt1, 0);
    lv_label_set_text(ui_Motion_Time_txt1, "Motion Time");
    lv_obj_set_style_text_color(ui_Motion_Time_txt1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Motion_Time_txt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Motion_Time_txt1, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Motion_Recording_group1);
    lv_obj_set_width(ui_Label104, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label104, 209);
    lv_obj_set_y(ui_Label104, -2);
    lv_label_set_text(ui_Label104, "00:45:38");
    lv_obj_set_style_text_color(ui_Label104, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label104, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label104, &ui_font_HONOR_M_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_Motion_Recording_group1);
    lv_obj_set_width(ui_Panel33, 364);
    lv_obj_set_height(ui_Panel33, 2);
    lv_obj_set_x(ui_Panel33, 0);
    lv_obj_set_y(ui_Panel33, 30);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel33, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel33, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_motionDatagroup1 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup1, 0);
    lv_obj_set_y(ui_motionDatagroup1, 73);

    ui_motionDatagroup9 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup9, 0);
    lv_obj_set_y(ui_motionDatagroup9, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup9, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Calories");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup9, UI_COMP_MOTIONDATAGROUP_KM_TXT), "kcal");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup9, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "120");

    ui_motionDatagroup10 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup10, 0);
    lv_obj_set_y(ui_motionDatagroup10, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup10, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Fastest Pace");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup10, UI_COMP_MOTIONDATAGROUP_KM_TXT), "km");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup10, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "12'15\"");

    ui_motionDatagroup11 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup11, 0);
    lv_obj_set_y(ui_motionDatagroup11, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup11, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Average Speed");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup11, UI_COMP_MOTIONDATAGROUP_KM_TXT), "km/hour");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup11, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "12.5");

    ui_motionDatagroup12 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup12, 0);
    lv_obj_set_y(ui_motionDatagroup12, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup12, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Average Pace");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup12, UI_COMP_MOTIONDATAGROUP_KM_TXT), "/km");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup12, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "12'02\"");

    ui_motionDatagroup13 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup13, 0);
    lv_obj_set_y(ui_motionDatagroup13, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup13, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Steps");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup13, UI_COMP_MOTIONDATAGROUP_KM_TXT), "step");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup13, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "8000");

    ui_motionDatagroup14 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup14, 0);
    lv_obj_set_y(ui_motionDatagroup14, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup14, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT), "Average pace");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup14, UI_COMP_MOTIONDATAGROUP_KM_TXT), "step/m");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup14, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "78");

    ui_motionDatagroup15 = ui_motionDatagroup_create(ui_Motion_Record_group1);
    lv_obj_set_x(ui_motionDatagroup15, 0);
    lv_obj_set_y(ui_motionDatagroup15, 73);

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup15, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_TXT),
                      "Average stride");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup15, UI_COMP_MOTIONDATAGROUP_KM_TXT), "/cm");

    lv_label_set_text(ui_comp_get_child(ui_motionDatagroup15, UI_COMP_MOTIONDATAGROUP_TOTAL_DISTANCE_DATE), "58");

    lv_obj_add_event_cb(ui_Primarystatusbar14, ui_event_Primarystatusbar14_Primary_status_bar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_outdoor_run_arc, ui_event_outdoor_run_arc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Outdoor_Run_05, ui_event_Outdoor_Run_05, LV_EVENT_ALL, NULL);

}

void ui_Outdoor_Run_05_screen_destroy(void)
{
    if(ui_Outdoor_Run_05) lv_obj_del(ui_Outdoor_Run_05);

    // NULL screen variables
    ui_Outdoor_Run_05 = NULL;
    ui_Campaign_List_group17 = NULL;
    ui_Primarystatusbar14 = NULL;
    ui_Motion_Record_group1 = NULL;
    ui_Panel32 = NULL;
    ui_Image21 = NULL;
    ui_outdoor_run_arc = NULL;
    ui_Label102 = NULL;
    ui_Label103 = NULL;
    ui_Motion_Recording_group1 = NULL;
    ui_Motion_Time_txt1 = NULL;
    ui_Label104 = NULL;
    ui_Panel33 = NULL;
    ui_motionDatagroup1 = NULL;
    ui_motionDatagroup9 = NULL;
    ui_motionDatagroup10 = NULL;
    ui_motionDatagroup11 = NULL;
    ui_motionDatagroup12 = NULL;
    ui_motionDatagroup13 = NULL;
    ui_motionDatagroup14 = NULL;
    ui_motionDatagroup15 = NULL;

}
