// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_Outdoor_Run_02;
lv_obj_t * ui_Campaign_List_group12;
lv_obj_t * ui_Primarystatusbar12;
lv_obj_t * ui_ready_txt2;
lv_obj_t * ui_indoor_run_group2;
lv_obj_t * ui_indoor_run_hr_icon2;
lv_obj_t * ui_Image18;
lv_obj_t * ui_indoor_run_date2;
lv_obj_t * ui_indoor_run_date4;
lv_obj_t * ui_Outdoor_Run_but;
lv_obj_t * ui_Outdoor_Run_icon_2;

// event funtions
void ui_event_Outdoor_Run_icon_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Outdoor_Run_03, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Outdoor_Run_03_screen_init);
    }
}

// build funtions

void ui_Outdoor_Run_02_screen_init(void)
{
    ui_Outdoor_Run_02 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Outdoor_Run_02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Outdoor_Run_02, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_02, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Outdoor_Run_02, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Outdoor_Run_02, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group12 = lv_obj_create(ui_Outdoor_Run_02);
    lv_obj_set_width(ui_Campaign_List_group12, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group12, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group12, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Campaign_List_group12, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Campaign_List_group12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group12, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar12 = ui_Primary_status_bar_create(ui_Outdoor_Run_02);
    lv_obj_set_x(ui_Primarystatusbar12, 0);
    lv_obj_set_y(ui_Primarystatusbar12, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar12, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Outdoor Run");

    ui_ready_txt2 = lv_label_create(ui_Outdoor_Run_02);
    lv_obj_set_width(ui_ready_txt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ready_txt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ready_txt2, 0);
    lv_obj_set_y(ui_ready_txt2, 90);
    lv_obj_set_align(ui_ready_txt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ready_txt2, "           Ready to go\nClick to start exercising");
    lv_obj_set_style_text_align(ui_ready_txt2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ready_txt2, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_group2 = lv_obj_create(ui_Outdoor_Run_02);
    lv_obj_set_width(ui_indoor_run_group2, 200);
    lv_obj_set_height(ui_indoor_run_group2, 50);
    lv_obj_set_x(ui_indoor_run_group2, 0);
    lv_obj_set_y(ui_indoor_run_group2, 180);
    lv_obj_set_align(ui_indoor_run_group2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_indoor_run_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_indoor_run_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_indoor_run_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_indoor_run_group2, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_indoor_run_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_hr_icon2 = lv_image_create(ui_indoor_run_group2);
    lv_image_set_src(ui_indoor_run_hr_icon2, &campaign_list_move_hr_icon);
    lv_obj_set_width(ui_indoor_run_hr_icon2, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_indoor_run_hr_icon2, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_indoor_run_hr_icon2, 22);
    lv_obj_set_y(ui_indoor_run_hr_icon2, 0);
    lv_obj_set_align(ui_indoor_run_hr_icon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_indoor_run_hr_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_indoor_run_hr_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_image_create(ui_indoor_run_group2);
    lv_image_set_src(ui_Image18, &campaign_list_group_1000006182);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 36
    lv_obj_set_x(ui_Image18, -71);
    lv_obj_set_y(ui_Image18, -1);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indoor_run_date2 = lv_label_create(ui_indoor_run_group2);
    lv_obj_set_width(ui_indoor_run_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor_run_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor_run_date2, 123);
    lv_obj_set_y(ui_indoor_run_date2, -7);
    lv_label_set_text(ui_indoor_run_date2, "88");
    lv_obj_set_style_text_font(ui_indoor_run_date2, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_indoor_run_date4 = lv_label_create(ui_indoor_run_group2);
    lv_obj_set_width(ui_indoor_run_date4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indoor_run_date4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_indoor_run_date4, 27);
    lv_obj_set_y(ui_indoor_run_date4, -7);
    lv_label_set_text(ui_indoor_run_date4, "GPS");
    lv_obj_set_style_text_font(ui_indoor_run_date4, &ui_font_HONORS_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Outdoor_Run_but = lv_button_create(ui_Outdoor_Run_02);
    lv_obj_set_width(ui_Outdoor_Run_but, 184);
    lv_obj_set_height(ui_Outdoor_Run_but, 184);
    lv_obj_set_x(ui_Outdoor_Run_but, 0);
    lv_obj_set_y(ui_Outdoor_Run_but, -60);
    lv_obj_set_align(ui_Outdoor_Run_but, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Outdoor_Run_but, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Outdoor_Run_but, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Outdoor_Run_but, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Outdoor_Run_icon_2 = lv_image_create(ui_Outdoor_Run_but);
    lv_image_set_src(ui_Outdoor_Run_icon_2, &campaign_list_outdoor_run_icon01);
    lv_obj_set_width(ui_Outdoor_Run_icon_2, LV_SIZE_CONTENT);   /// 184
    lv_obj_set_height(ui_Outdoor_Run_icon_2, LV_SIZE_CONTENT);    /// 184
    lv_obj_set_align(ui_Outdoor_Run_icon_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Outdoor_Run_icon_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Outdoor_Run_icon_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Outdoor_Run_icon_2, ui_event_Outdoor_Run_icon_2, LV_EVENT_ALL, NULL);

}

void ui_Outdoor_Run_02_screen_destroy(void)
{
    if(ui_Outdoor_Run_02) lv_obj_del(ui_Outdoor_Run_02);

    // NULL screen variables
    ui_Outdoor_Run_02 = NULL;
    ui_Campaign_List_group12 = NULL;
    ui_Primarystatusbar12 = NULL;
    ui_ready_txt2 = NULL;
    ui_indoor_run_group2 = NULL;
    ui_indoor_run_hr_icon2 = NULL;
    ui_Image18 = NULL;
    ui_indoor_run_date2 = NULL;
    ui_indoor_run_date4 = NULL;
    ui_Outdoor_Run_but = NULL;
    ui_Outdoor_Run_icon_2 = NULL;

}
