// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_setting_group01;
extern void ui_event_Primarystatusbar16_Primary_status_bar(lv_event_t * e);
extern lv_obj_t * ui_Primarystatusbar16;
extern lv_obj_t * ui_setting_group001;
extern lv_obj_t * ui_dialgroup02;
extern void ui_event_dialgroup2_dialgroup02(lv_event_t * e);
extern lv_obj_t * ui_dialgroup2;
extern lv_obj_t * ui_dialgroup3;
extern lv_obj_t * ui_dialgroup4;
extern lv_obj_t * ui_dialgroup5;
extern void ui_event_dialgroup6_dialgroup02(lv_event_t * e);
extern lv_obj_t * ui_dialgroup6;
extern lv_obj_t * ui_dialgroup7;
extern lv_obj_t * ui_dialgroup8;
extern lv_obj_t * ui_dialgroup9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

