// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_setting;
lv_obj_t * ui_setting_group01;
lv_obj_t * ui_Primarystatusbar16;
lv_obj_t * ui_setting_group001;
lv_obj_t * ui_dialgroup02;
lv_obj_t * ui_dialgroup2;
lv_obj_t * ui_dialgroup3;
lv_obj_t * ui_dialgroup4;
lv_obj_t * ui_dialgroup5;
lv_obj_t * ui_dialgroup6;
lv_obj_t * ui_dialgroup7;
lv_obj_t * ui_dialgroup8;
lv_obj_t * ui_dialgroup9;

// event funtions
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_control_center, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_center_screen_init);
    }
}

void ui_event_Primarystatusbar16_Primary_status_bar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_control_center, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_center_screen_init);
    }
}

void ui_event_dialgroup2_dialgroup02(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Display_Brightness, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Display_Brightness_screen_init);
    }
}

void ui_event_dialgroup6_dialgroup02(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_workout_setting, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_workout_setting_screen_init);
    }
}

// build funtions

void ui_setting_screen_init(void)
{
    ui_setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_setting_group01 = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_setting_group01, lv_pct(100));
    lv_obj_set_height(ui_setting_group01, lv_pct(100));
    lv_obj_set_align(ui_setting_group01, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting_group01, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_group01, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_setting_group01, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_setting_group01, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setting_group01, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_group01, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting_group01, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_setting_group01, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_setting_group01, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar16 = ui_Primary_status_bar_create(ui_setting);
    lv_obj_set_x(ui_Primarystatusbar16, 0);
    lv_obj_set_y(ui_Primarystatusbar16, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar16, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Setting");

    ui_setting_group001 = lv_obj_create(ui_setting);
    lv_obj_set_width(ui_setting_group001, 410);
    lv_obj_set_height(ui_setting_group001, 426);
    lv_obj_set_x(ui_setting_group001, 0);
    lv_obj_set_y(ui_setting_group001, 36);
    lv_obj_set_align(ui_setting_group001, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting_group001, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_group001, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_setting_group001, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_setting_group001, LV_DIR_VER);
    lv_obj_set_style_radius(ui_setting_group001, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_setting_group001, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_group001, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_setting_group001, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_setting_group001, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_setting_group001, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_setting_group001, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_setting_group001, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_setting_group001, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_setting_group001, -8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_setting_group001, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialgroup02 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup02, -5);
    lv_obj_set_y(ui_dialgroup02, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup02, &setting_bg01, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup02, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_dial_70);

    ui_dialgroup2 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup2, -5);
    lv_obj_set_y(ui_dialgroup2, -51);
    lv_obj_remove_flag(ui_dialgroup2, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_dialgroup2, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dialgroup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_display_brightness_70);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 270);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 49);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_obj_set_x(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), -14);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), -9);
    lv_obj_set_align(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), LV_ALIGN_TOP_LEFT);
    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup2, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                      "Display & Brightness");

    ui_dialgroup3 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup3, -5);
    lv_obj_set_y(ui_dialgroup3, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup3, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_sound_vibration_70);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup3, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "Sound & Vibration");

    ui_dialgroup4 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup4, -5);
    lv_obj_set_y(ui_dialgroup4, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup4, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_preference_70);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup4, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "Preference");

    ui_dialgroup5 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup5, -5);
    lv_obj_set_y(ui_dialgroup5, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup5, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_power_saving_mode_70);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_LIN_2), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_LIN_2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup5, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "Power Saving Mode");

    ui_dialgroup6 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup6, -5);
    lv_obj_set_y(ui_dialgroup6, -51);
    lv_obj_remove_flag(ui_dialgroup6, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_dialgroup6, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_workout_settings_70);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_LIN_2), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_LIN_2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup6, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "Workout settings");

    ui_dialgroup7 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup7, -5);
    lv_obj_set_y(ui_dialgroup7, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup7, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_sos_70);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_LIN_2), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_LIN_2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup7, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "SOS");

    ui_dialgroup8 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup8, -5);
    lv_obj_set_y(ui_dialgroup8, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup8, &setting_bg02, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_systems_updates_70);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_LIN_2), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_LIN_2), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup8, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "Systems & Updates");

    ui_dialgroup9 = ui_dialgroup02_create(ui_setting_group001);
    lv_obj_set_x(ui_dialgroup9, -5);
    lv_obj_set_y(ui_dialgroup9, -51);
    lv_obj_set_style_bg_image_src(ui_dialgroup9, &setting_bg03, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_ICON_2),
                     &setting_about_70);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_LIN_2), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_LIN_2), 0,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_width(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 280);
    lv_obj_set_height(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 50);
    lv_obj_set_x(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 54);
    lv_obj_set_y(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP), 0);

    lv_label_set_long_mode(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2),
                           LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_comp_get_child(ui_dialgroup9, UI_COMP_DIALGROUP02_DIAL_TXT_GROUP_DIAL_TXT2), "About");

    lv_obj_add_event_cb(ui_Primarystatusbar16, ui_event_Primarystatusbar16_Primary_status_bar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dialgroup2, ui_event_dialgroup2_dialgroup02, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dialgroup6, ui_event_dialgroup6_dialgroup02, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);

}

void ui_setting_screen_destroy(void)
{
    if(ui_setting) lv_obj_del(ui_setting);

    // NULL screen variables
    ui_setting = NULL;
    ui_setting_group01 = NULL;
    ui_Primarystatusbar16 = NULL;
    ui_setting_group001 = NULL;
    ui_dialgroup02 = NULL;
    ui_dialgroup2 = NULL;
    ui_dialgroup3 = NULL;
    ui_dialgroup4 = NULL;
    ui_dialgroup5 = NULL;
    ui_dialgroup6 = NULL;
    ui_dialgroup7 = NULL;
    ui_dialgroup8 = NULL;
    ui_dialgroup9 = NULL;

}
