// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_setting_;
lv_obj_t * ui_Campaign_List_group1;
lv_obj_t * ui_Primarystatusbar1;
lv_obj_t * ui_Setting_group;
lv_obj_t * ui_goal_group;
lv_obj_t * ui_Remind_group;
lv_obj_t * ui_bnt_group;
lv_obj_t * ui_cancel_icon;

// event funtions
void ui_event_Primarystatusbar1_Primary_status_bar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_List, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Campaign_List_screen_init);
    }
}

void ui_event_goal_group_Setting_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Goal, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Goal_screen_init);
    }
}

void ui_event_Remind_group_Setting_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_reminders, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_reminders_screen_init);
    }
}

void ui_event_bnt_group(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Campaign_List, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Campaign_List_screen_init);
    }
}

// build funtions

void ui_setting__screen_init(void)
{
    ui_setting_ = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setting_, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_setting_, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting_, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Campaign_List_group1 = lv_obj_create(ui_setting_);
    lv_obj_set_width(ui_Campaign_List_group1, lv_pct(100));
    lv_obj_set_height(ui_Campaign_List_group1, lv_pct(100));
    lv_obj_set_align(ui_Campaign_List_group1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Campaign_List_group1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Campaign_List_group1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Campaign_List_group1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Campaign_List_group1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Campaign_List_group1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Campaign_List_group1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Campaign_List_group1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Campaign_List_group1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Campaign_List_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar1 = ui_Primary_status_bar_create(ui_setting_);
    lv_obj_set_x(ui_Primarystatusbar1, 0);
    lv_obj_set_y(ui_Primarystatusbar1, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar1, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Setting");

    ui_Setting_group = lv_obj_create(ui_setting_);
    lv_obj_set_width(ui_Setting_group, 410);
    lv_obj_set_height(ui_Setting_group, 426);
    lv_obj_set_x(ui_Setting_group, 0);
    lv_obj_set_y(ui_Setting_group, 36);
    lv_obj_set_align(ui_Setting_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Setting_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Setting_group, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Setting_group, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Setting_group, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Setting_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Setting_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Setting_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Setting_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Setting_group, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Setting_group, 55, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Setting_group, -8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Setting_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goal_group = ui_Setting_group_create(ui_Setting_group);
    lv_obj_set_x(ui_goal_group, 0);
    lv_obj_set_y(ui_goal_group, 0);
    lv_obj_set_style_bg_image_src(ui_goal_group, &campaign_list_rectangle_03,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_goal_group, UI_COMP_SETTING_GROUP_GOAL_ICON),
                     &campaign_list_goal_icon);

    ui_Remind_group = ui_Setting_group_create(ui_Setting_group);
    lv_obj_set_x(ui_Remind_group, 0);
    lv_obj_set_y(ui_Remind_group, 0);
    lv_obj_set_style_bg_image_src(ui_Remind_group, &campaign_list_rectangle_04,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_LINE), lv_color_hex(0x333333),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_LINE), 0,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_image_set_src(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_ICON),
                     &campaign_list_remind_icon);

    lv_obj_set_x(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_TXT), 95);
    lv_obj_set_y(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_TXT), 24);
    lv_label_set_text(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_TXT), "Remind");

    lv_obj_set_style_text_color(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_TXT_01),
                                lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_comp_get_child(ui_Remind_group, UI_COMP_SETTING_GROUP_GOAL_TXT_01), 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bnt_group = lv_obj_create(ui_setting_);
    lv_obj_set_width(ui_bnt_group, 326);
    lv_obj_set_height(ui_bnt_group, 88);
    lv_obj_set_x(ui_bnt_group, 42);
    lv_obj_set_y(ui_bnt_group, 394);
    lv_obj_remove_flag(ui_bnt_group, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bnt_group, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bnt_group, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bnt_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bnt_group, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bnt_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancel_icon = lv_image_create(ui_bnt_group);
    lv_image_set_src(ui_cancel_icon, &campaign_list_cancel_icon);
    lv_obj_set_width(ui_cancel_icon, LV_SIZE_CONTENT);   /// 68
    lv_obj_set_height(ui_cancel_icon, LV_SIZE_CONTENT);    /// 68
    lv_obj_set_align(ui_cancel_icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancel_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_cancel_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Primarystatusbar1, ui_event_Primarystatusbar1_Primary_status_bar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goal_group, ui_event_goal_group_Setting_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Remind_group, ui_event_Remind_group_Setting_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bnt_group, ui_event_bnt_group, LV_EVENT_ALL, NULL);

}

void ui_setting__screen_destroy(void)
{
    if(ui_setting_) lv_obj_del(ui_setting_);

    // NULL screen variables
    ui_setting_ = NULL;
    ui_Campaign_List_group1 = NULL;
    ui_Primarystatusbar1 = NULL;
    ui_Setting_group = NULL;
    ui_goal_group = NULL;
    ui_Remind_group = NULL;
    ui_bnt_group = NULL;
    ui_cancel_icon = NULL;

}
