// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "../ui.h"

lv_obj_t * ui_time_setting;
lv_obj_t * ui_time_setting_bg;
lv_obj_t * ui_Primarystatusbar3;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_time_roller;
lv_obj_t * ui_btn_min;
lv_obj_t * ui_min_txt;
lv_obj_t * ui_btn_bg_black1;
lv_obj_t * ui_btn_cancel;
lv_obj_t * ui_btn_bg_black2;
lv_obj_t * ui_btn_comfirm_black1;

// event funtions
void ui_event_btn_bg_black1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Goal, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Goal_screen_init);
    }
}

void ui_event_btn_bg_black2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Indoor_Run, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Indoor_Run_screen_init);
    }
}

// build funtions

void ui_time_setting_screen_init(void)
{
    ui_time_setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_time_setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_time_setting, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_time_setting, lv_color_hex(0xFF0000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_setting, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_time_setting_bg = lv_obj_create(ui_time_setting);
    lv_obj_set_width(ui_time_setting_bg, lv_pct(100));
    lv_obj_set_height(ui_time_setting_bg, lv_pct(100));
    lv_obj_set_align(ui_time_setting_bg, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_time_setting_bg, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_time_setting_bg, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_time_setting_bg, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_time_setting_bg, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time_setting_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_setting_bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time_setting_bg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_time_setting_bg, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_time_setting_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Primarystatusbar3 = ui_Primary_status_bar_create(ui_time_setting);
    lv_obj_set_x(ui_Primarystatusbar3, 0);
    lv_obj_set_y(ui_Primarystatusbar3, 14);

    lv_label_set_text(ui_comp_get_child(ui_Primarystatusbar3, UI_COMP_PRIMARY_STATUS_BAR_CAPTION_ICON), "Time");

    ui_Panel21 = lv_obj_create(ui_time_setting);
    lv_obj_set_width(ui_Panel21, 384);
    lv_obj_set_height(ui_Panel21, 190);
    lv_obj_set_x(ui_Panel21, 0);
    lv_obj_set_y(ui_Panel21, -15);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_roller = lv_roller_create(ui_Panel21);
    lv_roller_set_options(ui_time_roller, "01\n02\n03\n04\n05", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_time_roller, 2, LV_ANIM_OFF);
    lv_obj_set_height(ui_time_roller, 190);
    lv_obj_set_width(ui_time_roller, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_x(ui_time_roller, 0);
    lv_obj_set_y(ui_time_roller, 6);
    lv_obj_set_align(ui_time_roller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_time_roller, lv_color_hex(0x707070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_time_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_time_roller, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time_roller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_roller, &ui_font_HONORS_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time_roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time_roller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time_roller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_time_roller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_roller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time_roller, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_roller, &ui_font_HONOR_M_50, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time_roller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time_roller, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_btn_min = lv_obj_create(ui_time_setting);
    lv_obj_set_width(ui_btn_min, 120);
    lv_obj_set_height(ui_btn_min, 50);
    lv_obj_set_x(ui_btn_min, 4);
    lv_obj_set_y(ui_btn_min, -135);
    lv_obj_set_align(ui_btn_min, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btn_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_min, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_min, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_min, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_min_txt = lv_label_create(ui_btn_min);
    lv_obj_set_width(ui_min_txt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min_txt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_min_txt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min_txt, "Min");
    lv_obj_set_style_text_font(ui_min_txt, &ui_font_HONORS_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_bg_black1 = lv_obj_create(ui_time_setting);
    lv_obj_set_width(ui_btn_bg_black1, 160);
    lv_obj_set_height(ui_btn_bg_black1, 88);
    lv_obj_set_x(ui_btn_bg_black1, 41);
    lv_obj_set_y(ui_btn_bg_black1, 394);
    lv_obj_remove_flag(ui_btn_bg_black1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_bg_black1, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_bg_black1, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_bg_black1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_bg_black1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_bg_black1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_cancel = lv_image_create(ui_btn_bg_black1);
    lv_image_set_src(ui_btn_cancel, &campaign_list_stagger_icon);
    lv_obj_set_width(ui_btn_cancel, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_btn_cancel, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_btn_cancel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_cancel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_btn_cancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn_bg_black2 = lv_obj_create(ui_time_setting);
    lv_obj_set_width(ui_btn_bg_black2, 160);
    lv_obj_set_height(ui_btn_bg_black2, 88);
    lv_obj_set_x(ui_btn_bg_black2, 211);
    lv_obj_set_y(ui_btn_bg_black2, 394);
    lv_obj_remove_flag(ui_btn_bg_black2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn_bg_black2, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn_bg_black2, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn_bg_black2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn_bg_black2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn_bg_black2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btn_comfirm_black1 = lv_image_create(ui_btn_bg_black2);
    lv_image_set_src(ui_btn_comfirm_black1, &campaign_list_treat_icon);
    lv_obj_set_width(ui_btn_comfirm_black1, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_btn_comfirm_black1, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_align(ui_btn_comfirm_black1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_comfirm_black1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_btn_comfirm_black1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btn_bg_black1, ui_event_btn_bg_black1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_bg_black2, ui_event_btn_bg_black2, LV_EVENT_ALL, NULL);

}

void ui_time_setting_screen_destroy(void)
{
    if(ui_time_setting) lv_obj_del(ui_time_setting);

    // NULL screen variables
    ui_time_setting = NULL;
    ui_time_setting_bg = NULL;
    ui_Primarystatusbar3 = NULL;
    ui_Panel21 = NULL;
    ui_time_roller = NULL;
    ui_btn_min = NULL;
    ui_min_txt = NULL;
    ui_btn_bg_black1 = NULL;
    ui_btn_cancel = NULL;
    ui_btn_bg_black2 = NULL;
    ui_btn_comfirm_black1 = NULL;

}
