// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef UI_TIME_SETTING_H
#define UI_TIME_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_time_setting
extern void ui_time_setting_screen_init(void);
extern void ui_time_setting_screen_destroy(void);
extern lv_obj_t * ui_time_setting;
extern lv_obj_t * ui_time_setting_bg;
extern lv_obj_t * ui_Primarystatusbar3;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_time_roller;
extern lv_obj_t * ui_btn_min;
extern lv_obj_t * ui_min_txt;
extern void ui_event_btn_bg_black1(lv_event_t * e);
extern lv_obj_t * ui_btn_bg_black1;
extern lv_obj_t * ui_btn_cancel;
extern void ui_event_btn_bg_black2(lv_event_t * e);
extern lv_obj_t * ui_btn_bg_black2;
extern lv_obj_t * ui_btn_comfirm_black1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

