#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")
CPPDEFINES = []
CPPPATH = [cwd]


if GetDepend('CONFIG_REALTEK_BUILD_LVGL_SIMPLE_DEMO'):
    src += Glob('*.c')
    src += Glob('./card/*.c')
    src += Glob('./cellular/*.c')
    src += Glob('./tileview_slide_snapshot/*.c')
    src += Glob('./lite3d/*.c')

    CPPPATH += [cwd + '/card']
    CPPPATH += [cwd + '/cellular']
    CPPPATH += [cwd + '/tileview_slide_snapshot']
    CPPPATH += [cwd + '/lite3d']

    CPPDEFINES += ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

if not GetDepend(['CONFIG_REALTEK_8773E_DEVICE']) and not GetDepend(['CONFIG_REALTEK_8773G_DEVICE']):
    SrcRemove(src,'app_rtk_port.c')

if GetDepend(['CONFIG_REALTEK_8773E_DEVICE']) or GetDepend(['CONFIG_REALTEK_8773G_DEVICE']):
    SrcRemove(src,'app_sim_port.c')

group = DefineGroup('lvgl_demo_app', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_SIMPLE_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
