// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#ifndef _SCR_TEST_UI_H
#define _SCR_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_clk_01.h"
#include "screens/ui_clk_02.h"
#include "screens/ui_clk_03.h"
#include "screens/ui_clk_04.h"
#include "screens/ui_clk_05.h"
#include "screens/ui_clk_06.h"
#include "screens/ui_clk_07.h"
#include "screens/ui_clk_08.h"
#include "screens/ui_clk_09.h"
#include "screens/ui_clk_10.h"
#include "screens/ui_clk_11.h"
#include "screens/ui_clk_12.h"
#include "screens/ui_clk_13.h"
#include "screens/ui_clk_14.h"
#include "screens/ui_clk_15.h"
#include "screens/ui_clk_16.h"
#include "screens/ui_clk_17.h"
#include "screens/ui_Feature_List.h"
#include "screens/ui_Campaign_List.h"
#include "screens/ui_setting_.h"
#include "screens/ui_Goal.h"
#include "screens/ui_time_setting.h"
#include "screens/ui_calorimetric.h"
#include "screens/ui_reminders.h"
#include "screens/ui_interval_alert.h"
#include "screens/ui_Indoor_Run.h"
#include "screens/ui_Campaign_Countdown.h"
#include "screens/ui_Indoor_Run_data_.h"
#include "screens/ui_Campaign_Pause.h"
#include "screens/ui_Music.h"
#include "screens/ui_Motion_Recording.h"
#include "screens/ui_Outdoor_Run_00.h"
#include "screens/ui_Outdoor_Run_01.h"
#include "screens/ui_Outdoor_Run_02.h"
#include "screens/ui_Outdoor_Run_03.h"
#include "screens/ui_Outdoor_Run_04.h"
#include "screens/ui_Outdoor_Run_05.h"
#include "screens/ui_control_center.h"
#include "screens/ui_setting.h"
#include "screens/ui_Display_Brightness.h"
#include "screens/ui_Interval_Time.h"
#include "screens/ui_workout_setting.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * clk04dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk05dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk06sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk06minut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk06hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk07dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk08dots_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk09hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk09m_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk10timecolon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk12hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk12minut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk12sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk14hour_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk14minut_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk14sec_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk15nobot_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * clk17colon_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
#include "lv_img_dsc_list.h"

// FONTS
LV_FONT_DECLARE(ui_font_HONORS_18);
LV_FONT_DECLARE(ui_font_HONORS_200);
LV_FONT_DECLARE(ui_font_HONORS_220);
LV_FONT_DECLARE(ui_font_HONORS_24);
LV_FONT_DECLARE(ui_font_HONORS_26);
LV_FONT_DECLARE(ui_font_HONORS_28);
LV_FONT_DECLARE(ui_font_HONORS_30);
LV_FONT_DECLARE(ui_font_HONORS_40);
LV_FONT_DECLARE(ui_font_HONORS_D_24);
LV_FONT_DECLARE(ui_font_HONORS_D_28);
LV_FONT_DECLARE(ui_font_HONORS_H_140);
LV_FONT_DECLARE(ui_font_HONOR_80);
LV_FONT_DECLARE(ui_font_LED_180);
LV_FONT_DECLARE(ui_font_LED_190);
LV_FONT_DECLARE(ui_font_LED_24);
LV_FONT_DECLARE(ui_font_LED_54);
LV_FONT_DECLARE(ui_font_LED_86);
LV_FONT_DECLARE(ui_font_Alimm_80);
LV_FONT_DECLARE(ui_font_BAIDU_122);
LV_FONT_DECLARE(ui_font_BEBAS_24);
LV_FONT_DECLARE(ui_font_BEBAS_32);
LV_FONT_DECLARE(ui_font_BEBAS_42);
LV_FONT_DECLARE(ui_font_YOUSHE_26);
LV_FONT_DECLARE(ui_font_YOUSHE_34);
LV_FONT_DECLARE(ui_font_HONO_18);
LV_FONT_DECLARE(ui_font_HONO_24);
LV_FONT_DECLARE(ui_font_EVELYNE_24);
LV_FONT_DECLARE(ui_font_EVELYNE_36);
LV_FONT_DECLARE(ui_font_EVELYNE_84);
LV_FONT_DECLARE(ui_font_HYZi_30);
LV_FONT_DECLARE(ui_font_HY_24);
LV_FONT_DECLARE(ui_font_HY_36);
LV_FONT_DECLARE(ui_font_HY_68);
LV_FONT_DECLARE(ui_font_HY_80);
LV_FONT_DECLARE(ui_font_HY_84);
LV_FONT_DECLARE(ui_font_GOTH_34);
LV_FONT_DECLARE(ui_font_GOTH_80);
LV_FONT_DECLARE(ui_font_HONORS_230);
LV_FONT_DECLARE(ui_font_HONORS_R_20);
LV_FONT_DECLARE(ui_font_HONOR_200);
LV_FONT_DECLARE(ui_font_HONOR_M_22);
LV_FONT_DECLARE(ui_font_HONOR_M_32);
LV_FONT_DECLARE(ui_font_HONOR_M_34);
LV_FONT_DECLARE(ui_font_HONOR_M_50);
LV_FONT_DECLARE(ui_font_HONOR_M_56);
LV_FONT_DECLARE(ui_font_HONOR_M_120);
LV_FONT_DECLARE(ui_font_HONOR_M_140);
LV_FONT_DECLARE(ui_font_HONOR_M_30);
LV_FONT_DECLARE(ui_font_HONOR_M_36);
LV_FONT_DECLARE(ui_font_HONOR_M_40);
LV_FONT_DECLARE(ui_font_HONOR_M_48);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_22);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_26);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_28);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_34);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_44);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_50);
LV_FONT_DECLARE(ui_font_Ping_Fang_B_94);
LV_FONT_DECLARE(ui_font_DIGI_20);
LV_FONT_DECLARE(ui_font_DIGI_34);
LV_FONT_DECLARE(ui_font_DIGI_36);
LV_FONT_DECLARE(ui_font_DIGI_90);
LV_FONT_DECLARE(ui_font_DJB_22);
LV_FONT_DECLARE(ui_font_HONORS_D_34);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
