// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: scr_test

#include "ui_helpers.h"

void _ui_bar_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BAR_PROPERTY_VALUE_WITH_ANIM) lv_bar_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_BAR_PROPERTY_VALUE) lv_bar_set_value(target, val, LV_ANIM_OFF);
}

void _ui_basic_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_BASIC_PROPERTY_POSITION_X) lv_obj_set_x(target, val);
    if(id == _UI_BASIC_PROPERTY_POSITION_Y) lv_obj_set_y(target, val);
    if(id == _UI_BASIC_PROPERTY_WIDTH) lv_obj_set_width(target, val);
    if(id == _UI_BASIC_PROPERTY_HEIGHT) lv_obj_set_height(target, val);
}


void _ui_dropdown_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_DROPDOWN_PROPERTY_SELECTED) lv_dropdown_set_selected(target, val);
}

void _ui_image_set_property(lv_obj_t * target, int id, uint8_t * val)
{
    if(id == _UI_IMAGE_PROPERTY_IMAGE) lv_image_set_src(target, val);
}

void _ui_label_set_property(lv_obj_t * target, int id, const char * val)
{
    if(id == _UI_LABEL_PROPERTY_TEXT) lv_label_set_text(target, val);
}


void _ui_roller_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM) lv_roller_set_selected(target, val, LV_ANIM_ON);
    if(id == _UI_ROLLER_PROPERTY_SELECTED) lv_roller_set_selected(target, val, LV_ANIM_OFF);
}

void _ui_slider_set_property(lv_obj_t * target, int id, int val)
{
    if(id == _UI_SLIDER_PROPERTY_VALUE_WITH_ANIM) lv_slider_set_value(target, val, LV_ANIM_ON);
    if(id == _UI_SLIDER_PROPERTY_VALUE) lv_slider_set_value(target, val, LV_ANIM_OFF);
}

void _ui_delate_useless_screen(lv_obj_t *act_scr, lv_obj_t *dst_scr)
{
    lv_obj_t **screen_ptrs[] = {
        &ui_clk_01,
        &ui_clk_02,
        &ui_clk_03,
        &ui_clk_04,
        &ui_clk_05,
        &ui_clk_06,
        &ui_clk_07,
        &ui_clk_08,
        &ui_clk_09,
        &ui_clk_10,
        &ui_clk_11,
        &ui_clk_12,
        &ui_clk_13,
        &ui_clk_14,
        &ui_clk_15,
        &ui_clk_16,
        &ui_clk_17,
        &ui_Feature_List,
        &ui_Campaign_List,
        &ui_setting_,
        &ui_Goal,
        &ui_time_setting,
        &ui_calorimetric,
        &ui_reminders,
        &ui_interval_alert,
        &ui_Indoor_Run,
        &ui_Campaign_Countdown,
        &ui_Indoor_Run_data_,
        &ui_Campaign_Pause,
        &ui_Music,
        &ui_Motion_Recording,
        &ui_Outdoor_Run_00,
        &ui_Outdoor_Run_01,
        &ui_Outdoor_Run_02,
        &ui_Outdoor_Run_03,
        &ui_Outdoor_Run_04,
        &ui_Outdoor_Run_05,
        &ui_control_center,
        &ui_setting,
        &ui_Display_Brightness,
        &ui_Interval_Time,
        &ui_workout_setting,
    };

    for (int i = 0; i < sizeof(screen_ptrs)/sizeof(screen_ptrs[0]); i++) {
        lv_obj_t *screen = *screen_ptrs[i];
        if (screen && screen != act_scr && screen != dst_scr) {
            _ui_screen_delete(screen_ptrs[i]);
        }
    }
}
static void lv_draw_buf_memcpy(void *dst, const void *src, size_t len)
{
    lv_memcpy(dst, src, len);
}
static void create_snapshot_copy(lv_obj_t *widget, lv_obj_t *img_snapshot, uint8_t *fb)
{
    lv_draw_buf_t *snapshot = (lv_draw_buf_t *)lv_image_get_src(img_snapshot);
    if (snapshot)
    {
        lv_draw_buf_destroy(snapshot);
    }
    snapshot = lv_snapshot_create_draw_buf(widget, lv_display_get_color_format(NULL));
    if (snapshot == NULL)
    {
        LV_LOG_WARN("create snapshot failed");
        return;
    }
    lv_draw_buf_memcpy(snapshot->data, fb, snapshot->data_size);
    lv_image_set_src(img_snapshot, snapshot);
}
static void update_snapshot(lv_obj_t *widget, lv_obj_t *img_snapshot)
{
    lv_draw_buf_t *snapshot = (lv_draw_buf_t *)lv_image_get_src(img_snapshot);
    if (snapshot)
    {
        lv_draw_buf_destroy(snapshot);
    }
    snapshot = lv_snapshot_take(widget, lv_display_get_color_format(NULL));
    if (snapshot == NULL)
    {
        LV_LOG_WARN("create snapshot failed");
        return;
    }
    lv_image_set_src(img_snapshot, snapshot);
}

static void create_snapshot_normal(lv_obj_t *widget, lv_obj_t *img_snapshot)
{
    update_snapshot(widget, img_snapshot);
}
static lv_obj_t *create_snapshot_obj_directly(lv_obj_t *parent, lv_obj_t *target)
{
    lv_obj_t *snapshot = lv_image_create(parent);
    lv_obj_set_size(snapshot, lv_obj_get_width(target), lv_obj_get_height(target));
    lv_obj_update_layout(snapshot);

    lv_area_t widget_area;
    lv_obj_get_coords(target, &widget_area);
    lv_area_t screen_area;
    screen_area.x1 = 0;
    screen_area.x2 = lv_display_get_horizontal_resolution(NULL) - 1;
    screen_area.y1 = 0;
    screen_area.y2 = lv_display_get_vertical_resolution(NULL) - 1;

    lv_area_t img_snapshot_area;
    lv_obj_get_coords(snapshot, &img_snapshot_area);

    if (lv_area_is_equal(&widget_area, &screen_area) &&
        lv_area_is_equal(&img_snapshot_area, &screen_area))
    {
        if (lv_display_get_default()->render_mode == LV_DISPLAY_RENDER_MODE_DIRECT ||
            lv_display_get_default()->render_mode == LV_DISPLAY_RENDER_MODE_FULL)
        {
            uint8_t *fb = lv_display_get_buf_active(NULL)->data;
            create_snapshot_copy(target, snapshot, fb);
        }
        else if (lv_display_get_user_data(NULL) != NULL)
        {
            uint8_t *fb = lv_display_get_user_data(NULL);
            create_snapshot_copy(target, snapshot, fb);
        }
        LV_LOG_INFO("widget_area is equal to screen_area, goto create_snapshot_copy");
        return snapshot;
    }
    create_snapshot_normal(target, snapshot);

    // lv_obj_add_flag(target, LV_OBJ_FLAG_HIDDEN);
    return snapshot;
}
static void delete_snapshot(lv_obj_t *img_snapshot)
{
    lv_draw_buf_t *snapshot = (lv_draw_buf_t *)lv_image_get_src(img_snapshot);
    if (snapshot)
    {
        lv_draw_buf_destroy(snapshot);
        // lv_image_set_src(img_snapshot, NULL);
    }
}
static void snapshot_custom_cb_delete(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *img_snapshot = lv_event_get_current_target(e);
    delete_snapshot(img_snapshot);
}
static void screen_change_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *screen = lv_event_get_current_target(e);
    if (code == LV_EVENT_SCREEN_LOAD_START)
    {
        // LV_LOG_USER("LV_EVENT_SCREEN_LOAD_START");
        lv_obj_t *snapshot = create_snapshot_obj_directly(screen, screen);
        lv_obj_add_event_cb(snapshot, snapshot_custom_cb_delete, LV_EVENT_DELETE, NULL);
        lv_obj_set_user_data(screen, snapshot);
        for (int i = 0; i < lv_obj_get_child_count(screen); i++)
        {
            lv_obj_t *obj = lv_obj_get_child(screen, i);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_HIDDEN);
        }
        lv_obj_remove_flag(snapshot, LV_OBJ_FLAG_HIDDEN);
    }
    else if (code == LV_EVENT_SCREEN_LOADED)
    {
        // LV_LOG_USER("LV_EVENT_SCREEN_LOADED");
        lv_obj_t *snapshot = lv_obj_get_user_data(screen);
        for (int i = 0; i < lv_obj_get_child_count(screen); i++)
        {
            lv_obj_t *obj = lv_obj_get_child(screen, i);
            lv_obj_remove_flag(obj, LV_OBJ_FLAG_HIDDEN);
        }
        lv_obj_delete(snapshot);
    }
    if (code == LV_EVENT_SCREEN_UNLOAD_START)
    {
        // LV_LOG_USER("LV_EVENT_SCREEN_UNLOAD_START");
        lv_obj_t *snapshot = create_snapshot_obj_directly(screen, screen);
        lv_obj_add_event_cb(snapshot, snapshot_custom_cb_delete, LV_EVENT_DELETE, NULL);
        lv_obj_set_user_data(screen, snapshot);
        for (int i = 0; i < lv_obj_get_child_count(screen); i++)
        {
            lv_obj_t *obj = lv_obj_get_child(screen, i);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_HIDDEN);
        }
        lv_obj_remove_flag(snapshot, LV_OBJ_FLAG_HIDDEN);
    }
    else if (code == LV_EVENT_SCREEN_UNLOADED)
    {
        // LV_LOG_USER("LV_EVENT_SCREEN_UNLOADED");
        lv_obj_t *snapshot = lv_obj_get_user_data(screen);
        lv_obj_delete(snapshot);
    }
}

/*original code from squareline studio*/
/*
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    if(*target == NULL)
        target_init();
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}
*/
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay,
                       void (*target_init)(void))
{
    target_init();
    lv_anim_delete_all();

    lv_obj_add_event_cb(*target, screen_change_cb, LV_EVENT_SCREEN_LOAD_START, NULL);
    lv_obj_add_event_cb(*target, screen_change_cb, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(lv_screen_active(), screen_change_cb, LV_EVENT_SCREEN_UNLOAD_START, NULL);
    lv_obj_add_event_cb(lv_screen_active(), screen_change_cb, LV_EVENT_SCREEN_UNLOADED, NULL);

    lv_screen_load_anim(*target, fademode, 300, delay, true);
}

void _ui_screen_delete(lv_obj_t ** target)
{
    if(*target != NULL) {
        lv_obj_delete(*target);
        *target = NULL;
    }
}

void _ui_arc_increment(lv_obj_t * target, int val)
{
    int old = lv_arc_get_value(target);
    lv_arc_set_value(target, old + val);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_bar_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_bar_get_value(target);
    lv_bar_set_value(target, old + val, anm);
}

void _ui_slider_increment(lv_obj_t * target, int val, int anm)
{
    int old = lv_slider_get_value(target);
    lv_slider_set_value(target, old + val, anm);
    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_keyboard_set_target(lv_obj_t * keyboard, lv_obj_t * textarea)
{
    lv_keyboard_set_textarea(keyboard, textarea);
}

void _ui_flag_modify(lv_obj_t * target, int32_t flag, int value)
{
    if(value == _UI_MODIFY_FLAG_TOGGLE) {
        if(lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    }
    else if(value == _UI_MODIFY_FLAG_ADD) lv_obj_add_flag(target, flag);
    else lv_obj_remove_flag(target, flag);
}
void _ui_state_modify(lv_obj_t * target, int32_t state, int value)
{
    if(value == _UI_MODIFY_STATE_TOGGLE) {
        if(lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    }
    else if(value == _UI_MODIFY_STATE_ADD) lv_obj_add_state(target, state);
    else lv_obj_remove_state(target, state);
}


void _ui_textarea_move_cursor(lv_obj_t * target, int val)

{

    if(val == UI_MOVE_CURSOR_UP) lv_textarea_cursor_up(target);
    if(val == UI_MOVE_CURSOR_RIGHT) lv_textarea_cursor_right(target);
    if(val == UI_MOVE_CURSOR_DOWN) lv_textarea_cursor_down(target);
    if(val == UI_MOVE_CURSOR_LEFT) lv_textarea_cursor_left(target);
    lv_obj_add_state(target, LV_STATE_FOCUSED);
}

void scr_unloaded_delete_cb(lv_event_t * e)

{

    lv_obj_t ** var = lv_event_get_user_data(e);
    lv_obj_delete(*var);
    (*var) = NULL;

}

void _ui_opacity_set(lv_obj_t * target, int val)
{
    lv_obj_set_style_opa(target, val, 0);
}

void _ui_anim_callback_free_user_data(lv_anim_t * a)
{
    lv_free(a->user_data);
    a->user_data = NULL;
}

void _ui_anim_callback_set_x(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_x(usr->target, v);

}


void _ui_anim_callback_set_y(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_y(usr->target, v);

}


void _ui_anim_callback_set_width(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_width(usr->target, v);

}


void _ui_anim_callback_set_height(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_height(usr->target, v);

}


void _ui_anim_callback_set_opacity(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_obj_set_style_opa(usr->target, v, 0);

}


void _ui_anim_callback_set_image_zoom(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_scale(usr->target, v);

}


void _ui_anim_callback_set_image_angle(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    lv_image_set_rotation(usr->target, v);

}


void _ui_anim_callback_set_image_frame(lv_anim_t * a, int32_t v)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    usr->val = v;

    if(v < 0) v = 0;
    if(v >= usr->imgset_size) v = usr->imgset_size - 1;
    lv_image_set_src(usr->target, usr->imgset[v]);
}

int32_t _ui_anim_callback_get_x(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_x_aligned(usr->target);

}


int32_t _ui_anim_callback_get_y(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_y_aligned(usr->target);

}


int32_t _ui_anim_callback_get_width(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_width(usr->target);

}


int32_t _ui_anim_callback_get_height(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_height(usr->target);

}


int32_t _ui_anim_callback_get_opacity(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_obj_get_style_opa(usr->target, 0);

}

int32_t _ui_anim_callback_get_image_zoom(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_scale(usr->target);

}

int32_t _ui_anim_callback_get_image_angle(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return lv_image_get_rotation(usr->target);

}

int32_t _ui_anim_callback_get_image_frame(lv_anim_t * a)

{

    ui_anim_user_data_t * usr = (ui_anim_user_data_t *)a->user_data;
    return usr->val;

}

void _ui_arc_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_arc_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}

void _ui_slider_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * prefix, const char * postfix)
{
    char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

    lv_snprintf(buf, sizeof(buf), "%s%d%s", prefix, (int)lv_slider_get_value(src), postfix);

    lv_label_set_text(trg, buf);
}
void _ui_checked_set_text_value(lv_obj_t * trg, lv_obj_t * src, const char * txt_on, const char * txt_off)
{
    if(lv_obj_has_state(src, LV_STATE_CHECKED)) lv_label_set_text(trg, txt_on);
    else lv_label_set_text(trg, txt_off);
}


void _ui_spinbox_step(lv_obj_t * target, int val)

{

    if(val > 0) lv_spinbox_increment(target);

    else lv_spinbox_decrement(target);


    lv_obj_send_event(target, LV_EVENT_VALUE_CHANGED, 0);
}

void _ui_switch_theme(int val)

{

#ifdef UI_THEME_ACTIVE
    ui_theme_set(val);
#endif
}


